- In this Notebook, I am trying to integrate the training data from the backscore and rest of the period from prj-prod-dataplatform.audit_balance.ml_model_run_details table.
- In this I will compare the training period with each month of test period.

**Steps to Follow**:

* Read the specific model data from prj-prod-dataplatform.audit_balance.ml_model_run_details table
* Expand the calcFeature column to extract all the features for the model
* Read the data from specific backscore table for the training data
* Identify the features and create a list
* Use transform_data function to create the same structure as ml_model_run_details table
* Insert the data to a similar training table - prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
* Read the specific model data from prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
* expand the training set from the calcFeature column
* Concatenate both the test and train datasets
* Calculate the PSI using the PSI function comparing it with the train set
* Insert the result to a PSI table prj-prod-dataplatform.dap_ds_poweruser_playground.alpha_cic_sil_model_psi_v4

# **PSI - CSI Calculation**

## Define Libraries

In [1]:
# %% [markdown]
# # Jupyter Notebook Loading Header
#
# This is a custom loading header for Jupyter Notebooks in Visual Studio Code.
# It includes common imports and settings to get you started quickly.
# %% [markdown]
## Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.cloud import bigquery
from google.cloud import storage
import os
import tempfile
import time
from datetime import datetime
import uuid
import joblib
import uuid

import gcsfs
import duckdb as dd
import pickle
import joblib
from typing import Union
import io
path = r'C:\Users\Dwaipayan\AppData\Roaming\gcloud\legacy_credentials\dchakroborti@tonikbank.com\adc.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = path
client = bigquery.Client(project='prj-prod-dataplatform')
os.environ["GOOGLE_CLOUD_PROJECT"] = "prj-prod-dataplatform"

# %% [markdown]
## Configure Settings
# Set options or configurations as needed
pd.set_option('display.max_columns', None)
pd.set_option("Display.max_rows", 100)

## Function

In [2]:
# Method 1: Using regex to remove all "Calc_" occurrences
def clean_names_regex(name):
    return re.sub(r'_Calc_', '_', name)

# Method 2: Simple string replacement
def clean_names_replace(name):
    return name.replace('_Calc_', '_')

## expand_calc_features_robust

In [3]:
import pandas as pd
import json

def expand_calc_features_robust(df):
    """
    Expand the calcFeatures JSON column into separate columns and return the complete DataFrame.
    
    Parameters:
    df (pd.DataFrame): Input DataFrame with calcFeatures column containing JSON data
    
    Returns:
    pd.DataFrame: Expanded DataFrame with all original columns plus JSON features as separate columns
    """
    
    # Make a copy to avoid modifying the original DataFrame
    df_expanded = df.copy()
    
    # Parse the calcFeatures JSON column
    calc_features_data = []
    
    for idx, calc_features_str in enumerate(df['calcFeatures']):
        try:
            # Handle None or NaN values
            if pd.isna(calc_features_str):
                calc_features_data.append({})
                continue
            
            # Convert to string if not already
            calc_features_str = str(calc_features_str)
            
            # Parse the JSON string
            features_dict = json.loads(calc_features_str.replace("'", '"'))
            
            # Ensure it's a dictionary, not a list
            if isinstance(features_dict, dict):
                calc_features_data.append(features_dict)
            elif isinstance(features_dict, list):
                # If it's a list, convert to dict with index keys or skip
                print(f"Warning: calcFeatures at index {idx} is a list, converting to dict")
                calc_features_data.append({'raw_list': features_dict})
            else:
                print(f"Warning: calcFeatures at index {idx} is neither dict nor list: {type(features_dict)}")
                calc_features_data.append({})
                
        except (json.JSONDecodeError, AttributeError, TypeError) as e:
            # If parsing fails, create an empty dict and print warning
            print(f"Warning: Could not parse calcFeatures at index {idx}: {e}")
            print(f"  Value: {calc_features_str}")
            calc_features_data.append({})
    
    # Create DataFrame from the parsed JSON data
    calc_features_df = pd.DataFrame(calc_features_data)
    
    # Add prefix to JSON-derived columns to avoid conflicts
    calc_features_df = calc_features_df.add_prefix('calc_')
    
    # Reset index to ensure proper alignment
    df_expanded = df_expanded.reset_index(drop=True)
    calc_features_df = calc_features_df.reset_index(drop=True)
    
    # Combine original DataFrame with expanded calcFeatures
    result_df = pd.concat([df_expanded, calc_features_df], axis=1)
    
    return result_df

### dropping_duplicates

In [4]:
def dropping_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    """
    Drop duplicates based on digitalLoanAccountId, Data_selection, and modelVersionid,
    keeping the first occurrence based on appln_submit_datetime.

    Parameters:
    -----------
    df : pd.DataFrame
        Input dataframe

    Returns:
    --------
    pd.DataFrame with duplicates dropped
    """

    df = df.sort_values(
        ['digitalLoanAccountId', 'Data_selection', 'modelVersionId', 'appln_submit_datetime'],
        ascending=[True, True, True, True],
        na_position='last'
    )

    result = df.drop_duplicates(
        subset=['digitalLoanAccountId', 'Data_selection', 'modelVersionId'],
        keep='first'
    ).copy()

    return result

### PSI Pipeline Version 1

In [5]:
# import pandas as pd
# import numpy as np
# from datetime import datetime
# from typing import List, Dict, Optional, Tuple

# class PSICalculator:
#     """
#     A class to calculate Population Stability Index (PSI) with support for 
#     multiple segments and score columns.
#     """
    
#     def __init__(self, df: pd.DataFrame):
#         """
#         Initialize the PSI Calculator with a combined dataframe.
        
#         Parameters:
#         -----------
#         df : pd.DataFrame
#             Combined dataframe with train and test data
#         """
#         self.df = df.copy()
#         self._prepare_data()
    
#     def _prepare_data(self):
#         """Prepare and clean the data for PSI calculation."""
#         # Convert score columns to numeric
#         if 'score' in self.df.columns:
#             self.df['score'] = pd.to_numeric(self.df['score'], errors='coerce')
        
#         # Convert Application_month to datetime
#         if 'Application_month' in self.df.columns:
#             if self.df['Application_month'].dtype != 'datetime64[ns]':
#                 self.df['Application_month'] = pd.to_datetime(
#                     self.df['Application_month'] + '-01'
#                 )
        
#         # Standardize Data_selection column (handle case sensitivity)
#         if 'Data_selection' in self.df.columns:
#             self.df['Data_selection'] = self.df['Data_selection'].str.strip().str.title()
    
#     def _calculate_decile_bins(self, train_scores: pd.Series) -> np.ndarray:
#         """
#         Calculate decile bins from training data.
        
#         Parameters:
#         -----------
#         train_scores : pd.Series
#             Training set scores
        
#         Returns:
#         --------
#         np.ndarray
#             Array of bin edges for deciles
#         """
#         _, bins = pd.qcut(train_scores.dropna(), 10, labels=False, retbins=True)
#         return bins
    
#     def _get_distribution(
#         self, 
#         scores: pd.Series, 
#         bins: np.ndarray
#     ) -> pd.Series:
#         """
#         Get the decile distribution for a set of scores.
        
#         Parameters:
#         -----------
#         scores : pd.Series
#             Scores to bin
#         bins : np.ndarray
#             Decile bin edges
        
#         Returns:
#         --------
#         pd.Series
#             Distribution across deciles (0-9)
#         """
#         deciles = pd.cut(scores.dropna(), bins=bins, labels=False, include_lowest=True)
#         distribution = pd.Series(deciles).value_counts().sort_index() / len(scores)
        
#         # Align with all 10 deciles
#         all_bins = range(10)
#         distribution_aligned = distribution.reindex(all_bins, fill_value=0)
#         return distribution_aligned
    
#     def _calculate_psi_value(
#         self, 
#         current_dist: pd.Series, 
#         baseline_dist: pd.Series
#     ) -> float:
#         """
#         Calculate PSI value given two distributions.
        
#         Parameters:
#         -----------
#         current_dist : pd.Series
#             Current period distribution
#         baseline_dist : pd.Series
#             Baseline period distribution
        
#         Returns:
#         --------
#         float
#             PSI value
#         """
#         # Add small constant to avoid log(0)
#         epsilon = 1e-10
#         current_dist = current_dist + epsilon
#         baseline_dist = baseline_dist + epsilon
        
#         psi = (current_dist - baseline_dist) * np.log(current_dist / baseline_dist)
#         return psi.sum()
    
#     def calculate_psi_by_segment(
#         self,
#         score_column: str = 'score',
#         segment_columns: Optional[List[str]] = None,
#         date_column: str = 'Application_month',
#         data_selection_column: str = 'Data_selection',
#         account_id_column: str = 'digitalLoanAccountId'
#     ) -> pd.DataFrame:
#         """
#         Calculate PSI for each segment and month.
        
#         Parameters:
#         -----------
#         score_column : str
#             Name of the score column to analyze
#         segment_columns : Optional[List[str]]
#             List of columns to segment by. If None, calculates overall PSI only.
#             Example: ['modelVersionId', 'trenchCategory', 'loan_product_type']
#         date_column : str
#             Name of the application month column
#         data_selection_column : str
#             Name of the column distinguishing train/test data
#         account_id_column : str
#             Name of the account ID column for counting distinct accounts
        
#         Returns:
#         --------
#         pd.DataFrame
#             DataFrame with columns: Month, scorename, DateCategory, psivalues, 
#             account_count, segment_column, segment_value
#         """
        
#         # Validate inputs
#         if score_column not in self.df.columns:
#             raise ValueError(f"Score column '{score_column}' not found in dataframe")
        
#         if segment_columns is None:
#             segment_columns = []
        
#         # Check all required columns exist
#         required_cols = [date_column, data_selection_column, account_id_column, score_column]
#         missing_cols = [col for col in required_cols + segment_columns if col not in self.df.columns]
#         if missing_cols:
#             raise ValueError(f"Missing columns: {missing_cols}")
        
#         # Separate train and test data
#         train_df = self.df[self.df[data_selection_column].str.lower() == 'train'].copy()
#         test_df = self.df[self.df[data_selection_column].str.lower() == 'test'].copy()
        
#         if train_df.empty:
#             raise ValueError("No training data found")
#         if test_df.empty:
#             raise ValueError("No test data found")
        
#         # Calculate baseline decile bins from training data
#         train_bins = self._calculate_decile_bins(train_df[score_column])
#         baseline_dist = self._get_distribution(train_df[score_column], train_bins)
        
#         results = []
        
#         # Get last training month
#         last_train_month = train_df[date_column].max()
#         last_train_month_str = last_train_month.strftime('%Y-%m')
        
#         # Case 1: Overall PSI (no segments)
#         if not segment_columns:
#             # Add training set PSI
#             train_psi = self._calculate_psi_value(baseline_dist, baseline_dist)
#             results.append({
#                 'Month': last_train_month_str,
#                 'scorename': score_column,
#                 'DateCategory': 'Training',
#                 'psivalues': train_psi,
#                 'account_count': train_df[account_id_column].nunique(),
#                 'segment_column': None,
#                 'segment_value': None
#             })
            
#             # Calculate monthly PSI for test set
#             for month in sorted(test_df[date_column].unique()):
#                 month_str = month.strftime('%Y-%m')
#                 month_df = test_df[test_df[date_column] == month]
#                 if not month_df.empty:
#                     month_dist = self._get_distribution(month_df[score_column], train_bins)
#                     month_psi = self._calculate_psi_value(month_dist, baseline_dist)
#                     results.append({
#                         'Month': month_str,
#                         'scorename': score_column,
#                         'DateCategory': 'Monthly',
#                         'psivalues': month_psi,
#                         'account_count': month_df[account_id_column].nunique(),
#                         'segment_column': None,
#                         'segment_value': None
#                     })
        
#         # Case 2: Segmented PSI
#         else:
#             # For each segment column
#             for seg_col in segment_columns:
#                 # Training set PSI by segment
#                 for seg_val in train_df[seg_col].unique():
#                     if pd.isna(seg_val):
#                         continue
                    
#                     seg_train_df = train_df[train_df[seg_col] == seg_val]
#                     if not seg_train_df.empty:
#                         seg_baseline_dist = self._get_distribution(
#                             seg_train_df[score_column], 
#                             train_bins
#                         )
#                         seg_train_psi = self._calculate_psi_value(
#                             seg_baseline_dist, 
#                             seg_baseline_dist
#                         )
#                         results.append({
#                             'Month': last_train_month_str,
#                             'scorename': score_column,
#                             'DateCategory': 'Training',
#                             'psivalues': seg_train_psi,
#                             'account_count': seg_train_df[account_id_column].nunique(),
#                             'segment_column': seg_col,
#                             'segment_value': str(seg_val)
#                         })
                
#                 # Monthly PSI by segment for test set
#                 for month in sorted(test_df[date_column].unique()):
#                     month_str = month.strftime('%Y-%m')
#                     month_df = test_df[test_df[date_column] == month]
                    
#                     for seg_val in month_df[seg_col].unique():
#                         if pd.isna(seg_val):
#                             continue
                        
#                         seg_month_df = month_df[month_df[seg_col] == seg_val]
#                         if not seg_month_df.empty:
#                             seg_month_dist = self._get_distribution(
#                                 seg_month_df[score_column], 
#                                 train_bins
#                             )
#                             seg_month_psi = self._calculate_psi_value(
#                                 seg_month_dist, 
#                                 baseline_dist
#                             )
#                             results.append({
#                                 'Month': month_str,
#                                 'scorename': score_column,
#                                 'DateCategory': 'Monthly',
#                                 'psivalues': seg_month_psi,
#                                 'account_count': seg_month_df[account_id_column].nunique(),
#                                 'segment_column': seg_col,
#                                 'segment_value': str(seg_val)
#                             })
        
#         return pd.DataFrame(results)


# # Usage Examples:
# # ===============

# # Example 1: Overall PSI (no segments)
# # psi_calc = PSICalculator(df_

### PSI Pipeline Version 2

In [6]:
import pandas as pd
import numpy as np
from datetime import datetime
from itertools import product, combinations

def calculate_psi_with_segments(
    df,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=None,
    num_bins=10,
    train_label='Train',
    test_label='Test'
):
    """
    Calculate Population Stability Index (PSI) with waterfall segmentation support.
    Creates waterfall combinations: first segment alone, then segment1+segment2, 
    then segment1+segment2+segment3, etc.
    Each segment uses its own training distribution.
    
    Parameters:
    -----------
    df : pd.DataFrame
        Combined dataframe with train and test data
    score_column : str
        Name of the score column (default: 'score')
    date_column : str
        Name of the date column (default: 'Application_month')
    data_selection_column : str
        Name of the column indicating train/test split (default: 'Data_selection')
    segment_columns : list
        List of column names to segment by in waterfall order.
        Example: ['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
    num_bins : int
        Number of bins/deciles for PSI calculation (default: 10)
    train_label : str
        Value indicating training data (default: 'Train')
    test_label : str
        Value indicating test data (default: 'Test')
    
    Returns:
    --------
    pd.DataFrame
        Output dataframe with columns: Month, scorename, DateCategory, psivalues, 
        account_count, modelVersionId, trenchCategory, new_loan_type, 
        loan_product_type, osType
    """
    
    # Create a copy to avoid modifying original data
    df = df.copy()
    
    # Convert score to numeric
    df[score_column] = pd.to_numeric(df[score_column], errors='coerce')
    
    # Convert Application_month to datetime if needed
    if df[date_column].dtype != 'datetime64[ns]':
        df[date_column] = pd.to_datetime(df[date_column].astype(str) + '-01', errors='coerce')
    
    # Separate train and test data
    train_df = df[df[data_selection_column] == train_label].copy()
    test_df = df[df[data_selection_column] == test_label].copy()
    
    # Handle missing values
    train_df = train_df.dropna(subset=[score_column])
    test_df = test_df.dropna(subset=[score_column])
    
    if train_df.empty or test_df.empty:
        raise ValueError("Train or Test dataframe is empty after removing NaN values")
    
    # If no segment columns specified, calculate overall PSI
    if segment_columns is None or len(segment_columns) == 0:
        segment_columns = []
    
    # Function to calculate PSI with predefined bins
    def calculate_psi_with_bins(data_scores, train_distribution, decile_bins):
        """
        Calculate PSI using pre-defined decile bins from training data.
        """
        if len(data_scores) == 0:
            return np.nan
        
        # Bin the scores using the training bins
        data_binned = pd.cut(data_scores, bins=decile_bins, labels=False, include_lowest=True)
        
        # Get distribution of current data
        current_dist = pd.Series(data_binned).value_counts().sort_index() / len(data_scores)
        
        # Align with training distribution (ensure all bins are represented)
        all_bins = range(num_bins)
        current_dist_aligned = current_dist.reindex(all_bins, fill_value=1e-10)
        train_dist_aligned = train_distribution.reindex(all_bins, fill_value=1e-10)
        
        # Calculate PSI
        psi_values = (current_dist_aligned - train_dist_aligned) * np.log(current_dist_aligned / train_dist_aligned)
        
        return psi_values.sum()
    
    # Get the last month of the training set
    last_train_month = train_df[date_column].max()
    last_train_month_str = last_train_month.strftime('%Y-%m')
    
    # Initialize results list
    psi_results = []
    
    # Define all possible segment columns (for creating NA columns)
    all_possible_segments = ['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
    
    # If no segments, calculate overall PSI
    if len(segment_columns) == 0:
        # Calculate training deciles and distribution
        train_score_binned = pd.qcut(train_df[score_column], num_bins, labels=False, duplicates='drop')
        train_distribution = train_score_binned.value_counts().sort_index() / len(train_df[score_column])
        _, train_decile_bins = pd.qcut(train_df[score_column], num_bins, retbins=True, duplicates='drop')
        
        # Training set PSI
        train_psi = calculate_psi_with_bins(train_df[score_column], train_distribution, train_decile_bins)
        result_row = {
            'Month': last_train_month_str,
            'scorename': score_column,
            'DateCategory': 'Training',
            'psivalues': train_psi,
            'account_count': train_df['digitalLoanAccountId'].nunique(),
        }
        # Add all segment columns as NA
        for seg_col in all_possible_segments:
            result_row[seg_col] = 'NA'
        psi_results.append(result_row)
        
        # Monthly PSI for test set
        for month in sorted(test_df[date_column].unique()):
            month_str = month.strftime('%Y-%m')
            month_df = test_df[test_df[date_column] == month]
            
            if not month_df.empty:
                month_psi = calculate_psi_with_bins(month_df[score_column], train_distribution, train_decile_bins)
                result_row = {
                    'Month': month_str,
                    'scorename': score_column,
                    'DateCategory': 'Monthly',
                    'psivalues': month_psi,
                    'account_count': month_df['digitalLoanAccountId'].nunique(),
                }
                for seg_col in all_possible_segments:
                    result_row[seg_col] = 'NA'
                psi_results.append(result_row)
    
    else:
        # Create waterfall combinations
        # For waterfall: [col1], [col1, col2], [col1, col2, col3], etc.
        waterfall_combinations = []
        for i in range(1, len(segment_columns) + 1):
            waterfall_combinations.append(segment_columns[:i])
        
        # Process each waterfall level
        for current_segments in waterfall_combinations:
            
            # Get unique values for each segment column in current waterfall level
            segment_combinations = []
            for seg_col in current_segments:
                unique_vals = df[seg_col].dropna().unique()
                segment_combinations.append([(seg_col, val) for val in unique_vals])
            
            # Generate all combinations for this waterfall level
            for seg_combo in product(*segment_combinations):
                # Filter data for this segment combination
                seg_filter = df.copy()
                
                for seg_col, seg_val in seg_combo:
                    seg_filter = seg_filter[seg_filter[seg_col] == seg_val]
                
                if seg_filter.empty:
                    continue
                
                # Split by train/test for this segment
                seg_train = seg_filter[seg_filter[data_selection_column] == train_label].copy()
                seg_test = seg_filter[seg_filter[data_selection_column] == test_label].copy()
                
                # Skip if segment has no data
                if seg_train.empty or seg_test.empty:
                    continue
                
                # Remove NaN values
                seg_train = seg_train.dropna(subset=[score_column])
                seg_test = seg_test.dropna(subset=[score_column])
                
                if seg_train.empty or seg_test.empty:
                    continue
                
                # Calculate training distribution SPECIFIC to this segment
                seg_train_binned = pd.qcut(
                    seg_train[score_column],
                    num_bins,
                    labels=False,
                    duplicates='drop'
                )
                seg_train_dist = seg_train_binned.value_counts().sort_index() / len(seg_train[score_column])
                
                # Get decile bins specific to this segment's training data
                _, seg_train_decile_bins = pd.qcut(
                    seg_train[score_column],
                    num_bins,
                    retbins=True,
                    duplicates='drop'
                )
                
                # Training set PSI for this segment
                seg_train_psi = calculate_psi_with_bins(seg_train[score_column], seg_train_dist, seg_train_decile_bins)
                
                # Create result row for training
                result_row = {
                    'Month': last_train_month_str,
                    'scorename': score_column,
                    'DateCategory': 'Training',
                    'psivalues': seg_train_psi,
                    'account_count': seg_train['digitalLoanAccountId'].nunique(),
                }
                
                # Add segment values
                for seg_col, seg_val in seg_combo:
                    result_row[seg_col] = seg_val
                
                # Add NA for segments not in this waterfall level
                for seg_col in all_possible_segments:
                    if seg_col not in [col for col, _ in seg_combo]:
                        result_row[seg_col] = 'NA'
                
                psi_results.append(result_row)
                
                # Monthly PSI for test set (this segment)
                for month in sorted(seg_test[date_column].unique()):
                    month_str = month.strftime('%Y-%m')
                    month_df = seg_test[seg_test[date_column] == month]
                    
                    if not month_df.empty:
                        month_psi = calculate_psi_with_bins(month_df[score_column], seg_train_dist, seg_train_decile_bins)
                        
                        result_row = {
                            'Month': month_str,
                            'scorename': score_column,
                            'DateCategory': 'Monthly',
                            'psivalues': month_psi,
                            'account_count': month_df['digitalLoanAccountId'].nunique(),
                        }
                        
                        # Add segment values
                        for seg_col, seg_val in seg_combo:
                            result_row[seg_col] = seg_val
                        
                        # Add NA for segments not in this waterfall level
                        for seg_col in all_possible_segments:
                            if seg_col not in [col for col, _ in seg_combo]:
                                result_row[seg_col] = 'NA'
                        
                        psi_results.append(result_row)
    
    # Create output dataframe
    output_df = pd.DataFrame(psi_results)
    
    # Reorder columns
    column_order = ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count'] + all_possible_segments
    output_df = output_df[[col for col in column_order if col in output_df.columns]]
    
    return output_df


# USAGE EXAMPLES:
# ===============

# Example 1: Waterfall segmentation with all levels
# score_output_df = calculate_psi_with_segments(
#     df=df_combined,
#     score_column='score',
#     date_column='Application_month',
#     data_selection_column='Data_selection',
#     segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
# )

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

# print(f"Output shape: {score_output_df.shape}")
# print(f"\nOutput columns: {score_output_df.columns.tolist()}")
# print(f"\nFirst few rows:")
# print(score_output_df.head(20))
# print(f"\nData types:")
# print(score_output_df.dtypes)

# Config query

In [7]:
sq = """ WITH base AS (
  -- First part with actual trenchCategory
  SELECT 
    modelDisplayName, 
    modelVersionId, 
    CASE 
      WHEN trenchCategory IS NULL THEN 'ALL'
      WHEN trenchCategory = '' THEN 'ALL'
      ELSE trenchCategory 
    END AS trenchCategory,
(CASE 
      WHEN modelDisplayName LIKE '%sil%' THEN 'SIL'
      WHEN modelDisplayName LIKE '%cash%' THEN 'CASH'
      ELSE 'ALL' 
    END) AS product_category,
  FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`

  
  UNION ALL
  
  -- Second part with 'ALL' trenchCategory
  SELECT 
    modelDisplayName, 
    modelVersionId, 
    'ALL' AS trenchCategory,
    (CASE 
      WHEN modelDisplayName LIKE '%sil%' THEN 'SIL'
      WHEN modelDisplayName LIKE '%cash%' THEN 'CASH'
      ELSE 'ALL' 
    END) AS product_category,
  FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
  WHERE trenchCategory IS NOT NULL

)
SELECT distinct
  modelDisplayName, 
  modelVersionId, 
  trenchCategory, 
  product_category,
FROM base
ORDER BY 4, 1, 2, 3;"""

configdf = client.query(sq).to_dataframe()
configdf

          modelDisplayName modelVersionId trenchCategory product_category
0       alpha_income_model             v1            ALL              ALL
1        beta_income_model             v1            ALL              ALL
2        beta_income_model             v1       Trench 1              ALL
3        beta_income_model             v1       Trench 2              ALL
4        beta_income_model             v1       Trench 3              ALL
5   alpha_stack_model_cash             v1            ALL             CASH
6   alpha_stack_model_cash             v1       Trench 1             CASH
7   alpha_stack_model_cash             v1       Trench 2             CASH
8   alpha_stack_model_cash             v1       Trench 3             CASH
9   alpha_stack_model_cash           v1.1            ALL             CASH
10  alpha_stack_model_cash           v1.1       Trench 1             CASH
11  alpha_stack_model_cash           v1.1       Trench 2             CASH
12         apps_score_cash             v1            ALL             CASH
13         apps_score_cash             v1       Trench 1             CASH
14         apps_score_cash             v1       Trench 2             CASH
15         apps_score_cash             v1       Trench 3             CASH
16         apps_score_cash           v1.1            ALL             CASH
17         apps_score_cash           v1.1       Trench 1             CASH
18         apps_score_cash           v1.1       Trench 2             CASH
19    beta_demo_model_cash             v1            ALL             CASH
20    beta_demo_model_cash             v1       Trench 1             CASH
21    beta_demo_model_cash             v1       Trench 2             CASH
22    beta_demo_model_cash             v1       Trench 3             CASH
23   beta_stack_model_cash             v1            ALL             CASH
24   beta_stack_model_cash             v1       Trench 1             CASH
25   beta_stack_model_cash             v1       Trench 2             CASH
26   beta_stack_model_cash             v1       Trench 3             CASH
27   beta_stack_model_cash           v1.1            ALL             CASH
28   beta_stack_model_cash           v1.1       Trench 1             CASH
29   beta_stack_model_cash           v1.1       Trench 2             CASH
30          cic_model_cash             v1            ALL             CASH
31          cic_model_cash             v1       Trench 1             CASH
32          cic_model_cash             v1       Trench 2             CASH
33          cic_model_cash             v1       Trench 3             CASH
34   gamma_demo_model_cash             v1            ALL             CASH
35   gamma_demo_model_cash             v1       Trench 1             CASH
36  gamma_stack_model_cash             v1            ALL             CASH
37  gamma_stack_model_cash             v1       Trench 1             CASH
38   alpha_stack_model_sil             v1            ALL              SIL
39   alpha_stack_model_sil             v2            ALL              SIL
40   alpha_stack_model_sil             v2       Trench 1              SIL
41   alpha_stack_model_sil             v2       Trench 2              SIL
42   alpha_stack_model_sil             v2       Trench 3              SIL
43    apps_score_model_sil             v1            ALL              SIL
44    apps_score_model_sil             v2            ALL              SIL
45    apps_score_model_sil             v2       Trench 1              SIL
46    apps_score_model_sil             v2       Trench 2              SIL
47    apps_score_model_sil             v2       Trench 3              SIL
48     beta_demo_model_sil             v1            ALL              SIL
49     beta_demo_model_sil             v2            ALL              SIL
50     beta_demo_model_sil             v2       Trench 1              SIL
51     beta_demo_model_sil             v2       Trench 2              SIL
52     beta_demo_model_sil             v2       Trench 3              SIL
53    beta_stack_model_sil             v1            ALL              SIL
54    beta_stack_model_sil             v2            ALL              SIL
55    beta_stack_model_sil             v2       Trench 1              SIL
56    beta_stack_model_sil             v2       Trench 2              SIL
57    beta_stack_model_sil             v2       Trench 3              SIL
58           cic_model_sil             v1            ALL              SIL
59           cic_model_sil             v2            ALL              SIL
60           cic_model_sil             v2       Trench 1              SIL
61           cic_model_sil             v2       Trench 2              SIL
62           cic_model_sil             v2       Trench 3              SIL

In [8]:
# configdf.to_csv('configdf.csv', index = False)

## SIL

### Queries

### cic_model_sil

### Test

In [9]:
## This is for the test period of Alpha - CIC sil model - reading the data from ml_model_run_details

sq = """
WITH cleaned AS (
  SELECT
    customerId,digitalLoanAccountId,prediction,start_time,end_time,
        case when modelDisplayName = 'Alpha - CIC-SIL-Model' then 'cic_model_sil' else modelDisplayName end as modelDisplayName    
    ,modelVersionId,
    case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
    else trenchCategory end trenchCategory,
    REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeature
  FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
  WHERE modelDisplayName in ('Alpha - CIC-SIL-Model', 'cic_model_sil')
  ),
base as
(SELECT distinct

--Alpha_cic_sil_score
  r.customerId,r.digitalLoanAccountId,prediction score
    ,start_time,end_time,modelDisplayName,modelVersionId,
   loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
        when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
        when lower(loanmaster.deviceType) like '%andro%' then 'android'
        else 'ios' end osType,
 'cic_model_sil' Model_Name,
 'SIL' as product,
  trenchCategory,
  r.calcFeature calcFeatures,
  'Test' Data_selection,
  coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time)) as Application_month,
FROM cleaned r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
qualify row_number() over (partition by r.customerId,r.digitalLoanAccountId, modelVersionId 
order by coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) desc) = 1
)
select * from base
;
"""
dfd = client.query(sq).to_dataframe()
print(f"The shape of the dataframe is: {dfd.shape}")
dfd.head()

## this data is not expanded. We will have to expand and get the features from the calcFeatures column

The shape of the dataframe is: (159799, 19)

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,calcFeatures,Data_selection,appln_submit_datetime,disbursementDateTime,Application_month
0,1379215,008724bf-1dc4-4d52-ab9a-a995b45e5d6e,0.18212203429492094,2025-10-25 09:38:39.225416,2025-10-25 09:38:39.231850,cic_model_sil,v1,SIL-Instore,M,Appliance,android,cic_model_sil,SIL,ALL,"{""run_date"":1761350400000,""cic_Personal_Loans_...",Test,2025-10-25 17:38:27,2025-10-27 10:01:24,2025-10
1,2031530,7ecbdd6b-800b-457c-96ac-9cbfaeaca365,0.13892255350798124,2025-12-04 12:09:56.705612,2025-12-04 12:09:56.712194,cic_model_sil,v1,SIL Competitor,F,Mall,ios,cic_model_sil,SIL,ALL,"{""run_date"":1764806400000,""cic_Personal_Loans_...",Test,2025-12-04 20:09:47,2025-12-04 20:14:03,2025-12
2,2256898,4b74514e-bfb6-4f54-ad90-7841826a8e1e,0.14185155811904787,2025-08-24 08:27:38.229047,2025-08-24 08:27:38.235628,cic_model_sil,v1,SIL Competitor,M,Mall,android,cic_model_sil,SIL,ALL,"{""run_date"":1755993600000,""cic_Personal_Loans_...",Test,2025-08-24 16:27:27,NaT,2025-08
3,2387610,5ec1d6f3-0ece-430c-923c-93a7de12fd34,0.18631429260071528,2025-09-10 06:40:29.779058,2025-09-10 06:40:29.785474,cic_model_sil,v1,SIL-Instore,F,Appliance,android,cic_model_sil,SIL,ALL,"{""run_date"":1757462400000,""cic_Personal_Loans_...",Test,2025-09-10 14:40:18,NaT,2025-09
4,2432136,a8f11603-d169-428c-963a-52a8624f7b87,0.10225649210326619,2025-11-30 06:04:08.379012,2025-11-30 06:04:08.385590,cic_model_sil,v1,SIL Competitor,M,Mall,ios,cic_model_sil,SIL,ALL,"{""run_date"":1764460800000,""cic_Personal_Loans_...",Test,2025-11-30 14:03:57,2025-11-30 14:10:55,2025-11

In [10]:
df1 = dfd.copy()

### Train

In [11]:
sq = """WITH cleaned AS (
  SELECT
    customerId,digitalLoanAccountId,prediction,start_time,end_time,
    
    case when modelDisplayName = 'Alpha - CIC-SIL-Model' then 'cic_model_sil' else modelDisplayName end as modelDisplayName
    
    ,modelVersionId,
        case when trenchCategory is null then 'ALL' 
         when trenchCategory = '' then 'ALL'
    else trenchCategory end trenchCategory,
    REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeature
  FROM prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
  WHERE modelDisplayName in ('Alpha - CIC-SIL-Model', 'cic_model_sil')
  ),
base as 
(SELECT distinct
  r.customerId,r.digitalLoanAccountId,prediction score
    ,start_time,end_time,modelDisplayName,modelVersionId,
   loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
        when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
        when lower(loanmaster.deviceType) like '%andro%' then 'android'
        else 'ios' end osType,
 'Alpha - CIC-SIL-Model' Model_Name,
 'SIL' as product,
  trenchCategory,
  r.calcFeature calcFeatures,
  'Train' Data_selection,
  coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  cast(r.start_time as datetime)) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m', IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime)) as Application_month,
FROM cleaned r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
qualify row_number() over (partition by r.customerId,r.digitalLoanAccountId, modelVersionId 
order by   coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  cast(r.start_time as datetime)) desc) = 1
)
select * from base
;
"""

dfd = client.query(sq).to_dataframe()
print(f"The shape of the dataframe is: {dfd.shape}")
dfd.head()

The shape of the dataframe is: (430892, 19)

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,calcFeatures,Data_selection,appln_submit_datetime,disbursementDateTime,Application_month
0,1714093,4bd77f7d-4258-4dd7-8bc3-3ff40283d41d,0.226442,2025-12-23T22:16:23.055806,2025-12-23T22:16:23.055806,cic_model_sil,v1,SIL-Instore,F,Appliance,android,Alpha - CIC-SIL-Model,SIL,ALL,"{""cic_days_since_last_inquiry"": 0.0, ""cic_vel_...",Train,2024-12-30 15:36:23,2024-12-30 15:42:57,2024-12
1,1906390,63452ed2-656f-49da-8778-a19d1df8807b,0.099444,2025-12-23T22:16:19.330097,2025-12-23T22:16:19.330097,cic_model_sil,v1,SIL-Instore,M,Appliance,android,Alpha - CIC-SIL-Model,SIL,ALL,"{""cic_days_since_last_inquiry"": 306.0, ""cic_ve...",Train,2023-12-21 17:50:08,2023-12-21 18:37:49,2023-12
2,2106427,b5fc07e2-a27c-41aa-b8b3-4e9cc3fab1e6,0.123620,2025-12-23T22:16:21.517024,2025-12-23T22:16:21.517024,cic_model_sil,v1,SIL-Instore,M,Appliance,android,Alpha - CIC-SIL-Model,SIL,ALL,"{""cic_days_since_last_inquiry"": 792.0, ""cic_ze...",Train,2023-06-24 17:46:47,NaT,2023-06
3,2114094,835376f9-fcba-451d-bf06-409fde348478,0.074639,2025-12-23T22:16:31.340745,2025-12-23T22:16:31.340745,cic_model_sil,v1,SIL Repeat,M,Mall,android,Alpha - CIC-SIL-Model,SIL,ALL,"{""cic_days_since_last_inquiry"": 555.0, ""cic_cn...",Train,2025-01-05 18:30:28,NaT,2025-01
4,2201012,b6078b88-c0c5-47f2-aed7-147f0045ce7e,0.125669,2025-12-23T22:16:22.059831,2025-12-23T22:16:22.059831,cic_model_sil,v1,SIL-Instore,F,Appliance,android,Alpha - CIC-SIL-Model,SIL,ALL,"{""cic_days_since_last_inquiry"": 1279.0, ""cic_z...",Train,2023-08-27 17:12:36,NaT,2023-08

In [12]:
df2 = dfd.copy()

In [13]:
df2[['Application_month']][(df2['modelVersionId'] =='v1')].max()

Application_month    2025-01
dtype: object

In [14]:
df2[df2['Application_month'] == '2025-11']

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,calcFeatures,Data_selection,appln_submit_datetime,disbursementDateTime,Application_month
152355,3206286,6b2d3c9c-efd4-4d62-a4d3-db28826ffd7a,0.394028,2025-12-23T22:28:52.295109,2025-12-23T22:28:52.295109,cic_model_sil,v2,SIL-Instore,F,Appliance,android,Alpha - CIC-SIL-Model,SIL,Trench 1,"{""ScoreRange"": ""Missing"", ""ln_loan_level_user_...",Train,2025-11-15 10:23:43,2025-01-21 19:13:10,2025-11

In [15]:
dd.query("""select Application_month, count(distinct digitalLoanAccountId)cnt from df2 
         where modelVersionId ='v1'
         group by 1 order by 1 desc;""").to_df()

   Application_month    cnt
0            2025-01  16318
1            2024-12  34696
2            2024-11  17931
3            2024-10  16817
4            2024-09  17502
5            2024-08  17808
6            2024-07  13346
7            2024-06  13472
8            2024-05   8033
9            2024-04   5851
10           2024-03   3083
11           2024-02   2382
12           2024-01   2506
13           2023-12   4458
14           2023-11   2505
15           2023-10   1836
16           2023-09   1886
17           2023-08   1148
18           2023-07    521
19           2023-06    507
20           2023-05    453
21           2023-04    446
22           2023-03    364
23           2023-02    323
24           2023-01    292

In [16]:
df_concat = pd.concat([df1, df2], ignore_index=True)
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")

The shape of the concatenated dataframe is: (590691, 19)

In [17]:
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")
df_combined = dropping_duplicates(df_concat)
print(f"The shape of the dataframe after dropping duplicates is: {df_combined.shape}")

The shape of the concatenated dataframe is: (590691, 19)
The shape of the dataframe after dropping duplicates is: (590691, 19)

In [18]:
df_combined['score'] = pd.to_numeric(df_combined['score'], errors='coerce')

In [19]:
df_combined['Application_month'][df_combined['Data_selection'] == 'Train'].max()

'2025-11'

### PSI calculation

In [20]:
# USAGE EXAMPLES:
# ===============

# Example 1: Calculate overall PSI (no segmentation)
# score_output_df = calculate_psi_with_segments(
#     df=df_combined,
#     score_column='score',
#     date_column='Application_month',
#     data_selection_column='Data_selection',
#     segment_columns=None
# )

# Example 2: Calculate PSI with single segmentation (modelVersionId)
# score_output_df = calculate_psi_with_segments(
#     df=df_combined,
#     score_column='score',
#     date_column='Application_month',
#     data_selection_column='Data_selection',
#     segment_columns=['modelVersionId']
# )

# Example 3: Calculate PSI with multiple segmentations (all combinations)
# score_output_df = calculate_psi_with_segments(
#     df=df_combined,
#     score_column='score',
#     date_column='Application_month',
#     data_selection_column='Data_selection',
#     segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
# )

# Example 4: With a different score column name
# score_output_df = calculate_psi_with_segments(
#     df=df_combined,
#     score_column='risk_score',  # Different score column
#     date_column='Application_month',
#     data_selection_column='Data_selection',
#     segment_columns=['modelVersionId', 'trenchCategory']
# )

# Example 1: Waterfall segmentation with all levels
score_output_df = calculate_psi_with_segments(
    df=df_combined,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
)

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

print(f"Output shape: {score_output_df.shape}")
print(f"\nOutput columns: {score_output_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(score_output_df.head(20))
print(f"\nData types:")
print(score_output_df.dtypes)

Output shape: (530, 10)

Output columns: ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count', 'modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']

First few rows:
      Month scorename DateCategory  psivalues  account_count modelVersionId  \
0   2025-11     score     Training   0.000000         246408             v2
1   2025-11     score      Monthly   0.082671            944             v2
2   2025-12     score      Monthly   0.064708          21069             v2
3   2026-01     score      Monthly   0.058383          17419             v2
4   2026-02     score      Monthly   0.057500          16642             v2
5   2026-03     score      Monthly   0.086705            294             v2
6   2025-11     score     Training   0.000000         184484             v1
7   2025-03     score      Monthly   0.134249            180             v1
8   2025-04     score      Monthly   0.110920            541             v1
9   2025-05     score      Monthly   0.108170            858             v1
10  2025-06     score      Monthly   0.120669           9934             v1
11  2025-07     score      Monthly   0.127452          14043             v1
12  2025-08     score      Monthly   0.134328          15085             v1
13  2025-09     score      Monthly   0.121338          13880             v1
14  2025-10     score      Monthly   0.129319          16424             v1
15  2025-11     score      Monthly   0.129063          19329             v1
16  2025-12     score      Monthly   0.159074          13157             v1
17  2025-11     score     Training   0.000000         224718             v2
18  2025-11     score      Monthly   0.136712            835             v2
19  2025-12     score      Monthly   0.089714          18748             v2

   trenchCategory new_loan_type loan_product_type osType
0              NA            NA                NA     NA
1              NA            NA                NA     NA
2              NA            NA                NA     NA
3              NA            NA                NA     NA
4              NA            NA                NA     NA
5              NA            NA                NA     NA
6              NA            NA                NA     NA
7              NA            NA                NA     NA
8              NA            NA                NA     NA
9              NA            NA                NA     NA
10             NA            NA                NA     NA
11             NA            NA                NA     NA
12             NA            NA                NA     NA
13             NA            NA                NA     NA
14             NA            NA                NA     NA
15             NA            NA                NA     NA
16             NA            NA                NA     NA
17       Trench 1            NA                NA     NA
18       Trench 1            NA                NA     NA
19       Trench 1            NA                NA     NA

Data types:
Month                 object
scorename             object
DateCategory          object
psivalues            float64
account_count          int64
modelVersionId        object
trenchCategory        object
new_loan_type         object
loan_product_type     object
osType                object
dtype: object

In [21]:
# # Initialize calculator
# psi_calc = PSICalculator(df_combined)
# results_overall = psi_calc.calculate_psi_by_segment(score_column='score')

In [22]:
# # 2. PSI by individual segment
# results_modelversion = psi_calc.calculate_psi_by_segment(
#     score_column='score',
#     segment_columns=['modelVersionId']
# )

In [23]:
# results_modelversion

In [24]:
# results_multi = psi_calc.calculate_psi_by_segment(
#     score_column='score',
#     segment_columns=['modelVersionId', 'trenchCategory', 'loan_product_type', 'osType']
# )

In [25]:
score_output_df

score_output_df['Model_Name'] = 'cic_model_sil'
score_output_df['scorename'] = score_output_df['scorename'].replace('score', 'Alpha_cic_sil_score')
score_output_df

,Month,scorename,DateCategory,psivalues,account_count,modelVersionId,trenchCategory,new_loan_type,loan_product_type,osType,Model_Name
0,2025-11,Alpha_cic_sil_score,Training,0.000000,246408,v2,NA,NA,NA,NA,cic_model_sil
1,2025-11,Alpha_cic_sil_score,Monthly,0.082671,944,v2,NA,NA,NA,NA,cic_model_sil
2,2025-12,Alpha_cic_sil_score,Monthly,0.064708,21069,v2,NA,NA,NA,NA,cic_model_sil
3,2026-01,Alpha_cic_sil_score,Monthly,0.058383,17419,v2,NA,NA,NA,NA,cic_model_sil
4,2026-02,Alpha_cic_sil_score,Monthly,0.057500,16642,v2,NA,NA,NA,NA,cic_model_sil
...,...,...,...,...,...,...,...,...,...,...,...
525,2025-08,Alpha_cic_sil_score,Monthly,0.162986,90,v1,ALL,SIL ZERO,Appliance,ios,cic_model_sil
526,2025-09,Alpha_cic_sil_score,Monthly,0.422861,78,v1,ALL,SIL ZERO,Appliance,ios,cic_model_sil
527,2025-10,Alpha_cic_sil_score,Monthly,0.136165,69,v1,ALL,SIL ZERO,Appliance,ios,cic_model_sil
528,2025-11,Alpha_cic_sil_score,Monthly,0.255677,83,v1,ALL,SIL ZERO,Appliance,ios,cic_model_sil
529,2025-12,Alpha_cic_sil_score,Monthly,0.286299,64,v1,ALL,SIL ZERO,Appliance,ios,cic_model_sil

In [26]:
# # 4. With custom column names
# results_custom = psi_calc.calculate_psi_by_segment(
#     score_column='score',
#     segment_columns=['modelVersionId', 'new_loan_type'],
#     account_id_column='digitalLoanAccountId',
#     data_selection_column='Data_selection'
# )

In [27]:
# copy the data to psi_results
psi_results = score_output_df.copy()

# Upload to BigQuery
table_id = "prj-prod-dataplatform.dap_ds_poweruser_playground.alpha_cic_sil_model_psi_v7"
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",  # or "WRITE_APPEND"
)
job = client.load_table_from_dataframe(psi_results, table_id, job_config=job_config)
job.result()

C:\Users\Dwaipayan\AppData\Roaming\Python\Python312\site-packages\google\cloud\bigquery\_pandas_helpers.py:483: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=prj-prod-dataplatform, location=asia-southeast1, id=98e72de6-1786-444f-8bd2-5925685a2df3>

### Alpha Sil Stack Model

### Test

In [28]:
## This is for the test period of Alpha - CIC sil model - reading the data from ml_model_run_details
# Sil_Alpha_Stack_score
sq = """
WITH cleaned AS (
  SELECT
    customerId,digitalLoanAccountId,prediction,start_time,end_time,
        case when modelDisplayName = 'Alpha - StackingModel' then 'alpha_stack_model_sil' else modelDisplayName end as modelDisplayName    
    ,modelVersionId,
    case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
    else trenchCategory end trenchCategory,
    REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeature
  FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
  WHERE modelDisplayName in ('Alpha - StackingModel', 'alpha_stack_model_sil')
  ),
base as
(SELECT distinct
  r.customerId,r.digitalLoanAccountId,prediction score
    ,start_time,end_time,modelDisplayName,modelVersionId,
   loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
        when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
        when lower(loanmaster.deviceType) like '%andro%' then 'android'
        else 'ios' end osType,
 'alpha_stack_model_sil' Model_Name,
 'SIL' as product,
  trenchCategory,
  r.calcFeature calcFeatures,
  'Test' Data_selection,
  coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time)) as Application_month,
FROM cleaned r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
qualify row_number() over (partition by r.customerId,r.digitalLoanAccountId, modelVersionId 
order by coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) desc) = 1
)
select * from base
;
"""
dfd = client.query(sq).to_dataframe()
print(f"The shape of the dataframe is: {dfd.shape}")
dfd.head()

## this data is not expanded. We will have to expand and get the features from the calcFeatures column

The shape of the dataframe is: (159800, 19)

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,calcFeatures,Data_selection,appln_submit_datetime,disbursementDateTime,Application_month
0,1008813,994223fd-9099-4b2a-9238-042743276049,0.039848645601934095,2025-09-07 13:00:29.214259,2025-09-07 13:00:29.220101,alpha_stack_model_sil,v1,SIL-Instore,F,Mall,android,alpha_stack_model_sil,SIL,ALL,"{""sb_demo_score"": 0.0801198395, ""s_cic_score"":...",Test,2025-09-07 21:00:20,NaT,2025-09
1,1182494,0cda7000-2b47-4b6a-92bd-9b75e8f2b78d,0.7080796727448715,2025-12-25 05:31:36.033251,2025-12-25 05:31:36.174904,alpha_stack_model_sil,v2,SIL Competitor,F,Appliance,android,alpha_stack_model_sil,SIL,Trench 2,"{""sb_demo_score"": 0.5630553684, ""apps_score"": ...",Test,2025-12-25 13:31:23,NaT,2025-12
2,1433761,a0c27a9d-ab2f-4820-9a47-aa9f502ca872,0.30138063308709817,2026-01-10 03:49:54.029139,2026-01-10 03:49:54.299480,alpha_stack_model_sil,v2,SIL-Instore,F,Appliance,android,alpha_stack_model_sil,SIL,Trench 2,"{""sb_demo_score"": 0.4074710426, ""apps_score"": ...",Test,2026-01-10 11:49:36,2026-01-10 11:56:13,2026-01
3,1680740,50de886a-cbad-4cd2-935f-96638f319038,0.12893522208124597,2025-12-14 10:32:16.952403,2025-12-14 10:32:16.957754,alpha_stack_model_sil,v1,SIL-Instore,F,Mall,ios,alpha_stack_model_sil,SIL,ALL,"{""sb_demo_score"": 0.0953303111, ""s_cic_score"":...",Test,2025-12-14 18:31:57,2025-12-14 18:37:02,2025-12
4,2217513,8d5a608b-bcf1-4f43-828d-9967ebf10f63,0.10153234211568707,2026-01-11 08:36:38.269864,2026-01-11 08:36:38.425511,alpha_stack_model_sil,v2,SIL-Instore,M,Appliance,android,alpha_stack_model_sil,SIL,Trench 3,"{""sb_demo_score"": 0.0801928612, ""apps_score"": ...",Test,2026-01-11 16:36:20,2026-01-11 17:04:06,2026-01

In [29]:
df1 = dfd.copy()

### Train

In [30]:
sq = """WITH cleaned AS (
  SELECT
    customerId,digitalLoanAccountId,prediction,start_time,end_time,
    
    case when modelDisplayName = 'Alpha - StackingModel' then 'alpha_stack_model_sil' else modelDisplayName end as modelDisplayName 
     ,modelVersionId,
        case when trenchCategory is null then 'ALL' 
         when trenchCategory = '' then 'ALL'
    else trenchCategory end trenchCategory,
    REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeature
  FROM prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
  WHERE modelDisplayName in ('Alpha - StackingModel', 'alpha_stack_model_sil')
  ),
base as 
(SELECT distinct
  r.customerId,r.digitalLoanAccountId,prediction score
    ,start_time,end_time,modelDisplayName,modelVersionId,
   loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
        when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
        when lower(loanmaster.deviceType) like '%andro%' then 'android'
        else 'ios' end osType,
 'alpha_stack_model_sil' Model_Name,
 'SIL' as product,
  trenchCategory,
  r.calcFeature calcFeatures,
  'Train' Data_selection,
  coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  cast(r.start_time as datetime)) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  cast(r.start_time as datetime))) as Application_month,
FROM cleaned r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
qualify row_number() over (partition by r.customerId,r.digitalLoanAccountId, modelVersionId 
order by   coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  cast(r.start_time as datetime)) desc) = 1
)
select * from base
;
"""

dfd = client.query(sq).to_dataframe()
print(f"The shape of the dataframe is: {dfd.shape}")
dfd.head()

The shape of the dataframe is: (439057, 19)

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,calcFeatures,Data_selection,appln_submit_datetime,disbursementDateTime,Application_month
0,2003382,bba611cc-8884-4793-aa36-c59087e34c85,0.241239,2025-12-23T22:16:52.577038,2025-12-23T22:16:52.577038,alpha_stack_model_sil,v1,SIL-Instore,F,Appliance,android,alpha_stack_model_sil,SIL,ALL,"{""sb_demo_score"": 0.18093306335082132, ""s_cic_...",Train,2024-10-06 19:31:05,NaT,2024-10
1,2020834,0201ff96-87a3-4606-ac16-3ef0655d92c1,0.081632,2025-12-23T22:16:48.031861,2025-12-23T22:16:48.031861,alpha_stack_model_sil,v1,SIL-Instore,M,Appliance,android,alpha_stack_model_sil,SIL,ALL,"{""sb_demo_score"": 0.09039479108953694, ""s_cic_...",Train,2024-03-10 13:18:24,2024-03-10 13:27:52,2024-03
2,2185970,ab9fbe15-42d2-4eb6-a2b8-5e95350c453e,0.023075,2025-12-23T22:16:49.652629,2025-12-23T22:16:49.652629,alpha_stack_model_sil,v1,SIL-Instore,M,Appliance,android,alpha_stack_model_sil,SIL,ALL,"{""sb_demo_score"": 0.06996197514807835, ""s_cic_...",Train,2023-08-12 18:41:56,2023-08-12 18:56:38,2023-08
3,2192426,938faeb0-e10b-4f32-9273-1bff5a768e9e,0.038476,2025-12-23T22:16:47.885940,2025-12-23T22:16:47.885940,alpha_stack_model_sil,v1,SIL-Instore,F,Appliance,android,alpha_stack_model_sil,SIL,ALL,"{""sb_demo_score"": 0.10227063946069813, ""s_cic_...",Train,2025-01-13 18:37:33,NaT,2025-01
4,2224109,e5c66bf1-d9fe-4451-b806-0ae9999ae67f,0.094867,2025-12-23T22:16:59.744473,2025-12-23T22:16:59.744473,alpha_stack_model_sil,v1,SIL-Instore,M,Appliance,ios,alpha_stack_model_sil,SIL,ALL,"{""sb_demo_score"": 0.19099172413302518, ""s_cic_...",Train,2024-04-14 11:37:59,NaT,2024-04

In [31]:
df2 = dfd.copy()

In [32]:
df_concat = pd.concat([df1, df2], ignore_index=True)
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")

The shape of the concatenated dataframe is: (598857, 19)

In [33]:
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")
df_combined = dropping_duplicates(df_concat)
print(f"The shape of the dataframe after dropping duplicates is: {df_combined.shape}")

The shape of the concatenated dataframe is: (598857, 19)
The shape of the dataframe after dropping duplicates is: (598857, 19)

In [34]:
df_combined['score'] = pd.to_numeric(df_combined['score'], errors='coerce')

### PSI calculation

In [35]:
score_output_df = calculate_psi_with_segments(
    df=df_combined,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
)

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

print(f"Output shape: {score_output_df.shape}")
print(f"\nOutput columns: {score_output_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(score_output_df.head(20))
print(f"\nData types:")
print(score_output_df.dtypes)

Output shape: (530, 10)

Output columns: ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count', 'modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']

First few rows:
      Month scorename DateCategory  psivalues  account_count modelVersionId  \
0   2025-11     score     Training   0.000000         254573             v2
1   2025-11     score      Monthly   0.565769            944             v2
2   2025-12     score      Monthly   0.043884          21069             v2
3   2026-01     score      Monthly   0.040086          17419             v2
4   2026-02     score      Monthly   0.031377          16642             v2
5   2026-03     score      Monthly   0.104491            295             v2
6   2025-11     score     Training   0.000000         184484             v1
7   2025-03     score      Monthly  12.685199            180             v1
8   2025-04     score      Monthly   0.176158            541             v1
9   2025-05     score      Monthly   0.041444            858             v1
10  2025-06     score      Monthly   0.100930           9934             v1
11  2025-07     score      Monthly   0.107424          14043             v1
12  2025-08     score      Monthly   0.105073          15085             v1
13  2025-09     score      Monthly   0.084556          13880             v1
14  2025-10     score      Monthly   0.101377          16424             v1
15  2025-11     score      Monthly   0.078706          19329             v1
16  2025-12     score      Monthly   0.080831          13157             v1
17  2025-11     score     Training   0.000000         232107             v2
18  2025-11     score      Monthly   0.617918            835             v2
19  2025-12     score      Monthly   0.054918          18748             v2

   trenchCategory new_loan_type loan_product_type osType
0              NA            NA                NA     NA
1              NA            NA                NA     NA
2              NA            NA                NA     NA
3              NA            NA                NA     NA
4              NA            NA                NA     NA
5              NA            NA                NA     NA
6              NA            NA                NA     NA
7              NA            NA                NA     NA
8              NA            NA                NA     NA
9              NA            NA                NA     NA
10             NA            NA                NA     NA
11             NA            NA                NA     NA
12             NA            NA                NA     NA
13             NA            NA                NA     NA
14             NA            NA                NA     NA
15             NA            NA                NA     NA
16             NA            NA                NA     NA
17       Trench 1            NA                NA     NA
18       Trench 1            NA                NA     NA
19       Trench 1            NA                NA     NA

Data types:
Month                 object
scorename             object
DateCategory          object
psivalues            float64
account_count          int64
modelVersionId        object
trenchCategory        object
new_loan_type         object
loan_product_type     object
osType                object
dtype: object

In [36]:
score_output_df

score_output_df['Model_Name'] = 'alpha_stack_model_sil'
score_output_df['scorename'] = score_output_df['scorename'].replace('score', 'Sil_Alpha_Stack_score')
score_output_df

,Month,scorename,DateCategory,psivalues,account_count,modelVersionId,trenchCategory,new_loan_type,loan_product_type,osType,Model_Name
0,2025-11,Sil_Alpha_Stack_score,Training,0.000000,254573,v2,NA,NA,NA,NA,alpha_stack_model_sil
1,2025-11,Sil_Alpha_Stack_score,Monthly,0.565769,944,v2,NA,NA,NA,NA,alpha_stack_model_sil
2,2025-12,Sil_Alpha_Stack_score,Monthly,0.043884,21069,v2,NA,NA,NA,NA,alpha_stack_model_sil
3,2026-01,Sil_Alpha_Stack_score,Monthly,0.040086,17419,v2,NA,NA,NA,NA,alpha_stack_model_sil
4,2026-02,Sil_Alpha_Stack_score,Monthly,0.031377,16642,v2,NA,NA,NA,NA,alpha_stack_model_sil
...,...,...,...,...,...,...,...,...,...,...,...
525,2025-08,Sil_Alpha_Stack_score,Monthly,0.130898,90,v1,ALL,SIL ZERO,Appliance,ios,alpha_stack_model_sil
526,2025-09,Sil_Alpha_Stack_score,Monthly,0.212421,78,v1,ALL,SIL ZERO,Appliance,ios,alpha_stack_model_sil
527,2025-10,Sil_Alpha_Stack_score,Monthly,0.274605,69,v1,ALL,SIL ZERO,Appliance,ios,alpha_stack_model_sil
528,2025-11,Sil_Alpha_Stack_score,Monthly,0.326472,83,v1,ALL,SIL ZERO,Appliance,ios,alpha_stack_model_sil
529,2025-12,Sil_Alpha_Stack_score,Monthly,0.376181,64,v1,ALL,SIL ZERO,Appliance,ios,alpha_stack_model_sil

In [37]:
psi_results = score_output_df.copy()
table_id = "prj-prod-dataplatform.dap_ds_poweruser_playground.alpha_sil_stack_model_psi_v7"
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",  # or "WRITE_APPEND"
)
job = client.load_table_from_dataframe(psi_results, table_id, job_config=job_config)
job.result()

C:\Users\Dwaipayan\AppData\Roaming\Python\Python312\site-packages\google\cloud\bigquery\_pandas_helpers.py:483: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=prj-prod-dataplatform, location=asia-southeast1, id=7efeb9db-d873-48d9-baf0-c3ae0b7e16e3>

### Beta Sil App Score

### Test

In [38]:
sq = """
WITH cleaned AS (
  SELECT
    customerId,digitalLoanAccountId,prediction,start_time,end_time,
    case when modelDisplayName = 'Beta - AppsScoreModel' then 'apps_score_model_sil' else modelDisplayName end as modelDisplayName ,   
    modelVersionId,
    case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
    REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeature,
    REPLACE(REPLACE(prediction, "'", '"'), "None", "null") AS prediction_clean
  FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
  WHERE modelDisplayName in ('Beta - AppsScoreModel', 'apps_score_model_sil')
    
  ),
base as 
(SELECT
  r.customerId,r.digitalLoanAccountId,prediction,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'apps_score_model_sil' Model_Name,
 'SIL' as product,
  trenchCategory,
  'Test' Data_selection,
  -- sil_beta_app_score
  safe_cast(JSON_VALUE(prediction_clean, "$.combined_score") AS float64) as score,
 calcFeature calcFeatures,
    coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) AS appln_submit_datetime,
    loanmaster.disbursementDateTime,
    format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time)) as Application_month,
 FROM cleaned r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid,  modelVersionId  order by coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) desc) = 1
  )
select * from base 
;
"""
dfd = client.query(sq).to_dataframe()
dfd.head()

,customerId,digitalLoanAccountId,prediction,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,Data_selection,score,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1234567,dummy-ceb2-4ec4-8409-2866af38d003,0.5790455351355035,2025-11-17 11:28:39.577968,2025-11-17 11:28:40.829485,apps_score_model_sil,v2,None,None,not applicable,ios,apps_score_model_sil,SIL,Trench 1,Test,NaN,"{""appScoreModel"": {""app_cnt_art_and_design_eve...",2025-11-17 11:28:39.577968,NaT,2025-11
1,1268860,7b84898d-1c0c-44d1-9246-d804a5421c73,"{'cb_score': 0.4922963549113004, 'dl_score': 0...",2025-11-13 06:16:34.460703,2025-11-13 06:16:35.319049,apps_score_model_sil,v1,SIL-Instore,F,Appliance,android,apps_score_model_sil,SIL,ALL,Test,0.575926,"{""app_cnt_rated_for_3plus_ever"":15,""app_cnt_ed...",2025-11-13 14:16:31.000000,NaT,2025-11
2,1529313,c1554aea-8b62-412d-b6bd-3b02eeeeedae,"{'cb_score': 0.352303464266693, 'dl_score': 0....",2025-09-28 10:39:34.093483,2025-09-28 10:39:34.552354,apps_score_model_sil,v1,SIL-Instore,M,Appliance,android,apps_score_model_sil,SIL,ALL,Test,0.450374,"{""app_cnt_rated_for_3plus_ever"":17,""app_cnt_ed...",2025-09-28 18:39:30.000000,NaT,2025-09
3,1644071,02d07e79-8be6-4bf9-bdf0-c617b1bda9b3,"{'cb_score': 0.49410636011694986, 'dl_score': ...",2025-11-02 05:45:29.623470,2025-11-02 05:45:30.089816,apps_score_model_sil,v1,SIL Competitor,F,Appliance,android,apps_score_model_sil,SIL,ALL,Test,0.518080,"{""app_cnt_rated_for_3plus_ever"":28,""app_cnt_ed...",2025-11-02 13:45:27.000000,NaT,2025-11
4,1720483,dc5085e6-3994-41c6-ab6e-863c67799361,0.1810084844992362,2026-01-07 11:07:35.741069,2026-01-07 11:07:36.397015,apps_score_model_sil,v2,SIL-Instore,F,Appliance,android,apps_score_model_sil,SIL,Trench 2,Test,NaN,"{""appScoreModel"": {""app_cnt_art_and_design_eve...",2026-01-07 19:07:30.000000,2026-01-07 19:22:49,2026-01

In [39]:
df1 = dfd.copy()

### Train

In [40]:
sq = """ 
WITH cleaned AS (
  SELECT
    customerId,digitalLoanAccountId,prediction,start_time,end_time,
    case when modelDisplayName = 'Beta - AppsScoreModel' then 'apps_score_model_sil' else modelDisplayName end as modelDisplayName 
     ,modelVersionId,
        case when trenchCategory is null then 'ALL' 
         when trenchCategory = '' then 'ALL'
    else trenchCategory end trenchCategory,
    REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeature,
    REPLACE(REPLACE(cast(prediction as string), "'", '"'), "None", "null") AS prediction_clean
  FROM prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
  WHERE modelDisplayName in ('Beta - AppsScoreModel', 'apps_score_model_sil')
      ),
base as 
(SELECT
  r.customerId,r.digitalLoanAccountId,prediction,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'apps_score_model_sil' Model_Name,
 'SIL' as product,
  trenchCategory,
  'Train' Data_selection,
  coalesce(prediction, safe_cast(JSON_VALUE(prediction_clean, "$.combined_score") AS float64)) as score,
 calcFeature calcFeatures,
    IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime) AS appln_submit_datetime,
    loanmaster.disbursementDateTime,
    format_date('%Y-%m', IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime)) as Application_month,
 FROM cleaned r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
 qualify row_number() over (partition by r.customerId,r.digitalLoanAccountId, modelVersionId 
order by   coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  cast(r.start_time as datetime)) desc) = 1
)
select * from base 
;
"""

dfd = client.query(sq).to_dataframe()
dfd.head()

,customerId,digitalLoanAccountId,prediction,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,Data_selection,score,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1010308,8a870f3e-d3cc-40eb-8c1a-8a9c794a6659,0.566302,2025-12-23T22:17:24.382665,2025-12-23T22:17:24.382665,apps_score_model_sil,v1,SIL-Instore,F,Appliance,android,apps_score_model_sil,SIL,ALL,Train,0.566302,"{""app_cnt_rated_for_3plus_ever"": 15.0, ""app_cn...",2024-02-07 20:11:48,NaT,2024-02
1,1137648,a0420d6d-1a04-49a8-9119-88a478e13041,0.154770,2025-12-23T22:32:15.692569,2025-12-23T22:32:15.692569,apps_score_model_sil,v2,SIL Repeat,F,Appliance,android,apps_score_model_sil,SIL,Trench 2,Train,0.154770,"{""app_cnt_payday_ever"": 2, ""app_cnt_finance_ev...",2024-12-20 18:08:52,2024-12-20 18:15:49,2024-12
2,1182494,d776a230-aeee-4e74-9cff-2d0ef7f7632b,0.378278,2025-12-23T22:32:14.944671,2025-12-23T22:32:14.944671,apps_score_model_sil,v2,SIL-Instore,F,Appliance,android,apps_score_model_sil,SIL,Trench 2,Train,0.378278,"{""app_cnt_payday_ever"": 0, ""app_cnt_finance_ev...",2024-12-23 17:14:02,NaT,2024-12
3,1216059,2fd82324-0de9-4a46-b3c9-9edad38986e1,0.340942,2025-12-23T22:32:22.503547,2025-12-23T22:32:22.503547,apps_score_model_sil,v2,SIL Repeat,F,Mall,android,apps_score_model_sil,SIL,Trench 3,Train,0.340942,"{""app_cnt_productivity_ever"": 13.0, ""app_cnt_r...",2025-09-29 13:46:14,2025-09-29 14:01:18,2025-09
4,1257421,541128d2-4295-4d2f-9a1e-adc353da1eaa,0.243012,2025-12-23T22:32:15.970362,2025-12-23T22:32:15.970362,apps_score_model_sil,v2,SIL Competitor,M,Appliance,android,apps_score_model_sil,SIL,Trench 2,Train,0.243012,"{""app_cnt_payday_ever"": 3, ""app_cnt_finance_ev...",2025-05-12 16:45:18,2025-05-12 16:49:35,2025-05

In [41]:
df2 = dfd.copy()

In [42]:
df_concat = pd.concat([df1, df2], ignore_index=True)
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")

The shape of the concatenated dataframe is: (660279, 20)

In [43]:
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")
df_combined = dropping_duplicates(df_concat)
print(f"The shape of the dataframe after dropping duplicates is: {df_combined.shape}")

The shape of the concatenated dataframe is: (660279, 20)
The shape of the dataframe after dropping duplicates is: (660279, 20)

In [44]:
df_combined['score'] = pd.to_numeric(df_combined['score'], errors='coerce')

In [45]:
dd.query("""select modelVersionId, Data_selection, count(distinct digitalLoanAccountId) cnt from df_combined group by 1,2;""").to_df()

  modelVersionId Data_selection     cnt
0             v2           Test   74154
1             v2          Train  329229
2             v1           Test  140863
3             v1          Train  116033

### PSI calculation

In [46]:
score_output_df = calculate_psi_with_segments(
    df=df_combined,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
)

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

print(f"Output shape: {score_output_df.shape}")
print(f"\nOutput columns: {score_output_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(score_output_df.head(20))
print(f"\nData types:")
print(score_output_df.dtypes)

Output shape: (55, 10)

Output columns: ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count', 'modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']

First few rows:
      Month scorename DateCategory  psivalues  account_count modelVersionId  \
0   2025-11     score     Training   0.000000         116033             v1
1   2025-03     score      Monthly   0.075090            373             v1
2   2025-04     score      Monthly   0.079331            914             v1
3   2025-05     score      Monthly   0.061396           1389             v1
4   2025-06     score      Monthly   0.039468          14507             v1
5   2025-07     score      Monthly   0.041627          20089             v1
6   2025-08     score      Monthly   0.033829          20563             v1
7   2025-09     score      Monthly   0.044746          19126             v1
8   2025-10     score      Monthly   0.051219          22029             v1
9   2025-11     score      Monthly   0.055074          25032             v1
10  2025-12     score      Monthly   0.060206          16841             v1
11  2025-11     score     Training   0.000000         116033             v1
12  2025-03     score      Monthly   0.075090            373             v1
13  2025-04     score      Monthly   0.079331            914             v1
14  2025-05     score      Monthly   0.061396           1389             v1
15  2025-06     score      Monthly   0.039468          14507             v1
16  2025-07     score      Monthly   0.041627          20089             v1
17  2025-08     score      Monthly   0.033829          20563             v1
18  2025-09     score      Monthly   0.044746          19126             v1
19  2025-10     score      Monthly   0.051219          22029             v1

   trenchCategory new_loan_type loan_product_type osType
0              NA            NA                NA     NA
1              NA            NA                NA     NA
2              NA            NA                NA     NA
3              NA            NA                NA     NA
4              NA            NA                NA     NA
5              NA            NA                NA     NA
6              NA            NA                NA     NA
7              NA            NA                NA     NA
8              NA            NA                NA     NA
9              NA            NA                NA     NA
10             NA            NA                NA     NA
11            ALL            NA                NA     NA
12            ALL            NA                NA     NA
13            ALL            NA                NA     NA
14            ALL            NA                NA     NA
15            ALL            NA                NA     NA
16            ALL            NA                NA     NA
17            ALL            NA                NA     NA
18            ALL            NA                NA     NA
19            ALL            NA                NA     NA

Data types:
Month                 object
scorename             object
DateCategory          object
psivalues            float64
account_count          int64
modelVersionId        object
trenchCategory        object
new_loan_type         object
loan_product_type     object
osType                object
dtype: object

In [47]:
score_output_df

score_output_df['Model_Name'] = 'apps_score_model_sil'
score_output_df['scorename'] = score_output_df['scorename'].replace('score', 'sil_beta_app_score')
score_output_df

,Month,scorename,DateCategory,psivalues,account_count,modelVersionId,trenchCategory,new_loan_type,loan_product_type,osType,Model_Name
0,2025-11,sil_beta_app_score,Training,0.000000,116033,v1,NA,NA,NA,NA,apps_score_model_sil
1,2025-03,sil_beta_app_score,Monthly,0.075090,373,v1,NA,NA,NA,NA,apps_score_model_sil
2,2025-04,sil_beta_app_score,Monthly,0.079331,914,v1,NA,NA,NA,NA,apps_score_model_sil
3,2025-05,sil_beta_app_score,Monthly,0.061396,1389,v1,NA,NA,NA,NA,apps_score_model_sil
4,2025-06,sil_beta_app_score,Monthly,0.039468,14507,v1,NA,NA,NA,NA,apps_score_model_sil
5,2025-07,sil_beta_app_score,Monthly,0.041627,20089,v1,NA,NA,NA,NA,apps_score_model_sil
6,2025-08,sil_beta_app_score,Monthly,0.033829,20563,v1,NA,NA,NA,NA,apps_score_model_sil
7,2025-09,sil_beta_app_score,Monthly,0.044746,19126,v1,NA,NA,NA,NA,apps_score_model_sil
8,2025-10,sil_beta_app_score,Monthly,0.051219,22029,v1,NA,NA,NA,NA,apps_score_model_sil
9,2025-11,sil_beta_app_score,Monthly,0.055074,25032,v1,NA,NA,NA,NA,apps_score_model_sil
10,2025-12,sil_beta_app_score,Monthly,0.060206,16841,v1,NA,NA,NA,NA,apps_score_model_sil
11,2025-11,sil_beta_app_score,Training,0.000000,116033,v1,ALL,NA,NA,NA,apps_score_model_sil
12,2025-03,sil_beta_app_score,Monthly,0.075090,373,v1,ALL,NA,NA,NA,apps_score_model_sil
13,2025-04,sil_beta_app_score,Monthly,0.079331,914,v1,ALL,NA,NA,NA,apps_score_model_sil
14,2025-05,sil_beta_app_score,Monthly,0.061396,1389,v1,ALL,NA,NA,NA,apps_score_model_sil
15,2025-06,sil_beta_app_score,Monthly,0.039468,14507,v1,ALL,NA,NA,NA,apps_score_model_sil
16,2025-07,sil_beta_app_score,Monthly,0.041627,20089,v1,ALL,NA,NA,NA,apps_score_model_sil
17,2025-08,sil_beta_app_score,Monthly,0.033829,20563,v1,ALL,NA,NA,NA,apps_score_model_sil
18,2025-09,sil_beta_app_score,Monthly,0.044746,19126,v1,ALL,NA,NA,NA,apps_score_model_sil
19,2025-10,sil_beta_app_score,Monthly,0.051219,22029,v1,ALL,NA,NA,NA,apps_score_model_sil
20,2025-11,sil_beta_app_score,Monthly,0.055074,25032,v1,ALL,NA,NA,NA,apps_score_model_sil
21,2025-12,sil_beta_app_score,Monthly,0.060206,16841,v1,ALL,NA,NA,NA,apps_score_model_sil
22,2025-11,sil_beta_app_score,Training,0.000000,116033,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
23,2025-03,sil_beta_app_score,Monthly,0.074020,365,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
24,2025-04,sil_beta_app_score,Monthly,0.077217,822,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
25,2025-05,sil_beta_app_score,Monthly,0.064821,1305,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
26,2025-06,sil_beta_app_score,Monthly,0.052850,11038,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
27,2025-07,sil_beta_app_score,Monthly,0.065770,12793,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
28,2025-08,sil_beta_app_score,Monthly,0.055032,12873,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
29,2025-09,sil_beta_app_score,Monthly,0.063812,11979,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
30,2025-10,sil_beta_app_score,Monthly,0.069806,13723,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
31,2025-11,sil_beta_app_score,Monthly,0.078503,16386,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
32,2025-12,sil_beta_app_score,Monthly,0.075300,10541,v1,ALL,SIL-Instore,NA,NA,apps_score_model_sil
33,2025-11,sil_beta_app_score,Training,0.000000,109314,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
34,2025-03,sil_beta_app_score,Monthly,0.124453,327,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
35,2025-04,sil_beta_app_score,Monthly,0.109833,741,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
36,2025-05,sil_beta_app_score,Monthly,0.095855,1166,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
37,2025-06,sil_beta_app_score,Monthly,0.079810,9733,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
38,2025-07,sil_beta_app_score,Monthly,0.089377,11235,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
39,2025-08,sil_beta_app_score,Monthly,0.084862,11244,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
40,2025-09,sil_beta_app_score,Monthly,0.103681,10336,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
41,2025-10,sil_beta_app_score,Monthly,0.108724,11939,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
42,2025-11,sil_beta_app_score,Monthly,0.116324,14084,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
43,2025-12,sil_beta_app_score,Monthly,0.105654,9070,v1,ALL,SIL-Instore,Appliance,NA,apps_score_model_sil
44,2025-11,sil_beta_app_score,Training,0.000000,109314,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil
45,2025-03,sil_beta_app_score,Monthly,0.124453,327,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil
46,2025-04,sil_beta_app_score,Monthly,0.109833,741,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil
47,2025-05,sil_beta_app_score,Monthly,0.095855,1166,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil
48,2025-06,sil_beta_app_score,Monthly,0.079739,9730,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil
49,2025-07,sil_beta_app_score,Monthly,0.089425,11231,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil
50,2025-08,sil_beta_app_score,Monthly,0.084827,11243,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil
51,2025-09,sil_beta_app_score,Monthly,0.103681,10336,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil
52,2025-10,sil_beta_app_score,Monthly,0.108724,11939,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil
53,2025-11,sil_beta_app_score,Monthly,0.116324,14084,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil
54,2025-12,sil_beta_app_score,Monthly,0.105654,9070,v1,ALL,SIL-Instore,Appliance,android,apps_score_model_sil

In [48]:
score_output_df.modelVersionId.unique()

array(['v1'], dtype=object)

In [49]:
psi_results = score_output_df.copy()

table_id = "prj-prod-dataplatform.dap_ds_poweruser_playground.beta_sil_appscore_model_psi_v7"
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",  # or "WRITE_APPEND"
)
job = client.load_table_from_dataframe(psi_results, table_id, job_config=job_config)
job.result()

C:\Users\Dwaipayan\AppData\Roaming\Python\Python312\site-packages\google\cloud\bigquery\_pandas_helpers.py:483: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=prj-prod-dataplatform, location=asia-southeast1, id=c4eddada-6c3b-4476-976e-9dbd9287ace6>

## Beta SIL Demo Score

### Test

In [50]:
sq = """
WITH cleaned AS (
  SELECT
    customerId,digitalLoanAccountId,prediction,start_time,end_time,
    case when modelDisplayName = 'Beta - DemoScoreModel' then 'beta_demo_model_sil' else modelDisplayName end as modelDisplayName ,   
    modelVersionId,
    case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
    REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeature,
    REPLACE(REPLACE(prediction, "'", '"'), "None", "null") AS prediction_clean
  FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
  WHERE modelDisplayName in  ('Beta - DemoScoreModel', 'beta_demo_model_sil')
  ),
base as 
(SELECT
  r.customerId,r.digitalLoanAccountId,prediction,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'beta_demo_model_sil' Model_Name,
 'SIL' as product,
  trenchCategory,
  'Test' Data_selection,
  -- sil_beta_demo_score
  prediction as score,
 calcFeature calcFeatures,
    coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) AS appln_submit_datetime,
    loanmaster.disbursementDateTime,
    format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time)) as Application_month,
 FROM cleaned r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid,  modelVersionId  order by coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) desc) = 1
  )
select * from base where lower(new_loan_type) like '%sil%'
;
"""
dfd = client.query(sq).to_dataframe()
dfd.head()

,customerId,digitalLoanAccountId,prediction,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,Data_selection,score,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1019991,6057ae8f-1664-43d9-b775-e0db770620ce,0.2535121221995825,2025-12-31 03:09:59.175226,2025-12-31 03:09:59.198077,beta_demo_model_sil,v2,SIL Competitor,M,Appliance,ios,beta_demo_model_sil,SIL,Trench 2,Test,0.2535121221995825,"{""demoScoreModel"": {""ln_vas_opted_flag"": ""0"", ...",2025-12-31 11:09:54,2025-12-31 11:13:03,2025-12
1,1245802,1d0736d2-3513-4061-aa90-297704499436,0.45418924527377563,2025-12-22 08:37:51.771485,2025-12-22 08:37:51.795152,beta_demo_model_sil,v2,SIL-Instore,F,Mall,ios,beta_demo_model_sil,SIL,Trench 2,Test,0.45418924527377563,"{""demoScoreModel"": {""ln_vas_opted_flag"": ""1"", ...",2025-12-22 16:37:46,NaT,2025-12
2,1319029,459258a7-afc9-44c3-bed2-8c0df2efabdf,0.421590480563884,2026-01-04 03:47:30.487436,2026-01-04 03:47:31.113172,beta_demo_model_sil,v2,SIL Competitor,F,Appliance,android,beta_demo_model_sil,SIL,Trench 2,Test,0.421590480563884,"{""demoScoreModel"": {""ln_vas_opted_flag"": ""1"", ...",2026-01-04 11:47:26,2026-01-04 11:52:00,2026-01
3,1701888,b3248d9b-f9f1-4d18-9137-e3aa9171682b,0.1293912176,2025-11-22 03:22:21.682505,2025-11-22 03:22:21.748007,beta_demo_model_sil,v1,SIL Competitor,F,Appliance,android,beta_demo_model_sil,SIL,ALL,Test,0.1293912176,"{""beta_de_ln_vas_opted_flag"": ""1"", ""beta_de_ln...",2025-11-22 11:22:19,NaT,2025-11
4,1845512,0643662e-342e-4521-925c-138cd7e6cd15,0.1989934897,2025-06-10 07:52:11.689997,2025-06-10 07:52:11.753739,beta_demo_model_sil,v1,SIL-Instore,M,Appliance,android,beta_demo_model_sil,SIL,ALL,Test,0.1989934897,"{""beta_de_ln_vas_opted_flag"": ""1"", ""beta_de_ln...",2025-06-04 11:54:00,NaT,2025-06

In [51]:
df1 = dfd.copy()

### Train

In [52]:
sq = """ 
WITH cleaned AS (
  SELECT
    customerId,digitalLoanAccountId,prediction,start_time,end_time,
    case when modelDisplayName = 'Beta - DemoScoreModel' then 'beta_demo_model_sil' else modelDisplayName end as modelDisplayName    
     ,modelVersionId,
        case when trenchCategory is null then 'ALL' 
         when trenchCategory = '' then 'ALL'
    else trenchCategory end trenchCategory,
    REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeature,
    REPLACE(REPLACE(cast(prediction as string), "'", '"'), "None", "null") AS prediction_clean
  FROM prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
  WHERE modelDisplayName in  ('Beta - DemoScoreModel', 'beta_demo_model_sil')
      ),
base as 
(SELECT
  r.customerId,r.digitalLoanAccountId,prediction,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'beta_demo_model_sil' Model_Name,
 'SIL' as product,
  trenchCategory,
  'Train' Data_selection,
  prediction as score,
 calcFeature calcFeatures,
    IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime) AS appln_submit_datetime,
    loanmaster.disbursementDateTime,
    format_date('%Y-%m', IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime)) as Application_month,
 FROM cleaned r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
 qualify row_number() over (partition by r.customerId,r.digitalLoanAccountId, modelVersionId 
order by   coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  cast(r.start_time as datetime)) desc) = 1
)
select * from base where lower(new_loan_type) like '%sil%'
;
"""

dfd = client.query(sq).to_dataframe()
dfd.head()

,customerId,digitalLoanAccountId,prediction,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,Data_selection,score,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1025403,7e3bfef4-a25e-42b5-8df8-abaf6736cde6,0.298597,2025-12-23T22:33:59.069704,2025-12-23T22:33:59.069704,beta_demo_model_sil,v2,SIL-Instore,F,Mall,android,beta_demo_model_sil,SIL,Trench 2,Train,0.298597,"{""ln_vas_opted_flag"": ""0"", ""ln_doc_type_rolled...",2025-08-01 14:14:38,2025-08-01 14:21:26,2025-08
1,1056924,786c75f2-d4bb-467e-bf2c-baf42a290111,0.454906,2025-12-23T22:33:59.378366,2025-12-23T22:33:59.378366,beta_demo_model_sil,v2,SIL-Instore,F,Appliance,ios,beta_demo_model_sil,SIL,Trench 2,Train,0.454906,"{""ln_vas_opted_flag"": ""1"", ""ln_doc_type_rolled...",2024-10-17 11:37:34,2024-10-17 11:40:04,2024-10
2,1180838,09778358-8c95-466e-8b9e-d772c81f5fe5,0.082535,2025-12-23T22:17:52.959670,2025-12-23T22:17:52.959670,beta_demo_model_sil,v1,SIL Repeat,M,Mall,android,beta_demo_model_sil,SIL,ALL,Train,0.082535,"{""beta_de_ln_vas_opted_flag"": ""0"", ""beta_de_ln...",2024-12-27 17:57:06,NaT,2024-12
3,1225465,60945f33-1bcb-4fea-beec-f0b6bf60ace3,0.071029,2025-12-23T22:18:35.385160,2025-12-23T22:18:35.385160,beta_demo_model_sil,v1,SIL-Instore,F,Appliance,android,beta_demo_model_sil,SIL,ALL,Train,0.071029,"{""beta_de_ln_vas_opted_flag"": ""1"", ""beta_de_ln...",2024-12-09 14:07:02,2024-12-09 14:21:49,2024-12
4,1227146,ba469b5c-512f-4d9b-9007-9ae6c46bca31,0.143901,2025-12-23T22:17:57.670400,2025-12-23T22:17:57.670400,beta_demo_model_sil,v1,SIL-Instore,M,Mobile,android,beta_demo_model_sil,SIL,ALL,Train,0.143901,"{""beta_de_ln_vas_opted_flag"": ""1"", ""beta_de_ln...",2024-10-19 18:42:08,NaT,2024-10

In [53]:
df2 = dfd.copy()

In [54]:
df_concat = pd.concat([df1, df2], ignore_index=True)
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")

The shape of the concatenated dataframe is: (936187, 20)

In [55]:
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")
df_combined = dropping_duplicates(df_concat)
print(f"The shape of the dataframe after dropping duplicates is: {df_combined.shape}")

The shape of the concatenated dataframe is: (936187, 20)
The shape of the dataframe after dropping duplicates is: (936187, 20)

In [56]:
df_combined['score'] = pd.to_numeric(df_combined['score'], errors='coerce')

### PSI calculation

In [57]:
score_output_df = calculate_psi_with_segments(
    df=df_combined,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
)

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

print(f"Output shape: {score_output_df.shape}")
print(f"\nOutput columns: {score_output_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(score_output_df.head(20))
print(f"\nData types:")
print(score_output_df.dtypes)

Output shape: (532, 10)

Output columns: ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count', 'modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']

First few rows:
      Month scorename DateCategory  psivalues  account_count modelVersionId  \
0   2025-11     score     Training   0.000000         321067             v1
1   2025-03     score      Monthly   0.212490            414             v1
2   2025-04     score      Monthly   0.271465           1039             v1
3   2025-05     score      Monthly   0.157399           1561             v1
4   2025-06     score      Monthly   0.154095          16368             v1
5   2025-07     score      Monthly   0.187953          22790             v1
6   2025-08     score      Monthly   0.196011          23270             v1
7   2025-09     score      Monthly   0.206522          21413             v1
8   2025-10     score      Monthly   0.280059          24822             v1
9   2025-11     score      Monthly   0.288194          28317             v1
10  2025-12     score      Monthly   0.276465          18895             v1
11  2025-11     score     Training   0.000000         372963             v2
12  2025-11     score      Monthly   0.045676           1413             v2
13  2025-12     score      Monthly   0.009295          30466             v2
14  2026-01     score      Monthly   0.004744          27358             v2
15  2026-02     score      Monthly   0.002236          23545             v2
16  2026-03     score      Monthly   0.032934            486             v2
17  2025-11     score     Training   0.000000         321067             v1
18  2025-03     score      Monthly   0.212490            414             v1
19  2025-04     score      Monthly   0.271465           1039             v1

   trenchCategory new_loan_type loan_product_type osType
0              NA            NA                NA     NA
1              NA            NA                NA     NA
2              NA            NA                NA     NA
3              NA            NA                NA     NA
4              NA            NA                NA     NA
5              NA            NA                NA     NA
6              NA            NA                NA     NA
7              NA            NA                NA     NA
8              NA            NA                NA     NA
9              NA            NA                NA     NA
10             NA            NA                NA     NA
11             NA            NA                NA     NA
12             NA            NA                NA     NA
13             NA            NA                NA     NA
14             NA            NA                NA     NA
15             NA            NA                NA     NA
16             NA            NA                NA     NA
17            ALL            NA                NA     NA
18            ALL            NA                NA     NA
19            ALL            NA                NA     NA

Data types:
Month                 object
scorename             object
DateCategory          object
psivalues            float64
account_count          int64
modelVersionId        object
trenchCategory        object
new_loan_type         object
loan_product_type     object
osType                object
dtype: object

In [58]:
score_output_df

score_output_df['Model_Name'] = 'beta_demo_model_sil'
score_output_df['scorename'] = score_output_df['scorename'].replace('score', 'sil_beta_demo_score')
score_output_df

,Month,scorename,DateCategory,psivalues,account_count,modelVersionId,trenchCategory,new_loan_type,loan_product_type,osType,Model_Name
0,2025-11,sil_beta_demo_score,Training,0.000000,321067,v1,NA,NA,NA,NA,beta_demo_model_sil
1,2025-03,sil_beta_demo_score,Monthly,0.212490,414,v1,NA,NA,NA,NA,beta_demo_model_sil
2,2025-04,sil_beta_demo_score,Monthly,0.271465,1039,v1,NA,NA,NA,NA,beta_demo_model_sil
3,2025-05,sil_beta_demo_score,Monthly,0.157399,1561,v1,NA,NA,NA,NA,beta_demo_model_sil
4,2025-06,sil_beta_demo_score,Monthly,0.154095,16368,v1,NA,NA,NA,NA,beta_demo_model_sil
...,...,...,...,...,...,...,...,...,...,...,...
527,2025-11,sil_beta_demo_score,Monthly,20.587815,1,v2,Trench 2,SIL ZERO,Appliance,ios,beta_demo_model_sil
528,2025-12,sil_beta_demo_score,Monthly,6.655938,21,v2,Trench 2,SIL ZERO,Appliance,ios,beta_demo_model_sil
529,2026-01,sil_beta_demo_score,Monthly,8.599668,11,v2,Trench 2,SIL ZERO,Appliance,ios,beta_demo_model_sil
530,2026-02,sil_beta_demo_score,Monthly,11.035031,6,v2,Trench 2,SIL ZERO,Appliance,ios,beta_demo_model_sil
531,2026-03,sil_beta_demo_score,Monthly,20.933028,1,v2,Trench 2,SIL ZERO,Appliance,ios,beta_demo_model_sil

In [59]:
psi_results = score_output_df.copy()

table_id = "prj-prod-dataplatform.dap_ds_poweruser_playground.beta_demo_score_model_psi_v7"
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",  # or "WRITE_APPEND"
)
job = client.load_table_from_dataframe(psi_results, table_id, job_config=job_config)
job.result()

C:\Users\Dwaipayan\AppData\Roaming\Python\Python312\site-packages\google\cloud\bigquery\_pandas_helpers.py:483: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=prj-prod-dataplatform, location=asia-southeast1, id=639d9416-6414-45ef-baf0-05297017a1c2>

## Beta SIL STACK Score Model

### Test

In [60]:
sq = """
WITH cleaned AS (
  SELECT
    customerId,digitalLoanAccountId,prediction,start_time,end_time,
    case when modelDisplayName = 'Beta - StackScoreModel' then 'beta_stack_model_sil' else modelDisplayName end as modelDisplayName ,   
    modelVersionId,
    case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
    REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeature,
    REPLACE(REPLACE(prediction, "'", '"'), "None", "null") AS prediction_clean
  FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
  WHERE modelDisplayName in ('Beta - StackScoreModel', 'beta_stack_model_sil')
  ),
base as 
(SELECT
  r.customerId,r.digitalLoanAccountId,prediction,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'beta_stack_model_sil' Model_Name,
 'SIL' as product,
  trenchCategory,
  'Test' Data_selection,
  -- sil_beta_stack_score
  prediction as score,
 calcFeature calcFeatures,
    coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) AS appln_submit_datetime,
    loanmaster.disbursementDateTime,
    format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time)) as Application_month,
 FROM cleaned r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid,  modelVersionId  order by coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) desc) = 1
  )
select * from base
where lower(new_loan_type) like '%sil%'
;
"""
dfd = client.query(sq).to_dataframe()
dfd.head()

,customerId,digitalLoanAccountId,prediction,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,Data_selection,score,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1403232,8fd55d35-caae-4831-ae01-83085300a27b,0.27660960053128913,2026-01-10 08:38:36.067453,2026-01-10 08:38:36.090977,beta_stack_model_sil,v2,SIL-Instore,F,Appliance,ios,beta_stack_model_sil,SIL,Trench 3,Test,0.27660960053128913,"{""stackScoreModel"": {""sb_demo_score"": 0.259486...",2026-01-10 16:38:29,2026-01-10 16:42:07,2026-01
1,1409391,f8a6d35b-827a-4387-a973-0fcef7d7fe11,0.14412345768647938,2026-02-05 03:58:17.472915,2026-02-05 03:58:18.117864,beta_stack_model_sil,v2,SIL ZERO,F,Appliance,android,beta_stack_model_sil,SIL,Trench 2,Test,0.14412345768647938,"{""stackScoreModel"": {""sb_demo_score"": 0.286369...",2026-02-05 11:58:14,2026-02-05 12:01:17,2026-02
2,1503188,8247031e-4a36-4378-be84-5d46a2a26562,0.6846513706074882,2026-01-24 06:52:42.939135,2026-01-24 06:52:43.595402,beta_stack_model_sil,v2,SIL-Instore,M,Appliance,android,beta_stack_model_sil,SIL,Trench 2,Test,0.6846513706074882,"{""stackScoreModel"": {""sb_demo_score"": 0.607578...",2026-01-24 14:52:39,NaT,2026-01
3,1503844,7a71803d-721d-4298-9bd9-b15ec05dbd61,0.20408063883229052,2025-12-20 04:38:25.894353,2025-12-20 04:38:26.579025,beta_stack_model_sil,v2,SIL-Instore,F,Appliance,android,beta_stack_model_sil,SIL,Trench 2,Test,0.20408063883229052,"{""stackScoreModel"": {""sb_demo_score"": 0.273819...",2025-12-20 12:38:20,2025-12-20 12:42:32,2025-12
4,1524001,cca0d9ea-09bf-46a0-9acc-949127e84a8a,0.027198365386525473,2025-08-19 07:24:46.318947,2025-08-19 07:24:46.323047,beta_stack_model_sil,v1,SIL-Instore,F,Mall,android,beta_stack_model_sil,SIL,ALL,Test,0.027198365386525473,"{""s_apps_score"": 0.26784130362265146, ""s_credo...",2025-08-19 15:24:42,2025-08-19 15:31:03,2025-08

In [61]:
df1 = dfd.copy()

### Train

In [62]:
sq = """ 
WITH cleaned AS (
  SELECT
    customerId,digitalLoanAccountId,prediction,start_time,end_time,
    case when modelDisplayName = 'Beta - StackScoreModel' then 'beta_stack_model_sil' else modelDisplayName end as modelDisplayName ,   
    modelVersionId,
    case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
    REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeature,
    REPLACE(REPLACE(cast(prediction as string), "'", '"'), "None", "null") AS prediction_clean
  FROM prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
  WHERE modelDisplayName in ('Beta - StackScoreModel', 'beta_stack_model_sil')
      ),
base as 
(SELECT
  r.customerId,r.digitalLoanAccountId,prediction,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'beta_demo_model_sil' Model_Name,
 'SIL' as product,
  trenchCategory,
  'Train' Data_selection,
  prediction as score,
 calcFeature calcFeatures,
    IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime) AS appln_submit_datetime,
    loanmaster.disbursementDateTime,
    format_date('%Y-%m', IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime)) as Application_month,
 FROM cleaned r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
 qualify row_number() over (partition by r.customerId,r.digitalLoanAccountId, modelVersionId 
order by   coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  cast(r.start_time as datetime)) desc) = 1
)
select * from base
where lower(new_loan_type) like '%sil%'
;
"""

dfd = client.query(sq).to_dataframe()
dfd.head()

,customerId,digitalLoanAccountId,prediction,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,Model_Name,product,trenchCategory,Data_selection,score,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1033734,b65c9c6a-cfc8-4946-99c2-7f45230757df,0.420388,2025-12-23T22:30:59.587302,2025-12-23T22:30:59.587302,beta_stack_model_sil,v2,SIL-Instore,F,Appliance,ios,beta_demo_model_sil,SIL,Trench 2,Train,0.420388,"{""sb_demo_score"": 0.4460781066672366, ""s_credo...",2024-11-21 18:06:14,NaT,2024-11
1,1070498,d059a5b5-e713-4d3d-b973-9d39456f578c,0.389967,2025-12-23T22:30:58.760210,2025-12-23T22:30:58.760210,beta_stack_model_sil,v2,SIL Competitor,F,Appliance,ios,beta_demo_model_sil,SIL,Trench 2,Train,0.389967,"{""sb_demo_score"": 0.3716181342388104, ""s_credo...",2025-04-17 13:28:22,2025-04-17 13:31:04,2025-04
2,1096654,2ddd8e20-17c8-4637-b8d9-7d457bd17c55,0.174228,2025-12-23T22:19:12.375888,2025-12-23T22:19:12.375888,beta_stack_model_sil,v1,SIL-Instore,M,Appliance,android,beta_demo_model_sil,SIL,ALL,Train,0.174228,"{""apps_score"": 0.5182126143707277, ""credo_gen_...",2023-09-25 12:41:06,2023-09-27 16:41:25,2023-09
3,1277768,bbdcd627-f480-4c93-9d4d-18dafd738125,0.223759,2025-12-23T22:19:14.422330,2025-12-23T22:19:14.422330,beta_stack_model_sil,v1,SIL-Instore,M,Mobile,android,beta_demo_model_sil,SIL,ALL,Train,0.223759,"{""apps_score"": 0.5251366724186015, ""credo_gen_...",2024-09-16 20:56:38,NaT,2024-09
4,1322864,185dcfa5-e5e1-4c47-9908-9deaa50908eb,0.598833,2025-12-23T22:30:59.040902,2025-12-23T22:30:59.040902,beta_stack_model_sil,v2,SIL-Instore,F,Appliance,android,beta_demo_model_sil,SIL,Trench 2,Train,0.598833,"{""sb_demo_score"": 0.479912707140512, ""apps_sco...",2025-05-18 16:56:32,2025-05-18 17:04:34,2025-05

In [63]:
df2 = dfd.copy()

In [64]:
df_concat = pd.concat([df1, df2], ignore_index=True)
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")

The shape of the concatenated dataframe is: (934093, 20)

In [65]:
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")
df_combined = dropping_duplicates(df_concat)
print(f"The shape of the dataframe after dropping duplicates is: {df_combined.shape}")

The shape of the concatenated dataframe is: (934093, 20)
The shape of the dataframe after dropping duplicates is: (934093, 20)

In [66]:
df_combined['score'] = pd.to_numeric(df_combined['score'], errors='coerce')

### PSI calculation

In [67]:
score_output_df = calculate_psi_with_segments(
    df=df_combined,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
)

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

print(f"Output shape: {score_output_df.shape}")
print(f"\nOutput columns: {score_output_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(score_output_df.head(20))
print(f"\nData types:")
print(score_output_df.dtypes)

Output shape: (532, 10)

Output columns: ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count', 'modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']

First few rows:
      Month scorename DateCategory  psivalues  account_count modelVersionId  \
0   2025-11     score     Training   0.000000         321067             v1
1   2025-03     score      Monthly   0.135260            414             v1
2   2025-04     score      Monthly   0.039789           1039             v1
3   2025-05     score      Monthly   0.042864           1561             v1
4   2025-06     score      Monthly   0.049583          16368             v1
5   2025-07     score      Monthly   0.063482          22790             v1
6   2025-08     score      Monthly   0.058819          23270             v1
7   2025-09     score      Monthly   0.055673          21413             v1
8   2025-10     score      Monthly   0.074304          24822             v1
9   2025-11     score      Monthly   0.073044          28317             v1
10  2025-12     score      Monthly   0.073772          18895             v1
11  2025-11     score     Training   0.000000         370869             v2
12  2025-11     score      Monthly   0.032788           1413             v2
13  2025-12     score      Monthly   0.004843          30466             v2
14  2026-01     score      Monthly   0.007463          27358             v2
15  2026-02     score      Monthly   0.013966          23545             v2
16  2026-03     score      Monthly   0.021629            486             v2
17  2025-11     score     Training   0.000000         321067             v1
18  2025-03     score      Monthly   0.135260            414             v1
19  2025-04     score      Monthly   0.039789           1039             v1

   trenchCategory new_loan_type loan_product_type osType
0              NA            NA                NA     NA
1              NA            NA                NA     NA
2              NA            NA                NA     NA
3              NA            NA                NA     NA
4              NA            NA                NA     NA
5              NA            NA                NA     NA
6              NA            NA                NA     NA
7              NA            NA                NA     NA
8              NA            NA                NA     NA
9              NA            NA                NA     NA
10             NA            NA                NA     NA
11             NA            NA                NA     NA
12             NA            NA                NA     NA
13             NA            NA                NA     NA
14             NA            NA                NA     NA
15             NA            NA                NA     NA
16             NA            NA                NA     NA
17            ALL            NA                NA     NA
18            ALL            NA                NA     NA
19            ALL            NA                NA     NA

Data types:
Month                 object
scorename             object
DateCategory          object
psivalues            float64
account_count          int64
modelVersionId        object
trenchCategory        object
new_loan_type         object
loan_product_type     object
osType                object
dtype: object

In [68]:
score_output_df

score_output_df['Model_Name'] = 'beta_stack_model_sil'
score_output_df['scorename'] = score_output_df['scorename'].replace('score', 'sil_beta_stack_score')
score_output_df

,Month,scorename,DateCategory,psivalues,account_count,modelVersionId,trenchCategory,new_loan_type,loan_product_type,osType,Model_Name
0,2025-11,sil_beta_stack_score,Training,0.000000,321067,v1,NA,NA,NA,NA,beta_stack_model_sil
1,2025-03,sil_beta_stack_score,Monthly,0.135260,414,v1,NA,NA,NA,NA,beta_stack_model_sil
2,2025-04,sil_beta_stack_score,Monthly,0.039789,1039,v1,NA,NA,NA,NA,beta_stack_model_sil
3,2025-05,sil_beta_stack_score,Monthly,0.042864,1561,v1,NA,NA,NA,NA,beta_stack_model_sil
4,2025-06,sil_beta_stack_score,Monthly,0.049583,16368,v1,NA,NA,NA,NA,beta_stack_model_sil
...,...,...,...,...,...,...,...,...,...,...,...
527,2025-11,sil_beta_stack_score,Monthly,20.552170,1,v2,Trench 2,SIL ZERO,Appliance,ios,beta_stack_model_sil
528,2025-12,sil_beta_stack_score,Monthly,2.130542,21,v2,Trench 2,SIL ZERO,Appliance,ios,beta_stack_model_sil
529,2026-01,sil_beta_stack_score,Monthly,8.377185,11,v2,Trench 2,SIL ZERO,Appliance,ios,beta_stack_model_sil
530,2026-02,sil_beta_stack_score,Monthly,10.673442,6,v2,Trench 2,SIL ZERO,Appliance,ios,beta_stack_model_sil
531,2026-03,sil_beta_stack_score,Monthly,20.899907,1,v2,Trench 2,SIL ZERO,Appliance,ios,beta_stack_model_sil

In [69]:
psi_results = score_output_df.copy()
table_id = "prj-prod-dataplatform.dap_ds_poweruser_playground.beta_sil_stack_model_psi_v7"
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",  # or "WRITE_APPEND"
)
job = client.load_table_from_dataframe(psi_results, table_id, job_config=job_config)
job.result()

C:\Users\Dwaipayan\AppData\Roaming\Python\Python312\site-packages\google\cloud\bigquery\_pandas_helpers.py:483: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=prj-prod-dataplatform, location=asia-southeast1, id=826bf595-6656-4962-bfbc-cd7c46e6c914>

## Cash

### Queries

### Alpha-Cash-CIC-Model (All Trench)

#### Test

In [70]:
sq = """
WITH parsed as (
select customerId, digitalLoanAccountId,
case when modelDisplayName in('Alpha-Cash-CIC-Model','Alpha Cash CIC Model') then 'cic_model_cash' else modelDisplayName end modelDisplayName,
modelVersionId,
start_time,
end_time,
prediction,
   case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeatures,
FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
where modelDisplayName in ('Alpha-Cash-CIC-Model','Alpha Cash CIC Model','cic_model_cash')
),
base as
(select 
 r.customerId,r.digitalLoanAccountId,
 prediction score
 -- aCicScore 
 ,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'Cash' as product,
 'cic_model_cash' Model_Name,
  trenchCategory,
   'Test' Data_selection,
  calcFeatures,
  coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time)) as Application_month, 
from parsed r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid order by cast(start_time as datetime) desc) = 1
)
select * from base where lower(new_loan_type) not like '%sil%'
""" 

dfd= client.query(sq).to_dataframe(progress_bar_type='tqdm')
dfd.head()

Job ID e0f17f67-bb58-42d9-af98-6cd43cc5d5f0 successfully executed: 100%|██████████|
Downloading: 100%|██████████|

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1021278,b75985b8-7918-4886-b600-35c2dc245847,0.4489282337924156,2025-12-04 08:42:38.328429,2025-12-04 08:42:38.434076,cic_model_cash,v1,Quick,M,not applicable,ios,Cash,cic_model_cash,Trench 2,Test,"{""cic_max_age_all_contracts_snapshot"": 885.0, ...",2025-12-04 16:42:23,2025-12-04 16:57:32,2025-12
1,1029290,119c1289-b11f-463d-9496-e7042a3c47a6,0.4844123653424989,2025-12-16 08:17:18.514163,2025-12-16 08:17:18.601228,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 2,Test,"{""cic_max_age_all_contracts_snapshot"": 326.0, ...",2025-12-16 16:16:56,2025-12-16 20:58:06,2025-12
2,1043146,40d55684-4295-430d-9e13-c06f162f45b4,0.5035218705903189,2025-12-15 04:07:34.728235,2025-12-15 04:07:34.834656,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 2,Test,"{""cic_max_age_all_contracts_snapshot"": 1290, ""...",2025-12-15 12:07:06,2025-12-19 08:59:52,2025-12
3,1066552,ea8f32de-fbe1-4ab9-8b7c-c8b842889206,0.4140830779780114,2025-11-12 09:19:16.269930,2025-11-12 09:19:16.396402,cic_model_cash,v1,Quick,F,not applicable,ios,Cash,cic_model_cash,Trench 2,Test,"{""cic_max_age_all_contracts_snapshot"": 1192.0,...",2025-11-12 17:19:01,NaT,2025-11
4,1082414,eda07cc7-20a8-40f2-b18a-a1495479466f,0.4788668086024414,2026-01-03 07:08:12.877614,2026-01-03 07:08:12.973297,cic_model_cash,v1,Quick,M,not applicable,android,Cash,cic_model_cash,Trench 2,Test,"{""cic_max_age_all_contracts_snapshot"": 509.0, ...",2026-01-03 15:07:59,2026-01-03 17:00:59,2026-01

In [71]:
df1 = dfd.copy()

#### Train

In [72]:
sq = """ 
WITH parsed as (
select customerId, digitalLoanAccountId,
case when modelDisplayName in('Alpha-Cash-CIC-Model','Alpha Cash CIC Model') then 'cic_model_cash' end modelDisplayName,
modelVersionId,
start_time,
end_time,
prediction,
   case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeatures,
FROM prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
where modelDisplayName in ('Alpha-Cash-CIC-Model','Alpha Cash CIC Model','cic_model_cash')
),
base as
(select 
 r.customerId,r.digitalLoanAccountId,
 prediction score 
 ,start_time,end_time,
  r.modelDisplayName,
  r.modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'Cash' as product,
 'cic_model_cash' Model_Name,
  trenchCategory,
   'Train' Data_selection,
  calcFeatures,
  IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m', IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime)) as Application_month, 
from parsed r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid order by cast(start_time as datetime) desc) = 1
)
select * from base where lower(new_loan_type) not like '%sil%'
;
"""
dfd= client.query(sq).to_dataframe(progress_bar_type='tqdm')
dfd.head()

Job ID 4b9ebed7-f0af-4f1a-95f4-cac793a6f35e successfully executed: 100%|██████████|
Downloading: 100%|██████████|

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1016599,a0d992e4-91a0-4a46-b4cb-922421c37484,0.482942,2025-12-23T22:23:30.422296,2025-12-23T22:23:30.422296,cic_model_cash,v1,Quick,F,not applicable,ios,Cash,cic_model_cash,Trench 2,Train,"{""max_age_all_contracts_snapshot"": 238.0, ""rat...",2024-09-05 10:04:43,NaT,2024-09
1,1028348,8aa7401c-5418-4cdf-99a8-66781d7a634d,0.619431,2025-12-23T22:23:28.172990,2025-12-23T22:23:28.172990,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 2,Train,"{""ScoreRange"": ""NH_Fi"", ""ln_loan_level_user_ty...",2024-09-02 17:55:03,NaT,2024-09
2,1074782,15b94416-f6d0-4ddf-9dc3-c5305069d919,0.521654,2025-12-23T22:23:29.462625,2025-12-23T22:23:29.462625,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 2,Train,"{""max_age_all_contracts_snapshot"": 408.0, ""rat...",2024-09-17 14:37:34,NaT,2024-09
3,1193594,a22516ca-8831-4852-8c39-67cadc0d0b1c,0.720237,2025-12-23T22:23:32.100613,2025-12-23T22:23:32.100613,cic_model_cash,v1,Quick,F,not applicable,ios,Cash,cic_model_cash,Trench 2,Train,"{""max_age_all_contracts_snapshot"": 774.0, ""rat...",2024-09-02 10:41:54,NaT,2024-09
4,1219384,eeb0bf9e-5e9b-42ae-96ad-a390e14edc66,0.611082,2025-12-23T22:23:32.631426,2025-12-23T22:23:32.631426,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 2,Train,"{""max_age_all_contracts_snapshot"": 1707.0, ""ra...",2024-09-26 20:39:08,NaT,2024-09

In [73]:
df2 = dfd.copy()

In [74]:
df_concat = pd.concat([df1, df2], ignore_index=True)
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")

The shape of the concatenated dataframe is: (240781, 19)

In [75]:
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")
df_combined = dropping_duplicates(df_concat)
print(f"The shape of the dataframe after dropping duplicates is: {df_combined.shape}")

The shape of the concatenated dataframe is: (240781, 19)
The shape of the dataframe after dropping duplicates is: (240781, 19)

In [76]:
df_combined['score'] = pd.to_numeric(df_combined['score'], errors='coerce')

In [77]:
df_combined.sample(10)

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
170670,2611597,00f68d7a-f585-4eae-b7ad-7712c20f1586,0.608727,2025-12-23T22:23:27.078304,2025-12-23T22:23:27.078304,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 2,Train,"{""max_age_all_contracts_snapshot"": 338.0, ""rat...",2025-03-05 20:30:18,NaT,2025-03
93778,3911394,c61adf09-bf64-4772-9c23-df9965cca556,0.524017,2025-12-20 00:40:57.531378,2025-12-20 00:40:57.636572,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 1,Test,"{""cic_max_age_all_contracts_snapshot"": 101, ""c...",2025-12-20 08:40:43,2025-12-20 08:54:40,2025-12
178962,3024176,b75ddc3d-457c-432f-8148-0639fc45a5cf,0.477686,2025-12-23T22:23:29.601319,2025-12-23T22:23:29.601319,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 2,Train,"{""max_age_all_contracts_snapshot"": 588.0, ""rat...",2025-04-21 21:45:34,NaT,2025-04
164574,2169098,dfb2bc0b-866e-473a-ba0a-23d35ec25d27,0.330074,2025-12-23T22:23:29.187942,2025-12-23T22:23:29.187942,cic_model_cash,v1,Quick,F,not applicable,ios,Cash,cic_model_cash,Trench 2,Train,"{""max_age_all_contracts_snapshot"": 3797.0, ""ra...",2025-02-16 17:11:51,2025-02-17 10:09:16,2025-02
163723,3292250,d6efba05-0555-4323-b8d9-12dab45314ef,0.532228,2025-12-23T22:23:08.517297,2025-12-23T22:23:08.517297,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 1,Train,"{""max_age_all_contracts_snapshot"": 759.0, ""rat...",2025-02-27 20:07:22,2025-03-23 21:22:26,2025-02
236081,2847338,638d9363-78a9-448e-b747-4648f8f2873c,0.507892,2025-12-23T22:23:29.488664,2025-12-23T22:23:29.488664,cic_model_cash,v1,Quick,F,not applicable,ios,Cash,cic_model_cash,Trench 2,Train,"{""max_age_all_contracts_snapshot"": 794.0, ""rat...",2025-09-07 10:33:48,NaT,2025-09
113592,2969891,a1a3a5ec-4b8b-439f-ae1b-4279faaa1b63,0.432106,2025-12-23T22:23:13.778698,2025-12-23T22:23:13.778698,cic_model_cash,v1,Quick,M,not applicable,android,Cash,cic_model_cash,Trench 1,Train,"{""max_age_all_contracts_snapshot"": 1156.0, ""ra...",2024-10-27 17:38:21,2024-10-27 18:13:20,2024-10
182170,2663003,f11a2642-fe89-495b-99ca-1661fc15bcf8,0.699868,2025-12-23T22:23:32.019384,2025-12-23T22:23:32.019384,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 2,Train,"{""max_age_all_contracts_snapshot"": 1196.0, ""ra...",2025-04-12 06:26:33,NaT,2025-04
171556,3317621,bd954a73-5b65-4b71-bad3-9015a75f42f0,0.398051,2025-12-23T22:23:08.242907,2025-12-23T22:23:08.242907,cic_model_cash,v1,Quick,F,not applicable,ios,Cash,cic_model_cash,Trench 1,Train,"{""max_age_all_contracts_snapshot"": 2317.0, ""ra...",2025-03-29 23:46:16,NaT,2025-03
92421,3307044,670d9bcc-9bc1-458d-a1cd-15c4f086874e,0.473404,2025-11-03 07:07:07.257488,2025-11-03 07:07:07.411110,cic_model_cash,v1,Quick,F,not applicable,android,Cash,cic_model_cash,Trench 2,Test,"{""cic_max_age_all_contracts_snapshot"": 1224.0,...",2025-11-03 15:06:54,2025-11-03 17:40:55,2025-11

### PSI calculation

In [78]:
score_output_df = calculate_psi_with_segments(
    df=df_combined,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
)

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

print(f"Output shape: {score_output_df.shape}")
print(f"\nOutput columns: {score_output_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(score_output_df.head(20))
print(f"\nData types:")
print(score_output_df.dtypes)

Output shape: (128, 10)

Output columns: ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count', 'modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']

First few rows:
      Month scorename DateCategory  psivalues  account_count modelVersionId  \
0   2025-09     score     Training   0.000000         145746             v1
1   2025-09     score      Monthly   0.071033            134             v1
2   2025-10     score      Monthly   0.004982           9210             v1
3   2025-11     score      Monthly   0.021048          18803             v1
4   2025-12     score      Monthly   0.073764          29260             v1
5   2026-01     score      Monthly   0.017216          19254             v1
6   2026-02     score      Monthly   0.016566          18073             v1
7   2026-03     score      Monthly   0.055413            301             v1
8   2025-09     score     Training   0.000000          48479             v1
9   2025-09     score      Monthly   2.194329             31             v1
10  2025-10     score      Monthly   0.032051           2355             v1
11  2025-11     score      Monthly   0.018651          10225             v1
12  2025-12     score      Monthly   0.083924          15854             v1
13  2026-01     score      Monthly   0.026692           5370             v1
14  2026-02     score      Monthly   0.023412           4960             v1
15  2026-03     score      Monthly   0.293193             67             v1
16  2025-09     score     Training   0.000000          77967             v1
17  2025-09     score      Monthly   0.206073             86             v1
18  2025-10     score      Monthly   0.013947           6039             v1
19  2025-11     score      Monthly   0.014011           7675             v1

   trenchCategory new_loan_type loan_product_type osType
0              NA            NA                NA     NA
1              NA            NA                NA     NA
2              NA            NA                NA     NA
3              NA            NA                NA     NA
4              NA            NA                NA     NA
5              NA            NA                NA     NA
6              NA            NA                NA     NA
7              NA            NA                NA     NA
8        Trench 2            NA                NA     NA
9        Trench 2            NA                NA     NA
10       Trench 2            NA                NA     NA
11       Trench 2            NA                NA     NA
12       Trench 2            NA                NA     NA
13       Trench 2            NA                NA     NA
14       Trench 2            NA                NA     NA
15       Trench 2            NA                NA     NA
16       Trench 1            NA                NA     NA
17       Trench 1            NA                NA     NA
18       Trench 1            NA                NA     NA
19       Trench 1            NA                NA     NA

Data types:
Month                 object
scorename             object
DateCategory          object
psivalues            float64
account_count          int64
modelVersionId        object
trenchCategory        object
new_loan_type         object
loan_product_type     object
osType                object
dtype: object

In [79]:
score_output_df
score_output_df['Model_Name'] = 'cic_model_cash'
score_output_df['scorename'] = score_output_df['scorename'].replace('score', 'cic_model_cash_score')
score_output_df

,Month,scorename,DateCategory,psivalues,account_count,modelVersionId,trenchCategory,new_loan_type,loan_product_type,osType,Model_Name
0,2025-09,cic_model_cash_score,Training,0.000000,145746,v1,NA,NA,NA,NA,cic_model_cash
1,2025-09,cic_model_cash_score,Monthly,0.071033,134,v1,NA,NA,NA,NA,cic_model_cash
2,2025-10,cic_model_cash_score,Monthly,0.004982,9210,v1,NA,NA,NA,NA,cic_model_cash
3,2025-11,cic_model_cash_score,Monthly,0.021048,18803,v1,NA,NA,NA,NA,cic_model_cash
4,2025-12,cic_model_cash_score,Monthly,0.073764,29260,v1,NA,NA,NA,NA,cic_model_cash
...,...,...,...,...,...,...,...,...,...,...,...
123,2025-11,cic_model_cash_score,Monthly,0.055762,363,v1,Trench 3,Quick,not applicable,ios,cic_model_cash
124,2025-12,cic_model_cash_score,Monthly,0.066168,423,v1,Trench 3,Quick,not applicable,ios,cic_model_cash
125,2026-01,cic_model_cash_score,Monthly,0.108791,383,v1,Trench 3,Quick,not applicable,ios,cic_model_cash
126,2026-02,cic_model_cash_score,Monthly,0.047808,587,v1,Trench 3,Quick,not applicable,ios,cic_model_cash
127,2026-03,cic_model_cash_score,Monthly,6.889943,11,v1,Trench 3,Quick,not applicable,ios,cic_model_cash

In [80]:
psi_results = score_output_df.copy()
# Upload to BigQuery
table_id = "prj-prod-dataplatform.dap_ds_poweruser_playground.alpha_cash_cic_model_psi_v7"
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",  # or "WRITE_APPEND"
)
job = client.load_table_from_dataframe(psi_results, table_id, job_config=job_config)
job.result()  # Wait for the job to complete

C:\Users\Dwaipayan\AppData\Roaming\Python\Python312\site-packages\google\cloud\bigquery\_pandas_helpers.py:483: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=prj-prod-dataplatform, location=asia-southeast1, id=0c077b20-42c2-418e-b60f-145b551d2d36>

### Alpha-Cash-Stack-Model

#### Test

In [81]:
sq = """ 
WITH parsed as (
select customerId, digitalLoanAccountId,
case when  modelDisplayName in ('Alpha-Cash-Stack-Model') then 'alpha_stack_model_cash' else modelDisplayName end as modelDisplayName,
modelVersionId,
start_time,
end_time,
prediction,
   case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeatures,
FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
where modelDisplayName in ('Alpha-Cash-Stack-Model', 'alpha_stack_model_cash')
),
base as
(select 
 r.customerId,r.digitalLoanAccountId
 ,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'Cash' as product,
 'alpha_stack_model_cash' Model_Name,
  trenchCategory,
   'Test' Data_selection,
  calcFeatures,
  prediction score,
  coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time)) as Application_month, 
from parsed r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid order by cast(start_time as datetime) desc) = 1
)
select * from base where lower(new_loan_type) not like '%sil%'
;
"""

dfd= client.query(sq).to_dataframe(progress_bar_type='tqdm')
dfd.head()

Job ID 14b3ee13-b192-4637-9501-ac3af144244f successfully executed: 100%|██████████|
Downloading: 100%|██████████|

,customerId,digitalLoanAccountId,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,score,appln_submit_datetime,disbursementDateTime,Application_month
0,1021278,b75985b8-7918-4886-b600-35c2dc245847,2025-12-04 08:42:38.328429,2025-12-04 08:42:38.434438,alpha_stack_model_cash,v1,Quick,M,not applicable,ios,Cash,alpha_stack_model_cash,Trench 2,Test,"{""apps_score"": null, ""c_demo_score"": 0.3361856...",0.13938851579489592,2025-12-04 16:42:23,2025-12-04 16:57:32,2025-12
1,1029290,119c1289-b11f-463d-9496-e7042a3c47a6,2025-12-16 08:17:18.514163,2025-12-16 08:17:18.601571,alpha_stack_model_cash,v1.1,Quick,F,not applicable,android,Cash,alpha_stack_model_cash,Trench 2,Test,"{""apps_score"": 0.5215029376832699, ""c_demo_sco...",0.4147199313177051,2025-12-16 16:16:56,2025-12-16 20:58:06,2025-12
2,1043146,40d55684-4295-430d-9e13-c06f162f45b4,2025-12-15 04:07:34.728235,2025-12-15 04:07:34.834996,alpha_stack_model_cash,v1.1,Quick,F,not applicable,android,Cash,alpha_stack_model_cash,Trench 2,Test,"{""apps_score"": 0.5052307414720665, ""c_demo_sco...",0.4109359604467927,2025-12-15 12:07:06,2025-12-19 08:59:52,2025-12
3,1066552,ea8f32de-fbe1-4ab9-8b7c-c8b842889206,2025-11-12 09:19:16.269930,2025-11-12 09:19:16.396791,alpha_stack_model_cash,v1,Quick,F,not applicable,ios,Cash,alpha_stack_model_cash,Trench 2,Test,"{""apps_score"": null, ""c_demo_score"": 0.3939944...",0.11382406398674749,2025-11-12 17:19:01,NaT,2025-11
4,1082414,eda07cc7-20a8-40f2-b18a-a1495479466f,2026-01-03 07:08:12.877614,2026-01-03 07:08:12.973649,alpha_stack_model_cash,v1.1,Quick,M,not applicable,android,Cash,alpha_stack_model_cash,Trench 2,Test,"{""apps_score"": 0.4763168821039231, ""c_demo_sco...",0.31935137541414554,2026-01-03 15:07:59,2026-01-03 17:00:59,2026-01

In [82]:
df1 = dfd.copy()

#### Train

In [83]:
sq = """ 
WITH parsed as (
select customerId, digitalLoanAccountId,
case when  modelDisplayName in ('Alpha-Cash-Stack-Model') then 'alpha_stack_model_cash' else modelDisplayName end as modelDisplayName,
modelVersionId,
start_time,
end_time,
prediction,
   case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeatures,
FROM prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
where modelDisplayName in ('Alpha-Cash-Stack-Model', 'alpha_stack_model_cash')
),
base as
(select 
 r.customerId,r.digitalLoanAccountId,prediction score 
 ,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type ,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'Cash' as product,
 'alpha_stack_model_cash' Model_Name,
  trenchCategory,
   'Train' Data_selection,
  calcFeatures,
  IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m',IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime)) as Application_month, 
from parsed r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid order by cast(start_time as datetime) desc) = 1
)
select * from base where lower(new_loan_type) not like '%sil%'

"""
dfd= client.query(sq).to_dataframe(progress_bar_type='tqdm')
dfd.head()

Job ID 0df102bc-e855-4020-a2a7-f298ad76e447 successfully executed: 100%|██████████|
Downloading: 100%|██████████|

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1022910,be499b08-8210-40bf-8da9-30084abfa70d,0.078464,2025-12-23T22:22:49.368914,2025-12-23T22:22:49.368914,alpha_stack_model_cash,v1,Quick,F,not applicable,android,Cash,alpha_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.4629508333338754, ""apps_score...",2024-10-20 13:39:03,2024-10-20 13:42:51,2024-10
1,1146761,4afb8676-e01e-4459-b634-4e534b9d40e3,0.530454,2025-12-23T22:22:50.485926,2025-12-23T22:22:50.485926,alpha_stack_model_cash,v1,Quick,M,not applicable,android,Cash,alpha_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.4369173525685635, ""apps_score...",2024-10-15 21:44:24,NaT,2024-10
2,1181666,6a98f8da-1d9f-45a1-aece-0c2770c1035a,0.416180,2025-12-23T22:22:49.226902,2025-12-23T22:22:49.226902,alpha_stack_model_cash,v1,Quick,F,not applicable,android,Cash,alpha_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.547991957804576, ""apps_score""...",2024-10-13 18:09:51,NaT,2024-10
3,1330746,473a1f5f-8b34-4ab4-b641-d482785f142f,0.887773,2025-12-23T22:22:50.618782,2025-12-23T22:22:50.618782,alpha_stack_model_cash,v1,Quick,F,not applicable,android,Cash,alpha_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.657301505649539, ""apps_score""...",2024-10-08 17:44:12,NaT,2024-10
4,1366068,80de41d2-181c-4aa7-be29-74b9125e1469,0.772347,2025-12-23T22:22:50.279593,2025-12-23T22:22:50.279593,alpha_stack_model_cash,v1,Quick,F,not applicable,android,Cash,alpha_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.5472972438386717, ""apps_score...",2024-10-18 20:41:34,NaT,2024-10

In [84]:
df2 = dfd.copy()

In [85]:
df_concat = pd.concat([df1, df2], ignore_index=True)
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")

The shape of the concatenated dataframe is: (224093, 19)

In [86]:
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")
df_combined = dropping_duplicates(df_concat)
print(f"The shape of the dataframe after dropping duplicates is: {df_combined.shape}")

The shape of the concatenated dataframe is: (224093, 19)
The shape of the dataframe after dropping duplicates is: (224093, 19)

In [87]:
df_combined['score'] = pd.to_numeric(df_combined['score'], errors='coerce')

In [88]:
df_combined.sample(10)

,customerId,digitalLoanAccountId,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,score,appln_submit_datetime,disbursementDateTime,Application_month
131663,3190534,dfebe24e-736c-4926-8337-515e16cd5ba1,2025-12-23T22:22:39.820979,2025-12-23T22:22:39.820979,alpha_stack_model_cash,v1,Quick,F,not applicable,ios,Cash,alpha_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.6333764635169523, ""credo_scor...",0.839473,2025-01-15 05:37:33,NaT,2025-01
128893,3083289,ab00d6f6-7083-45ea-8545-2fcf2ed36425,2025-12-23T22:22:39.532126,2025-12-23T22:22:39.532126,alpha_stack_model_cash,v1,Quick,F,not applicable,ios,Cash,alpha_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.5199632267947087, ""credo_scor...",0.504335,2024-12-06 17:25:54,NaT,2024-12
153359,2859986,39d9133d-9b1f-4d62-8dc9-acbe7366e098,2025-12-23T22:22:52.026188,2025-12-23T22:22:52.026188,alpha_stack_model_cash,v1,Quick,F,not applicable,ios,Cash,alpha_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.4737475789467241, ""credo_scor...",0.363538,2025-03-04 08:07:35,NaT,2025-03
87251,4064775,8e9e9087-221f-40ad-acb1-0bda8e4afbfe,2026-01-31 14:31:44.299758,2026-01-31 14:31:44.397133,alpha_stack_model_cash,v1.1,Quick,M,not applicable,android,Cash,alpha_stack_model_cash,Trench 1,Test,"{""apps_score"": 0.5130310756336074, ""c_demo_sco...",0.718099,2026-01-31 22:31:26,NaT,2026-01
104526,2959482,c2d9b4ed-1f1c-452e-9a3e-b153a14be92c,2025-12-23T22:22:35.211816,2025-12-23T22:22:35.211816,alpha_stack_model_cash,v1,Quick,M,not applicable,android,Cash,alpha_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.5700589125786139, ""apps_score...",0.834631,2024-10-21 23:58:24,NaT,2024-10
60260,3828998,781c0fd6-cc75-41f7-a252-63b1ac61f592,2025-12-03 06:26:03.527093,2025-12-03 06:26:03.625395,alpha_stack_model_cash,v1,Quick,M,not applicable,android,Cash,alpha_stack_model_cash,Trench 1,Test,"{""apps_score"": 0.5229385995687521, ""c_demo_sco...",0.546064,2025-12-03 14:25:50,2025-12-03 14:33:00,2025-12
167984,3376986,089b619e-2e18-49a8-9d73-d6fc6d4450d4,2025-12-23T22:22:36.680403,2025-12-23T22:22:36.680403,alpha_stack_model_cash,v1,Quick,F,not applicable,android,Cash,alpha_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.607488066955819, ""apps_score""...",0.658316,2025-04-13 13:46:35,NaT,2025-04
112690,2709571,1165390f-4445-461c-a66c-68d5b5ac8f7d,2025-12-23T22:22:49.624798,2025-12-23T22:22:49.624798,alpha_stack_model_cash,v1,Quick,F,not applicable,android,Cash,alpha_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.6119750498646548, ""apps_score...",0.434459,2024-11-21 14:29:02,NaT,2024-11
16237,2841166,40486d61-0a60-452c-a6a4-b896b54750d5,2025-12-03 05:44:49.100693,2025-12-03 05:44:49.215049,alpha_stack_model_cash,v1,Quick,F,not applicable,ios,Cash,alpha_stack_model_cash,Trench 3,Test,"{""apps_score"": null, ""c_demo_score"": 0.4501940...",0.396320,2025-12-03 13:44:28,2025-12-03 13:47:46,2025-12
147768,3212904,5f82171c-8eae-4e97-86b9-9bc79eed7854,2025-12-23T22:22:36.590115,2025-12-23T22:22:36.590115,alpha_stack_model_cash,v1,Quick,M,not applicable,android,Cash,alpha_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.44694446743298216, ""apps_scor...",0.888692,2025-02-06 20:22:41,NaT,2025-02

### PSI calculation

In [89]:
score_output_df = calculate_psi_with_segments(
    df=df_combined,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
)

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

print(f"Output shape: {score_output_df.shape}")
print(f"\nOutput columns: {score_output_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(score_output_df.head(20))
print(f"\nData types:")
print(score_output_df.dtypes)

Output shape: (98, 10)

Output columns: ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count', 'modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']

First few rows:
      Month scorename DateCategory  psivalues  account_count modelVersionId  \
0   2025-09     score     Training   0.000000         129058             v1
1   2025-09     score      Monthly   0.573402            134             v1
2   2025-10     score      Monthly   0.133387           9210             v1
3   2025-11     score      Monthly   0.135991          18803             v1
4   2025-12     score      Monthly   0.138993          11761             v1
5   2026-01     score      Monthly   2.768859           1023             v1
6   2026-02     score      Monthly   2.254437           1361             v1
7   2026-03     score      Monthly   4.358015             25             v1
8   2025-09     score     Training   0.000000          42982             v1
9   2025-09     score      Monthly   4.296736             31             v1
10  2025-10     score      Monthly   0.340872           2355             v1
11  2025-11     score      Monthly   0.306604          10225             v1
12  2025-12     score      Monthly   0.322299           5907             v1
13  2025-09     score     Training   0.000000          67807             v1
14  2025-09     score      Monthly   2.304206             86             v1
15  2025-10     score      Monthly   0.159201           6039             v1
16  2025-11     score      Monthly   0.131975           7675             v1
17  2025-12     score      Monthly   0.156285           4791             v1
18  2025-09     score     Training   0.000000          18269             v1
19  2025-09     score      Monthly   4.510130             17             v1

   trenchCategory new_loan_type loan_product_type osType
0              NA            NA                NA     NA
1              NA            NA                NA     NA
2              NA            NA                NA     NA
3              NA            NA                NA     NA
4              NA            NA                NA     NA
5              NA            NA                NA     NA
6              NA            NA                NA     NA
7              NA            NA                NA     NA
8        Trench 2            NA                NA     NA
9        Trench 2            NA                NA     NA
10       Trench 2            NA                NA     NA
11       Trench 2            NA                NA     NA
12       Trench 2            NA                NA     NA
13       Trench 1            NA                NA     NA
14       Trench 1            NA                NA     NA
15       Trench 1            NA                NA     NA
16       Trench 1            NA                NA     NA
17       Trench 1            NA                NA     NA
18       Trench 3            NA                NA     NA
19       Trench 3            NA                NA     NA

Data types:
Month                 object
scorename             object
DateCategory          object
psivalues            float64
account_count          int64
modelVersionId        object
trenchCategory        object
new_loan_type         object
loan_product_type     object
osType                object
dtype: object

In [90]:
print(f"The shape of the score_output_df is {score_output_df.shape}")
score_output_df['Model_Name'] = 'alpha_stack_model_cash'
score_output_df['scorename'] = score_output_df['scorename'].replace('score', 'alpha_stack_model_cash_score')
score_output_df

The shape of the score_output_df is (98, 10)

,Month,scorename,DateCategory,psivalues,account_count,modelVersionId,trenchCategory,new_loan_type,loan_product_type,osType,Model_Name
0,2025-09,alpha_stack_model_cash_score,Training,0.000000,129058,v1,NA,NA,NA,NA,alpha_stack_model_cash
1,2025-09,alpha_stack_model_cash_score,Monthly,0.573402,134,v1,NA,NA,NA,NA,alpha_stack_model_cash
2,2025-10,alpha_stack_model_cash_score,Monthly,0.133387,9210,v1,NA,NA,NA,NA,alpha_stack_model_cash
3,2025-11,alpha_stack_model_cash_score,Monthly,0.135991,18803,v1,NA,NA,NA,NA,alpha_stack_model_cash
4,2025-12,alpha_stack_model_cash_score,Monthly,0.138993,11761,v1,NA,NA,NA,NA,alpha_stack_model_cash
5,2026-01,alpha_stack_model_cash_score,Monthly,2.768859,1023,v1,NA,NA,NA,NA,alpha_stack_model_cash
6,2026-02,alpha_stack_model_cash_score,Monthly,2.254437,1361,v1,NA,NA,NA,NA,alpha_stack_model_cash
7,2026-03,alpha_stack_model_cash_score,Monthly,4.358015,25,v1,NA,NA,NA,NA,alpha_stack_model_cash
8,2025-09,alpha_stack_model_cash_score,Training,0.000000,42982,v1,Trench 2,NA,NA,NA,alpha_stack_model_cash
9,2025-09,alpha_stack_model_cash_score,Monthly,4.296736,31,v1,Trench 2,NA,NA,NA,alpha_stack_model_cash
10,2025-10,alpha_stack_model_cash_score,Monthly,0.340872,2355,v1,Trench 2,NA,NA,NA,alpha_stack_model_cash
11,2025-11,alpha_stack_model_cash_score,Monthly,0.306604,10225,v1,Trench 2,NA,NA,NA,alpha_stack_model_cash
12,2025-12,alpha_stack_model_cash_score,Monthly,0.322299,5907,v1,Trench 2,NA,NA,NA,alpha_stack_model_cash
13,2025-09,alpha_stack_model_cash_score,Training,0.000000,67807,v1,Trench 1,NA,NA,NA,alpha_stack_model_cash
14,2025-09,alpha_stack_model_cash_score,Monthly,2.304206,86,v1,Trench 1,NA,NA,NA,alpha_stack_model_cash
15,2025-10,alpha_stack_model_cash_score,Monthly,0.159201,6039,v1,Trench 1,NA,NA,NA,alpha_stack_model_cash
16,2025-11,alpha_stack_model_cash_score,Monthly,0.131975,7675,v1,Trench 1,NA,NA,NA,alpha_stack_model_cash
17,2025-12,alpha_stack_model_cash_score,Monthly,0.156285,4791,v1,Trench 1,NA,NA,NA,alpha_stack_model_cash
18,2025-09,alpha_stack_model_cash_score,Training,0.000000,18269,v1,Trench 3,NA,NA,NA,alpha_stack_model_cash
19,2025-09,alpha_stack_model_cash_score,Monthly,4.510130,17,v1,Trench 3,NA,NA,NA,alpha_stack_model_cash
20,2025-10,alpha_stack_model_cash_score,Monthly,0.546630,816,v1,Trench 3,NA,NA,NA,alpha_stack_model_cash
21,2025-11,alpha_stack_model_cash_score,Monthly,0.439744,903,v1,Trench 3,NA,NA,NA,alpha_stack_model_cash
22,2025-12,alpha_stack_model_cash_score,Monthly,0.304673,1063,v1,Trench 3,NA,NA,NA,alpha_stack_model_cash
23,2026-01,alpha_stack_model_cash_score,Monthly,0.304161,1023,v1,Trench 3,NA,NA,NA,alpha_stack_model_cash
24,2026-02,alpha_stack_model_cash_score,Monthly,0.028492,1361,v1,Trench 3,NA,NA,NA,alpha_stack_model_cash
25,2026-03,alpha_stack_model_cash_score,Monthly,2.324307,25,v1,Trench 3,NA,NA,NA,alpha_stack_model_cash
26,2025-09,alpha_stack_model_cash_score,Training,0.000000,42982,v1,Trench 2,Quick,NA,NA,alpha_stack_model_cash
27,2025-09,alpha_stack_model_cash_score,Monthly,4.296736,31,v1,Trench 2,Quick,NA,NA,alpha_stack_model_cash
28,2025-10,alpha_stack_model_cash_score,Monthly,0.340872,2355,v1,Trench 2,Quick,NA,NA,alpha_stack_model_cash
29,2025-11,alpha_stack_model_cash_score,Monthly,0.306604,10225,v1,Trench 2,Quick,NA,NA,alpha_stack_model_cash
30,2025-12,alpha_stack_model_cash_score,Monthly,0.322299,5907,v1,Trench 2,Quick,NA,NA,alpha_stack_model_cash
31,2025-09,alpha_stack_model_cash_score,Training,0.000000,67807,v1,Trench 1,Quick,NA,NA,alpha_stack_model_cash
32,2025-09,alpha_stack_model_cash_score,Monthly,2.304206,86,v1,Trench 1,Quick,NA,NA,alpha_stack_model_cash
33,2025-10,alpha_stack_model_cash_score,Monthly,0.159201,6039,v1,Trench 1,Quick,NA,NA,alpha_stack_model_cash
34,2025-11,alpha_stack_model_cash_score,Monthly,0.131975,7675,v1,Trench 1,Quick,NA,NA,alpha_stack_model_cash
35,2025-12,alpha_stack_model_cash_score,Monthly,0.156285,4791,v1,Trench 1,Quick,NA,NA,alpha_stack_model_cash
36,2025-09,alpha_stack_model_cash_score,Training,0.000000,18269,v1,Trench 3,Quick,NA,NA,alpha_stack_model_cash
37,2025-09,alpha_stack_model_cash_score,Monthly,4.510130,17,v1,Trench 3,Quick,NA,NA,alpha_stack_model_cash
38,2025-10,alpha_stack_model_cash_score,Monthly,0.546630,816,v1,Trench 3,Quick,NA,NA,alpha_stack_model_cash
39,2025-11,alpha_stack_model_cash_score,Monthly,0.439744,903,v1,Trench 3,Quick,NA,NA,alpha_stack_model_cash
40,2025-12,alpha_stack_model_cash_score,Monthly,0.304673,1063,v1,Trench 3,Quick,NA,NA,alpha_stack_model_cash
41,2026-01,alpha_stack_model_cash_score,Monthly,0.304161,1023,v1,Trench 3,Quick,NA,NA,alpha_stack_model_cash
42,2026-02,alpha_stack_model_cash_score,Monthly,0.028492,1361,v1,Trench 3,Quick,NA,NA,alpha_stack_model_cash
43,2026-03,alpha_stack_model_cash_score,Monthly,2.324307,25,v1,Trench 3,Quick,NA,NA,alpha_stack_model_cash
44,2025-09,alpha_stack_model_cash_score,Training,0.000000,42982,v1,Trench 2,Quick,not applicable,NA,alpha_stack_model_cash
45,2025-09,alpha_stack_model_cash_score,Monthly,4.296736,31,v1,Trench 2,Quick,not applicable,NA,alpha_stack_model_cash
46,2025-10,alpha_stack_model_cash_score,Monthly,0.340872,2355,v1,Trench 2,Quick,not applicable,NA,alpha_stack_model_cash
47,2025-11,alpha_stack_model_cash_score,Monthly,0.306604,10225,v1,Trench 2,Quick,not applicable,NA,alpha_stack_model_cash
48,2025-12,alpha_stack_model_cash_score,Monthly,0.322299,5907,v1,Trench 2,Quick,not applicable,NA,alpha_stack_model_cash
49,2025-09,alpha_stack_model_cash_score,Training,0.000000,67807,v1,Trench 1,Quick,not applicable,NA,alpha_stack_model_cash
50,2025-09,alpha_stack_model_cash_score,Monthly,2.304206,86,v1,Trench 1,Quick,not applicable,NA,alpha_stack_model_cash
51,2025-10,alpha_stack_model_cash_score,Monthly,0.159201,6039,v1,Trench 1,Quick,not applicable,NA,alpha_stack_model_cash
52,2025-11,alpha_stack_model_cash_score,Monthly,0.131975,7675,v1,Trench 1,Quick,not applicable,NA,alpha_stack_model_cash
53,2025-12,alpha_stack_model_cash_score,Monthly,0.156285,4791,v1,Trench 1,Quick,not applicable,NA,alpha_stack_model_cash
54,2025-09,alpha_stack_model_cash_score,Training,0.000000,18269,v1,Trench 3,Quick,not applicable,NA,alpha_stack_model_cash
55,2025-09,alpha_stack_model_cash_score,Monthly,4.510130,17,v1,Trench 3,Quick,not applicable,NA,alpha_stack_model_cash
56,2025-10,alpha_stack_model_cash_score,Monthly,0.546630,816,v1,Trench 3,Quick,not applicable,NA,alpha_stack_model_cash
57,2025-11,alpha_stack_model_cash_score,Monthly,0.439744,903,v1,Trench 3,Quick,not applicable,NA,alpha_stack_model_cash
58,2025-12,alpha_stack_model_cash_score,Monthly,0.304673,1063,v1,Trench 3,Quick,not applicable,NA,alpha_stack_model_cash
59,2026-01,alpha_stack_model_cash_score,Monthly,0.304161,1023,v1,Trench 3,Quick,not applicable,NA,alpha_stack_model_cash
60,2026-02,alpha_stack_model_cash_score,Monthly,0.028492,1361,v1,Trench 3,Quick,not applicable,NA,alpha_stack_model_cash
61,2026-03,alpha_stack_model_cash_score,Monthly,2.324307,25,v1,Trench 3,Quick,not applicable,NA,alpha_stack_model_cash
62,2025-09,alpha_stack_model_cash_score,Training,0.000000,24489,v1,Trench 2,Quick,not applicable,android,alpha_stack_model_cash
63,2025-09,alpha_stack_model_cash_score,Monthly,8.640981,20,v1,Trench 2,Quick,not applicable,android,alpha_stack_model_cash
64,2025-10,alpha_stack_model_cash_score,Monthly,2.204641,1489,v1,Trench 2,Quick,not applicable,android,alpha_stack_model_cash
65,2025-11,alpha_stack_model_cash_score,Monthly,2.205032,6018,v1,Trench 2,Quick,not applicable,android,alpha_stack_model_cash
66,2025-12,alpha_stack_model_cash_score,Monthly,2.268771,3653,v1,Trench 2,Quick,not applicable,android,alpha_stack_model_cash
67,2025-09,alpha_stack_model_cash_score,Training,0.000000,18493,v1,Trench 2,Quick,not applicable,ios,alpha_stack_model_cash
68,2025-09,alpha_stack_model_cash_score,Monthly,8.879556,11,v1,Trench 2,Quick,not applicable,ios,alpha_stack_model_cash
69,2025-10,alpha_stack_model_cash_score,Monthly,0.125652,866,v1,Trench 2,Quick,not applicable,ios,alpha_stack_model_cash
70,2025-11,alpha_stack_model_cash_score,Monthly,0.061966,4207,v1,Trench 2,Quick,not applicable,ios,alpha_stack_model_cash
71,2025-12,alpha_stack_model_cash_score,Monthly,0.088695,2254,v1,Trench 2,Quick,not applicable,ios,alpha_stack_model_cash
72,2025-09,alpha_stack_model_cash_score,Training,0.000000,31164,v1,Trench 1,Quick,not applicable,android,alpha_stack_model_cash
73,2025-09,alpha_stack_model_cash_score,Monthly,2.565897,58,v1,Trench 1,Quick,not applicable,android,alpha_stack_model_cash
74,2025-10,alpha_stack_model_cash_score,Monthly,2.236943,3861,v1,Trench 1,Quick,not applicable,android,alpha_stack_model_cash
75,2025-11,alpha_stack_model_cash_score,Monthly,2.207375,4791,v1,Trench 1,Quick,not applicable,android,alpha_stack_model_cash
76,2025-12,alpha_stack_model_cash_score,Monthly,2.218864,3500,v1,Trench 1,Quick,not applicable,android,alpha_stack_model_cash
77,2025-09,alpha_stack_model_cash_score,Training,0.000000,36643,v1,Trench 1,Quick,not applicable,ios,alpha_stack_model_cash
78,2025-09,alpha_stack_model_cash_score,Monthly,7.008960,28,v1,Trench 1,Quick,not applicable,ios,alpha_stack_model_cash
79,2025-10,alpha_stack_model_cash_score,Monthly,0.084538,2178,v1,Trench 1,Quick,not applicable,ios,alpha_stack_model_cash
80,2025-11,alpha_stack_model_cash_score,Monthly,0.030836,2884,v1,Trench 1,Quick,not applicable,ios,alpha_stack_model_cash
81,2025-12,alpha_stack_model_cash_score,Monthly,0.050058,1291,v1,Trench 1,Quick,not applicable,ios,alpha_stack_model_cash
82,2025-09,alpha_stack_model_cash_score,Training,0.000000,10465,v1,Trench 3,Quick,not applicable,android,alpha_stack_model_cash
83,2025-09,alpha_stack_model_cash_score,Monthly,13.140106,7,v1,Trench 3,Quick,not applicable,android,alpha_stack_model_cash
84,2025-10,alpha_stack_model_cash_score,Monthly,2.453639,484,v1,Trench 3,Quick,not applicable,android,alpha_stack_model_cash
85,2025-11,alpha_stack_model_cash_score,Monthly,2.387098,540,v1,Trench 3,Quick,not applicable,android,alpha_stack_model_cash
86,2025-12,alpha_stack_model_cash_score,Monthly,2.306285,640,v1,Trench 3,Quick,not applicable,android,alpha_stack_model_cash
87,2026-01,alpha_stack_model_cash_score,Monthly,0.571480,640,v1,Trench 3,Quick,not applicable,android,alpha_stack_model_cash
88,2026-02,alpha_stack_model_cash_score,Monthly,0.074245,774,v1,Trench 3,Quick,not applicable,android,alpha_stack_model_cash
89,2026-03,alpha_stack_model_cash_score,Monthly,2.252158,14,v1,Trench 3,Quick,not applicable,android,alpha_stack_model_cash
90,2025-09,alpha_stack_model_cash_score,Training,0.000000,7804,v1,Trench 3,Quick,not applicable,ios,alpha_stack_model_cash
91,2025-09,alpha_stack_model_cash_score,Monthly,6.505706,10,v1,Trench 3,Quick,not applicable,ios,alpha_stack_model_cash
92,2025-10,alpha_stack_model_cash_score,Monthly,0.298518,332,v1,Trench 3,Quick,not applicable,ios,alpha_stack_model_cash
93,2025-11,alpha_stack_model_cash_score,Monthly,0.321658,363,v1,Trench 3,Quick,not applicable,ios,alpha_stack_model_cash
94,2025-12,alpha_stack_model_cash_score,Monthly,0.258903,423,v1,Trench 3,Quick,not applicable,ios,alpha_stack_model_cash
95,2026-01,alpha_stack_model_cash_score,Monthly,0.277470,383,v1,Trench 3,Quick,not applicable,ios,alpha_stack_model_cash
96,2026-02,alpha_stack_model_cash_score,Monthly,0.096791,587,v1,Trench 3,Quick,not applicable,ios,alpha_stack_model_cash
97,2026-03,alpha_stack_model_cash_score,Monthly,6.610318,11,v1,Trench 3,Quick,not applicable,ios,alpha_stack_model_cash

In [91]:
psi_results = score_output_df.copy()
# Upload to BigQuery
table_id = "prj-prod-dataplatform.dap_ds_poweruser_playground.alpha_cash_stack_model_psi_v7"
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",  # or "WRITE_APPEND"
)
job = client.load_table_from_dataframe(psi_results, table_id, job_config=job_config)
job.result()  # Wait for the job to complete

C:\Users\Dwaipayan\AppData\Roaming\Python\Python312\site-packages\google\cloud\bigquery\_pandas_helpers.py:483: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=prj-prod-dataplatform, location=asia-southeast1, id=d24f97be-fe6e-4b46-8028-6177382ce944>

### Beta-Cash-Demo-Model

#### Test

In [92]:
sq = """
WITH parsed as (
select customerId, digitalLoanAccountId,
case when modelDisplayName in ('Beta-Cash-Demo-Model') then 'beta_demo_model_cash' else modelDisplayName end modelDisplayName,
modelVersionId,
start_time,
end_time,
prediction,
   case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeatures,
FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
where modelDisplayName in ('Beta-Cash-Demo-Model', 'beta_demo_model_cash')
),
base as
(select 
 r.customerId,r.digitalLoanAccountId
 ,start_time,end_time,  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'Cash' as product,
 'beta_demo_model_cash' Model_Name,
  trenchCategory,
   'Test' Data_selection,
  calcFeatures,
  prediction score,
  coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time)) as Application_month, 
from parsed r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid order by cast(start_time as datetime) desc) = 1
)
select * from base where lower(new_loan_type) not like '%sil%'
;
"""
dfd= client.query(sq).to_dataframe(progress_bar_type='tqdm')
dfd.head()

Job ID 915855a8-dbe2-4e89-a3f1-ae864eff3aa4 successfully executed: 100%|██████████|
Downloading: 100%|██████████|

,customerId,digitalLoanAccountId,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,score,appln_submit_datetime,disbursementDateTime,Application_month
0,1020427,11d7d231-a26c-4b62-aca1-f634ad557dc6,2026-02-17 15:13:13.303223,2026-02-17 15:13:14.885594,beta_demo_model_cash,v1,Quick,F,not applicable,android,Cash,beta_demo_model_cash,Trench 2,Test,"{""ln_vas_opted_flag"": 0, ""ln_self_dec_income"":...",0.5224440889583156,2026-02-17 23:13:10,NaT,2026-02
1,1021059,c5563e41-90d8-49c9-9644-90db0fd22bb1,2025-12-09 16:41:09.864665,2025-12-09 16:41:10.400832,beta_demo_model_cash,v1,Quick,F,not applicable,ios,Cash,beta_demo_model_cash,Trench 2,Test,"{""ln_vas_opted_flag"": 1, ""ln_self_dec_income"":...",0.6624425777692581,2025-12-10 00:41:06,NaT,2025-12
2,1021333,344114a3-b85a-443a-9603-5d198b39fcfa,2026-01-03 19:34:03.582325,2026-01-03 19:34:04.223574,beta_demo_model_cash,v1,Quick,F,not applicable,ios,Cash,beta_demo_model_cash,Trench 2,Test,"{""ln_vas_opted_flag"": 1, ""ln_self_dec_income"":...",0.5796909206055453,2026-01-04 03:33:59,NaT,2026-01
3,1024345,698b3f30-e868-4344-b76a-ac23d13eb759,2026-01-13 18:59:43.503839,2026-01-13 18:59:44.111483,beta_demo_model_cash,v1,Quick,F,not applicable,ios,Cash,beta_demo_model_cash,Trench 2,Test,"{""ln_vas_opted_flag"": 0, ""ln_self_dec_income"":...",0.37859559137776166,2026-01-14 02:59:38,NaT,2026-01
4,1038808,996f8341-a23a-49af-a4dc-efdc9d1c0c65,2025-11-29 06:28:36.212082,2025-11-29 06:28:36.830652,beta_demo_model_cash,v1,Quick,M,not applicable,ios,Cash,beta_demo_model_cash,Trench 2,Test,"{""ln_vas_opted_flag"": 1, ""ln_self_dec_income"":...",0.5927838714573406,2025-11-29 14:28:33,NaT,2025-11

In [93]:
df1 = dfd.copy()

#### Train

In [94]:
sq = """
WITH parsed as (
select customerId, digitalLoanAccountId,
case when modelDisplayName in ('Beta-Cash-Demo-Model') then 'beta_demo_model_cash' else modelDisplayName end modelDisplayName,
modelVersionId,
start_time,
end_time,
prediction,
   case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeatures,
FROM prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
where modelDisplayName in ('Beta-Cash-Demo-Model', 'beta_demo_model_cash')
),
base as
(select 
 r.customerId,r.digitalLoanAccountId,prediction 
 ,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'Cash' as product,
 'beta_demo_model_cash' Model_Name,
  trenchCategory,
   'Train' Data_selection,
  calcFeatures,
  prediction score,
  IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m',IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime)) as Application_month, 
from parsed r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid order by cast(start_time as datetime) desc) = 1
)
select * from base where lower(new_loan_type) not like '%sil%'
;
"""

dfd = client.query(sq).to_dataframe(progress_bar_type='tqdm')
dfd.head()

Job ID da21e416-6211-42ca-ab08-3450baed98bb successfully executed: 100%|██████████|
Downloading: 100%|██████████|

,customerId,digitalLoanAccountId,prediction,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,score,appln_submit_datetime,disbursementDateTime,Application_month
0,1007650,1aa9bcf2-7a3a-4c2d-a80e-5c2925b002eb,0.556992,2025-12-23T22:25:04.537124,2025-12-23T22:25:04.537124,beta_demo_model_cash,v1,Quick,M,not applicable,android,Cash,beta_demo_model_cash,Trench 2,Train,"{""ln_vas_opted_flag"": ""1"", ""ln_self_dec_income...",0.556992,2025-02-12 08:39:59,2025-02-12 08:51:22,2025-02
1,1011027,0ff80d8c-4249-4ca5-92a0-92cad9965611,0.278479,2025-12-23T22:25:06.637979,2025-12-23T22:25:06.637979,beta_demo_model_cash,v1,Quick,M,not applicable,ios,Cash,beta_demo_model_cash,Trench 2,Train,"{""ln_vas_opted_flag"": ""0"", ""ln_self_dec_income...",0.278479,2025-08-15 21:33:24,NaT,2025-08
2,1016678,70c7a82b-f031-41f8-8d41-408107251c84,0.482508,2025-12-23T22:25:05.600661,2025-12-23T22:25:05.600661,beta_demo_model_cash,v1,Quick,F,not applicable,android,Cash,beta_demo_model_cash,Trench 2,Train,"{""ln_vas_opted_flag"": ""0"", ""ln_self_dec_income...",0.482508,2025-09-17 19:46:44,NaT,2025-09
3,1021339,3e4cd47a-0548-4b4a-90e7-40f597b28147,0.504683,2025-12-23T22:25:09.490969,2025-12-23T22:25:09.490969,beta_demo_model_cash,v1,Quick,M,not applicable,android,Cash,beta_demo_model_cash,Trench 2,Train,"{""ln_vas_opted_flag"": ""1"", ""ln_self_dec_income...",0.504683,2024-11-22 10:43:52,NaT,2024-11
4,1024793,f96e9cb6-84c6-4b64-9d5a-adf5512bb754,0.618878,2025-12-23T22:25:04.820827,2025-12-23T22:25:04.820827,beta_demo_model_cash,v1,Quick,F,not applicable,android,Cash,beta_demo_model_cash,Trench 2,Train,"{""ln_vas_opted_flag"": ""1"", ""ln_self_dec_income...",0.618878,2025-06-26 14:54:22,2025-06-27 03:25:06,2025-06

In [95]:
df2 = dfd.copy()

In [96]:
df_concat = pd.concat([df1, df2], ignore_index=True)
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")

The shape of the concatenated dataframe is: (817167, 20)

In [97]:
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")
df_combined = dropping_duplicates(df_concat)
print(f"The shape of the dataframe after dropping duplicates is: {df_combined.shape}")

The shape of the concatenated dataframe is: (817167, 20)
The shape of the dataframe after dropping duplicates is: (817167, 20)

In [98]:
df_combined['score'] = pd.to_numeric(df_combined['score'], errors='coerce')

In [99]:
df_combined.sample(10)

,customerId,digitalLoanAccountId,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,score,appln_submit_datetime,disbursementDateTime,Application_month,prediction
600244,3536016,dfefc500-5608-4c0c-abd7-c6498504bb13,2025-12-23T22:23:53.849643,2025-12-23T22:23:53.849643,beta_demo_model_cash,v1,Quick,F,not applicable,android,Cash,beta_demo_model_cash,Trench 1,Train,"{""ln_vas_opted_flag"": ""1"", ""ln_self_dec_income...",0.495900,2025-07-18 05:23:49,NaT,2025-07,0.495900
269649,4019601,68880b1c-12db-4469-8542-cdcc39b8ba55,2026-01-18 05:32:51.300349,2026-01-18 05:32:51.897250,beta_demo_model_cash,v1,Quick,M,not applicable,android,Cash,beta_demo_model_cash,Trench 1,Test,"{""ln_vas_opted_flag"": 1, ""ln_self_dec_income"":...",0.576997,2026-01-18 13:32:42,2026-01-18 14:01:53,2026-01,NaN
188904,4136195,c2f24b7e-9874-481e-ad0b-26ad0882a278,2026-02-23 09:23:02.864647,2026-02-23 09:23:02.986914,beta_demo_model_cash,v1,Quick,F,not applicable,ios,Cash,beta_demo_model_cash,Trench 1,Test,"{""ln_vas_opted_flag"": 1, ""ln_self_dec_income"":...",0.557100,2026-02-23 17:22:56,NaT,2026-02,NaN
559095,3071760,6b53ffb7-65ee-4e22-aa6c-d6045936238d,2025-12-23T22:25:05.240978,2025-12-23T22:25:05.240978,beta_demo_model_cash,v1,Quick,F,not applicable,android,Cash,beta_demo_model_cash,Trench 2,Train,"{""ln_vas_opted_flag"": ""1"", ""ln_self_dec_income...",0.616096,2025-04-03 00:38:07,NaT,2025-04,0.616096
104742,3334574,81fe2cc6-ac9e-4745-b255-33dd44ec7f97,2025-11-29 07:33:49.849896,2025-11-29 07:33:50.685616,beta_demo_model_cash,v1,Quick,M,not applicable,android,Cash,beta_demo_model_cash,Trench 3,Test,"{""ln_vas_opted_flag"": 0, ""ln_self_dec_income"":...",0.481183,2025-11-29 15:33:46,NaT,2025-11,NaN
323281,3415597,ff4e63d9-ec7c-4f23-9892-28c20adaece6,2025-10-17 06:45:31.312175,2025-10-17 06:45:32.139170,beta_demo_model_cash,v1,Quick,F,not applicable,android,Cash,beta_demo_model_cash,Trench 2,Test,"{""ln_vas_opted_flag"": 1, ""ln_self_dec_income"":...",0.623306,2025-10-17 14:45:26,NaT,2025-10,NaN
326607,2706817,afa97b99-5d3a-418e-9584-29f416529195,2025-12-23T22:24:57.269851,2025-12-23T22:24:57.269851,beta_demo_model_cash,v1,Quick,M,not applicable,ios,Cash,beta_demo_model_cash,Trench 2,Train,"{""ln_vas_opted_flag"": ""1"", ""ln_self_dec_income...",0.624577,2024-11-28 23:54:41,NaT,2024-11,0.624577
553952,3021341,29553b6c-a844-439a-868d-56a109e9788a,2025-12-23T22:25:07.716132,2025-12-23T22:25:07.716132,beta_demo_model_cash,v1,Quick,M,not applicable,android,Cash,beta_demo_model_cash,Trench 2,Train,"{""ln_vas_opted_flag"": ""1"", ""ln_self_dec_income...",0.648503,2025-03-31 09:49:43,NaT,2025-03,0.648503
534544,3067435,affa7a8e-7236-40ae-9a0c-6cbd3a6838fd,2025-12-23T22:24:24.349911,2025-12-23T22:24:24.349911,beta_demo_model_cash,v1,Quick,M,not applicable,ios,Cash,beta_demo_model_cash,Trench 1,Train,"{""ln_vas_opted_flag"": ""1"", ""ln_self_dec_income...",0.583133,2024-11-30 17:02:47,NaT,2024-11,0.583133
805200,3235697,cf8f2663-8f9a-4a73-aac4-494edbc8b0f2,2025-12-23T22:24:20.253587,2025-12-23T22:24:20.253587,beta_demo_model_cash,v1,Quick,F,not applicable,ios,Cash,beta_demo_model_cash,Trench 1,Train,"{""ln_vas_opted_flag"": ""1"", ""ln_self_dec_income...",0.569750,2025-02-03 19:54:51,NaT,2025-02,0.569750

### PSI calculation

In [100]:
score_output_df = calculate_psi_with_segments(
    df=df_combined,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
)

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

print(f"Output shape: {score_output_df.shape}")
print(f"\nOutput columns: {score_output_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(score_output_df.head(20))
print(f"\nData types:")
print(score_output_df.dtypes)

Output shape: (133, 10)

Output columns: ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count', 'modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']

First few rows:
      Month scorename DateCategory  psivalues  account_count modelVersionId  \
0   2025-10     score     Training   0.000000         491421             v1
1   2025-02     score      Monthly  20.713669              1             v1
2   2025-09     score      Monthly   0.020071            803             v1
3   2025-10     score      Monthly   0.003881          35272             v1
4   2025-11     score      Monthly   0.016022          58553             v1
5   2025-12     score      Monthly   0.021845          96115             v1
6   2026-01     score      Monthly   0.004770          75429             v1
7   2026-02     score      Monthly   0.005705          58406             v1
8   2026-03     score      Monthly   0.024460           1167             v1
9   2025-10     score     Training   0.000000         324441             v1
10  2025-09     score      Monthly   0.032080            578             v1
11  2025-10     score      Monthly   0.005630          24909             v1
12  2025-11     score      Monthly   0.012271          26229             v1
13  2025-12     score      Monthly   0.037068          41543             v1
14  2026-01     score      Monthly   0.011274          56721             v1
15  2026-02     score      Monthly   0.009653          42216             v1
16  2026-03     score      Monthly   0.036938            866             v1
17  2025-10     score     Training   0.000000         124539             v1
18  2025-02     score      Monthly  20.713979              1             v1
19  2025-09     score      Monthly   0.070085            164             v1

   trenchCategory new_loan_type loan_product_type osType
0              NA            NA                NA     NA
1              NA            NA                NA     NA
2              NA            NA                NA     NA
3              NA            NA                NA     NA
4              NA            NA                NA     NA
5              NA            NA                NA     NA
6              NA            NA                NA     NA
7              NA            NA                NA     NA
8              NA            NA                NA     NA
9        Trench 1            NA                NA     NA
10       Trench 1            NA                NA     NA
11       Trench 1            NA                NA     NA
12       Trench 1            NA                NA     NA
13       Trench 1            NA                NA     NA
14       Trench 1            NA                NA     NA
15       Trench 1            NA                NA     NA
16       Trench 1            NA                NA     NA
17       Trench 2            NA                NA     NA
18       Trench 2            NA                NA     NA
19       Trench 2            NA                NA     NA

Data types:
Month                 object
scorename             object
DateCategory          object
psivalues            float64
account_count          int64
modelVersionId        object
trenchCategory        object
new_loan_type         object
loan_product_type     object
osType                object
dtype: object

In [101]:
print(f"The shape of the score_output_df is {score_output_df.shape}")
score_output_df['Model_Name'] = 'beta_demo_model_cash'
score_output_df['scorename'] = score_output_df['scorename'].replace('score', 'beta_demo_model_cash_score')
score_output_df

The shape of the score_output_df is (133, 10)

,Month,scorename,DateCategory,psivalues,account_count,modelVersionId,trenchCategory,new_loan_type,loan_product_type,osType,Model_Name
0,2025-10,beta_demo_model_cash_score,Training,0.000000,491421,v1,NA,NA,NA,NA,beta_demo_model_cash
1,2025-02,beta_demo_model_cash_score,Monthly,20.713669,1,v1,NA,NA,NA,NA,beta_demo_model_cash
2,2025-09,beta_demo_model_cash_score,Monthly,0.020071,803,v1,NA,NA,NA,NA,beta_demo_model_cash
3,2025-10,beta_demo_model_cash_score,Monthly,0.003881,35272,v1,NA,NA,NA,NA,beta_demo_model_cash
4,2025-11,beta_demo_model_cash_score,Monthly,0.016022,58553,v1,NA,NA,NA,NA,beta_demo_model_cash
...,...,...,...,...,...,...,...,...,...,...,...
128,2025-11,beta_demo_model_cash_score,Monthly,0.013132,1000,v1,Trench 3,Quick,not applicable,ios,beta_demo_model_cash
129,2025-12,beta_demo_model_cash_score,Monthly,0.039445,1478,v1,Trench 3,Quick,not applicable,ios,beta_demo_model_cash
130,2026-01,beta_demo_model_cash_score,Monthly,0.039550,933,v1,Trench 3,Quick,not applicable,ios,beta_demo_model_cash
131,2026-02,beta_demo_model_cash_score,Monthly,0.019092,852,v1,Trench 3,Quick,not applicable,ios,beta_demo_model_cash
132,2026-03,beta_demo_model_cash_score,Monthly,6.688439,18,v1,Trench 3,Quick,not applicable,ios,beta_demo_model_cash

In [102]:
psi_results = score_output_df.copy()
table_id = "prj-prod-dataplatform.dap_ds_poweruser_playground.beta_cash_demo_model_psi_v7"
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",  # or "WRITE_APPEND"
)
job = client.load_table_from_dataframe(psi_results, table_id, job_config=job_config)
job.result()

C:\Users\Dwaipayan\AppData\Roaming\Python\Python312\site-packages\google\cloud\bigquery\_pandas_helpers.py:483: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=prj-prod-dataplatform, location=asia-southeast1, id=b06c627b-7120-42ce-8e80-7db9597dba01>

### Beta-Cash-AppScore-Model

#### Test

In [103]:
sq = """WITH parsed as (
select customerId, digitalLoanAccountId,
case when modelDisplayName in ('Beta-Cash-AppScore-Model') then 'apps_score_cash' else modelDisplayName end as modelDisplayName,
modelVersionId,start_time,end_time,
prediction,
case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeatures,
REPLACE(REPLACE(prediction, "'", '"'), "None", "null") AS prediction_clean
FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
where modelDisplayName in  ('Beta-Cash-AppScore-Model', 'apps_score_cash')
),
base as
(select 
 r.customerId,r.digitalLoanAccountId
 ,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type ,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'Cash' as product,
 'apps_score_cash' Model_Name,
  trenchCategory,
   'Test' Data_selection,
  calcFeatures,
  SAFE_CAST(JSON_VALUE(r.prediction_clean, "$.combined_score") AS Float64) AS score,
  coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time)) as Application_month, 
from parsed r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid order by cast(start_time as datetime) desc) = 1
)
select * from base where lower(new_loan_type) not like '%sil%'
;"""

dfd = client.query(sq).to_dataframe(progress_bar_type='tqdm')
dfd.head()

Job ID 9fc3c3f4-1ef8-4dc0-a6d8-3a00ac1a03e7 successfully executed: 100%|██████████|
Downloading: 100%|██████████|

,customerId,digitalLoanAccountId,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,score,appln_submit_datetime,disbursementDateTime,Application_month
0,1048719,cb5e212d-2b38-4834-b4fc-f91d66266a37,2025-10-13 21:07:43.861219,2025-10-13 21:07:44.649847,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 2,Test,"{""app_cnt_health_and_fitness_ever"": 0, ""app_cn...",0.429959,2025-10-14 05:07:40,2025-10-14 14:45:58,2025-10
1,1049753,ea86e003-f4c1-4c7e-95c1-8aea2496e7e1,2025-12-16 03:47:58.736677,2025-12-16 03:47:59.743291,apps_score_cash,v1.1,Quick,F,not applicable,android,Cash,apps_score_cash,Trench 2,Test,"{""app_cnt_rated_for_18plus_ever"": 0, ""app_cnt_...",0.473642,2025-12-16 11:47:54,2025-12-18 10:48:42,2025-12
2,1066929,6f488b4b-bb82-435f-9948-4b28dcd95956,2025-11-19 03:49:30.071541,2025-11-19 03:49:30.878118,apps_score_cash,v1,Quick,F,not applicable,android,Cash,apps_score_cash,Trench 2,Test,"{""app_cnt_health_and_fitness_ever"": 1, ""app_cn...",0.525848,2025-11-19 11:49:25,NaT,2025-11
3,1067190,22429801-26a5-4f95-a248-c58c2a3d804c,2025-12-14 10:57:17.023330,2025-12-14 10:57:17.932120,apps_score_cash,v1.1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 2,Test,"{""app_cnt_rated_for_18plus_ever"": 0, ""app_cnt_...",0.473923,2025-12-14 18:57:11,NaT,2025-12
4,1079945,1622fe82-5cf5-452b-9c02-96e683b90887,2025-11-29 19:10:32.539423,2025-11-29 19:10:33.258330,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 2,Test,"{""app_cnt_health_and_fitness_ever"": 1, ""app_cn...",0.547946,2025-11-30 03:10:29,NaT,2025-11

In [104]:
df1 = dfd.copy()

#### Train

In [105]:
sq = """ 
WITH parsed as (
select customerId, digitalLoanAccountId,
case when modelDisplayName in  ('Beta-Cash-AppScore-Model') then 'apps_score_cash' else modelDisplayName end as modelDisplayName,
modelVersionId,start_time,end_time,prediction,
   case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeatures,
FROM prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
where modelDisplayName in  ('Beta-Cash-AppScore-Model', 'apps_score_cash')
),
base as
(select 
 r.customerId,r.digitalLoanAccountId,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type ,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'Cash' as product,
 'apps_score_cash' Model_Name,
  trenchCategory,
   'Train' Data_selection,
  calcFeatures,
  prediction score,
  IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m',IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime)) as Application_month, 
from parsed r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid order by cast(start_time as datetime) desc) = 1
)
select * from base where lower(new_loan_type) not like '%sil%'
"""

dfd = client.query(sq).to_dataframe(progress_bar_type='tqdm')
dfd.head()

Job ID 4188ff68-4c5e-4613-82a9-e97e55a37154 successfully executed: 100%|██████████|
Downloading: 100%|██████████|

,customerId,digitalLoanAccountId,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,score,appln_submit_datetime,disbursementDateTime,Application_month
0,1011039,33f1e12e-0fef-489e-a61d-302aeb20e3a2,2025-12-23T22:27:52.515500,2025-12-23T22:27:52.515500,apps_score_cash,v1,Quick,F,not applicable,android,Cash,apps_score_cash,Trench 2,Train,"{""beta_cash_app_score"": 0.40736195997096203, ""...",0.407362,2025-01-07 07:59:26,NaT,2025-01
1,1023915,3f92ad5d-97b7-4fbf-a7f4-f38a0f184276,2025-12-23T22:27:52.576053,2025-12-23T22:27:52.576053,apps_score_cash,v1,Quick,F,not applicable,android,Cash,apps_score_cash,Trench 2,Train,"{""beta_cash_app_score"": 0.5130389752995737, ""a...",0.513039,2024-08-16 14:30:12,NaT,2024-08
2,1029583,b4645c03-9f42-435c-9bba-ef6c9350034a,2025-12-23T22:27:46.345756,2025-12-23T22:27:46.345756,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 2,Train,"{""beta_cash_app_score"": 0.3193252182138878, ""a...",0.319325,2024-11-27 17:29:56,NaT,2024-11
3,1037812,59ec308d-0436-4865-9d27-79a12d48540f,2025-12-23T22:27:52.683233,2025-12-23T22:27:52.683233,apps_score_cash,v1,Quick,F,not applicable,android,Cash,apps_score_cash,Trench 2,Train,"{""beta_cash_app_score"": 0.3662211934607458, ""a...",0.366221,2024-09-24 12:08:29,2024-09-24 13:31:59,2024-09
4,1045104,66cacb5c-e266-4ab3-9fec-fb04391b2859,2025-12-23T22:27:48.125493,2025-12-23T22:27:48.125493,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 2,Train,"{""beta_cash_app_score"": 0.5982586742667514, ""a...",0.598259,2024-08-19 21:14:03,2024-08-22 06:56:18,2024-08

In [106]:
df2 = dfd.copy()

In [107]:
df_concat = pd.concat([df1, df2], ignore_index=True)
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")

The shape of the concatenated dataframe is: (650487, 19)

In [108]:
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")
df_combined = dropping_duplicates(df_concat)
print(f"The shape of the dataframe after dropping duplicates is: {df_combined.shape}")

The shape of the concatenated dataframe is: (650487, 19)
The shape of the dataframe after dropping duplicates is: (650487, 19)

In [109]:
df_combined['score'] = pd.to_numeric(df_combined['score'], errors='coerce')

In [110]:
df_combined.sample(10)

,customerId,digitalLoanAccountId,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,score,appln_submit_datetime,disbursementDateTime,Application_month
512279,3595718,51eb493e-d461-4e66-9ea8-c609bd4c0fda,2025-12-23T22:27:07.206909,2025-12-23T22:27:07.206909,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 1,Train,"{""beta_cash_app_score"": 0.4861470112556753, ""a...",0.486147,2025-08-08 23:42:31,NaT,2025-08
649543,3364496,2c3c498f-4f8e-432c-893f-d8bde4e78206,2025-12-23T22:27:02.397467,2025-12-23T22:27:02.397467,apps_score_cash,v1,Quick,F,not applicable,android,Cash,apps_score_cash,Trench 1,Train,"{""beta_cash_app_score"": 0.6610660510993256, ""a...",0.661066,2025-04-07 07:40:56,NaT,2025-04
4110,3992335,ec3b83fc-624e-47a7-aaf5-5557caa025de,2026-01-10 09:14:14.174036,2026-01-10 09:14:14.803898,apps_score_cash,v1.1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 1,Test,"{""app_cnt_rated_for_18plus_ever"": 1, ""app_cnt_...",0.591984,2026-01-10 17:14:10,NaT,2026-01
584015,3137486,5c53269f-dfad-4b3e-a743-80a3b82a5e7e,2025-12-23T22:27:18.156575,2025-12-23T22:27:18.156575,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 1,Train,"{""beta_cash_app_score"": 0.5340564567212488, ""a...",0.534056,2024-12-25 12:48:32,NaT,2024-12
501098,2629584,61ca6638-6b9d-4c93-bc09-d7a62015cb37,2025-12-23T22:28:12.707150,2025-12-23T22:28:12.707150,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 3,Train,"{""beta_cash_app_score"": 0.43497726261135383, ""...",0.434977,2025-01-30 09:12:59,NaT,2025-01
301389,1510105,ee7796de-9c56-47d3-888d-874c97815fb4,2025-12-23T22:27:43.177850,2025-12-23T22:27:43.177850,apps_score_cash,v1,Quick,F,not applicable,android,Cash,apps_score_cash,Trench 2,Train,"{""beta_cash_app_score"": 0.5475456929961895, ""a...",0.547546,2025-01-19 17:51:09,NaT,2025-01
448386,2785795,a6a3f68f-e17b-4518-a0a3-c2a0c7f4b806,2025-12-23T22:27:01.685975,2025-12-23T22:27:01.685975,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 1,Train,"{""beta_cash_app_score"": 0.5938468681859459, ""a...",0.593847,2024-08-24 07:26:18,NaT,2024-08
305831,2442175,c11ec0b1-994f-43b6-beb3-995cec672e74,2025-12-23T22:27:52.995143,2025-12-23T22:27:52.995143,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 2,Train,"{""beta_cash_app_score"": 0.2842936170622742, ""a...",0.284294,2025-06-28 11:14:42,2025-07-04 04:48:55,2025-06
418895,3672134,868693e2-4b5b-4f23-9716-86f729aef446,2025-12-23T22:27:22.810749,2025-12-23T22:27:22.810749,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 1,Train,"{""beta_cash_app_score"": 0.5997316858003313, ""a...",0.599732,2025-09-08 15:35:16,NaT,2025-09
534887,2986176,ec8a832e-bc1d-4c35-9098-52f3272f798f,2025-12-23T22:27:00.035674,2025-12-23T22:27:00.035674,apps_score_cash,v1,Quick,M,not applicable,android,Cash,apps_score_cash,Trench 1,Train,"{""beta_cash_app_score"": 0.5278872958423171, ""a...",0.527887,2024-11-01 00:17:15,NaT,2024-11

### PSI calculation

In [111]:
score_output_df = calculate_psi_with_segments(
    df=df_combined,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
)

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

print(f"Output shape: {score_output_df.shape}")
print(f"\nOutput columns: {score_output_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(score_output_df.head(20))
print(f"\nData types:")
print(score_output_df.dtypes)

Output shape: (82, 10)

Output columns: ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count', 'modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']

First few rows:
      Month scorename DateCategory  psivalues  account_count modelVersionId  \
0   2025-10     score     Training   0.000000         406044             v1
1   2025-09     score      Monthly   0.030436            521             v1
2   2025-10     score      Monthly   0.009636          24667             v1
3   2025-11     score      Monthly   0.021315          40688             v1
4   2025-12     score      Monthly   0.027029          28521             v1
5   2026-01     score      Monthly   4.993215           1965             v1
6   2026-02     score      Monthly   4.974092           1404             v1
7   2026-03     score      Monthly   6.520536             32             v1
8   2025-10     score     Training   0.000000         271448             v1
9   2025-09     score      Monthly   0.046215            378             v1
10  2025-10     score      Monthly   0.016260          17704             v1
11  2025-11     score      Monthly   0.020690          19216             v1
12  2025-12     score      Monthly   0.023237          13115             v1
13  2025-10     score     Training   0.000000          92944             v1
14  2025-09     score      Monthly   0.045757            102             v1
15  2025-10     score      Monthly   0.011338           5157             v1
16  2025-11     score      Monthly   0.014704          19281             v1
17  2025-12     score      Monthly   0.020377          12342             v1
18  2025-10     score     Training   0.000000          41652             v1
19  2025-09     score      Monthly   0.237792             41             v1

   trenchCategory new_loan_type loan_product_type osType
0              NA            NA                NA     NA
1              NA            NA                NA     NA
2              NA            NA                NA     NA
3              NA            NA                NA     NA
4              NA            NA                NA     NA
5              NA            NA                NA     NA
6              NA            NA                NA     NA
7              NA            NA                NA     NA
8        Trench 1            NA                NA     NA
9        Trench 1            NA                NA     NA
10       Trench 1            NA                NA     NA
11       Trench 1            NA                NA     NA
12       Trench 1            NA                NA     NA
13       Trench 2            NA                NA     NA
14       Trench 2            NA                NA     NA
15       Trench 2            NA                NA     NA
16       Trench 2            NA                NA     NA
17       Trench 2            NA                NA     NA
18       Trench 3            NA                NA     NA
19       Trench 3            NA                NA     NA

Data types:
Month                 object
scorename             object
DateCategory          object
psivalues            float64
account_count          int64
modelVersionId        object
trenchCategory        object
new_loan_type         object
loan_product_type     object
osType                object
dtype: object

In [112]:
print(f"The shape of the score_output_df is {score_output_df.shape}")
score_output_df['Model_Name'] = 'apps_score_cash'
score_output_df['scorename'] = score_output_df['scorename'].replace('score', 'apps_score_cash_score')
score_output_df

The shape of the score_output_df is (82, 10)

,Month,scorename,DateCategory,psivalues,account_count,modelVersionId,trenchCategory,new_loan_type,loan_product_type,osType,Model_Name
0,2025-10,apps_score_cash_score,Training,0.000000,406044,v1,NA,NA,NA,NA,apps_score_cash
1,2025-09,apps_score_cash_score,Monthly,0.030436,521,v1,NA,NA,NA,NA,apps_score_cash
2,2025-10,apps_score_cash_score,Monthly,0.009636,24667,v1,NA,NA,NA,NA,apps_score_cash
3,2025-11,apps_score_cash_score,Monthly,0.021315,40688,v1,NA,NA,NA,NA,apps_score_cash
4,2025-12,apps_score_cash_score,Monthly,0.027029,28521,v1,NA,NA,NA,NA,apps_score_cash
5,2026-01,apps_score_cash_score,Monthly,4.993215,1965,v1,NA,NA,NA,NA,apps_score_cash
6,2026-02,apps_score_cash_score,Monthly,4.974092,1404,v1,NA,NA,NA,NA,apps_score_cash
7,2026-03,apps_score_cash_score,Monthly,6.520536,32,v1,NA,NA,NA,NA,apps_score_cash
8,2025-10,apps_score_cash_score,Training,0.000000,271448,v1,Trench 1,NA,NA,NA,apps_score_cash
9,2025-09,apps_score_cash_score,Monthly,0.046215,378,v1,Trench 1,NA,NA,NA,apps_score_cash
10,2025-10,apps_score_cash_score,Monthly,0.016260,17704,v1,Trench 1,NA,NA,NA,apps_score_cash
11,2025-11,apps_score_cash_score,Monthly,0.020690,19216,v1,Trench 1,NA,NA,NA,apps_score_cash
12,2025-12,apps_score_cash_score,Monthly,0.023237,13115,v1,Trench 1,NA,NA,NA,apps_score_cash
13,2025-10,apps_score_cash_score,Training,0.000000,92944,v1,Trench 2,NA,NA,NA,apps_score_cash
14,2025-09,apps_score_cash_score,Monthly,0.045757,102,v1,Trench 2,NA,NA,NA,apps_score_cash
15,2025-10,apps_score_cash_score,Monthly,0.011338,5157,v1,Trench 2,NA,NA,NA,apps_score_cash
16,2025-11,apps_score_cash_score,Monthly,0.014704,19281,v1,Trench 2,NA,NA,NA,apps_score_cash
17,2025-12,apps_score_cash_score,Monthly,0.020377,12342,v1,Trench 2,NA,NA,NA,apps_score_cash
18,2025-10,apps_score_cash_score,Training,0.000000,41652,v1,Trench 3,NA,NA,NA,apps_score_cash
19,2025-09,apps_score_cash_score,Monthly,0.237792,41,v1,Trench 3,NA,NA,NA,apps_score_cash
20,2025-10,apps_score_cash_score,Monthly,0.032335,1806,v1,Trench 3,NA,NA,NA,apps_score_cash
21,2025-11,apps_score_cash_score,Monthly,0.014934,2191,v1,Trench 3,NA,NA,NA,apps_score_cash
22,2025-12,apps_score_cash_score,Monthly,0.022769,3064,v1,Trench 3,NA,NA,NA,apps_score_cash
23,2026-01,apps_score_cash_score,Monthly,0.035248,1965,v1,Trench 3,NA,NA,NA,apps_score_cash
24,2026-02,apps_score_cash_score,Monthly,0.074197,1404,v1,Trench 3,NA,NA,NA,apps_score_cash
25,2026-03,apps_score_cash_score,Monthly,4.429205,32,v1,Trench 3,NA,NA,NA,apps_score_cash
26,2025-10,apps_score_cash_score,Training,0.000000,271448,v1,Trench 1,Quick,NA,NA,apps_score_cash
27,2025-09,apps_score_cash_score,Monthly,0.046215,378,v1,Trench 1,Quick,NA,NA,apps_score_cash
28,2025-10,apps_score_cash_score,Monthly,0.016260,17704,v1,Trench 1,Quick,NA,NA,apps_score_cash
29,2025-11,apps_score_cash_score,Monthly,0.020690,19216,v1,Trench 1,Quick,NA,NA,apps_score_cash
30,2025-12,apps_score_cash_score,Monthly,0.023237,13115,v1,Trench 1,Quick,NA,NA,apps_score_cash
31,2025-10,apps_score_cash_score,Training,0.000000,90939,v1,Trench 2,Quick,NA,NA,apps_score_cash
32,2025-09,apps_score_cash_score,Monthly,0.042520,102,v1,Trench 2,Quick,NA,NA,apps_score_cash
33,2025-10,apps_score_cash_score,Monthly,0.011771,5157,v1,Trench 2,Quick,NA,NA,apps_score_cash
34,2025-11,apps_score_cash_score,Monthly,0.015966,19281,v1,Trench 2,Quick,NA,NA,apps_score_cash
35,2025-12,apps_score_cash_score,Monthly,0.020104,12342,v1,Trench 2,Quick,NA,NA,apps_score_cash
36,2025-10,apps_score_cash_score,Training,0.000000,20872,v1,Trench 3,Quick,NA,NA,apps_score_cash
37,2025-09,apps_score_cash_score,Monthly,0.259244,41,v1,Trench 3,Quick,NA,NA,apps_score_cash
38,2025-10,apps_score_cash_score,Monthly,0.005345,1806,v1,Trench 3,Quick,NA,NA,apps_score_cash
39,2025-11,apps_score_cash_score,Monthly,0.011924,2191,v1,Trench 3,Quick,NA,NA,apps_score_cash
40,2025-12,apps_score_cash_score,Monthly,0.024628,3064,v1,Trench 3,Quick,NA,NA,apps_score_cash
41,2026-01,apps_score_cash_score,Monthly,0.012881,1965,v1,Trench 3,Quick,NA,NA,apps_score_cash
42,2026-02,apps_score_cash_score,Monthly,0.034959,1404,v1,Trench 3,Quick,NA,NA,apps_score_cash
43,2026-03,apps_score_cash_score,Monthly,0.249559,32,v1,Trench 3,Quick,NA,NA,apps_score_cash
44,2025-10,apps_score_cash_score,Training,0.000000,271448,v1,Trench 1,Quick,not applicable,NA,apps_score_cash
45,2025-09,apps_score_cash_score,Monthly,0.046215,378,v1,Trench 1,Quick,not applicable,NA,apps_score_cash
46,2025-10,apps_score_cash_score,Monthly,0.016260,17704,v1,Trench 1,Quick,not applicable,NA,apps_score_cash
47,2025-11,apps_score_cash_score,Monthly,0.020690,19216,v1,Trench 1,Quick,not applicable,NA,apps_score_cash
48,2025-12,apps_score_cash_score,Monthly,0.023237,13115,v1,Trench 1,Quick,not applicable,NA,apps_score_cash
49,2025-10,apps_score_cash_score,Training,0.000000,90939,v1,Trench 2,Quick,not applicable,NA,apps_score_cash
50,2025-09,apps_score_cash_score,Monthly,0.042520,102,v1,Trench 2,Quick,not applicable,NA,apps_score_cash
51,2025-10,apps_score_cash_score,Monthly,0.011771,5157,v1,Trench 2,Quick,not applicable,NA,apps_score_cash
52,2025-11,apps_score_cash_score,Monthly,0.015966,19281,v1,Trench 2,Quick,not applicable,NA,apps_score_cash
53,2025-12,apps_score_cash_score,Monthly,0.020104,12342,v1,Trench 2,Quick,not applicable,NA,apps_score_cash
54,2025-10,apps_score_cash_score,Training,0.000000,20872,v1,Trench 3,Quick,not applicable,NA,apps_score_cash
55,2025-09,apps_score_cash_score,Monthly,0.259244,41,v1,Trench 3,Quick,not applicable,NA,apps_score_cash
56,2025-10,apps_score_cash_score,Monthly,0.005345,1806,v1,Trench 3,Quick,not applicable,NA,apps_score_cash
57,2025-11,apps_score_cash_score,Monthly,0.011924,2191,v1,Trench 3,Quick,not applicable,NA,apps_score_cash
58,2025-12,apps_score_cash_score,Monthly,0.024628,3064,v1,Trench 3,Quick,not applicable,NA,apps_score_cash
59,2026-01,apps_score_cash_score,Monthly,0.012881,1965,v1,Trench 3,Quick,not applicable,NA,apps_score_cash
60,2026-02,apps_score_cash_score,Monthly,0.034959,1404,v1,Trench 3,Quick,not applicable,NA,apps_score_cash
61,2026-03,apps_score_cash_score,Monthly,0.249559,32,v1,Trench 3,Quick,not applicable,NA,apps_score_cash
62,2025-10,apps_score_cash_score,Training,0.000000,271448,v1,Trench 1,Quick,not applicable,android,apps_score_cash
63,2025-09,apps_score_cash_score,Monthly,0.046215,378,v1,Trench 1,Quick,not applicable,android,apps_score_cash
64,2025-10,apps_score_cash_score,Monthly,0.016258,17702,v1,Trench 1,Quick,not applicable,android,apps_score_cash
65,2025-11,apps_score_cash_score,Monthly,0.020690,19216,v1,Trench 1,Quick,not applicable,android,apps_score_cash
66,2025-12,apps_score_cash_score,Monthly,0.023237,13115,v1,Trench 1,Quick,not applicable,android,apps_score_cash
67,2025-10,apps_score_cash_score,Training,0.000000,90939,v1,Trench 2,Quick,not applicable,android,apps_score_cash
68,2025-09,apps_score_cash_score,Monthly,0.042520,102,v1,Trench 2,Quick,not applicable,android,apps_score_cash
69,2025-10,apps_score_cash_score,Monthly,0.012016,5146,v1,Trench 2,Quick,not applicable,android,apps_score_cash
70,2025-11,apps_score_cash_score,Monthly,0.015986,19277,v1,Trench 2,Quick,not applicable,android,apps_score_cash
71,2025-12,apps_score_cash_score,Monthly,0.020104,12342,v1,Trench 2,Quick,not applicable,android,apps_score_cash
72,2025-10,apps_score_cash_score,Training,0.000000,20855,v1,Trench 3,Quick,not applicable,android,apps_score_cash
73,2025-09,apps_score_cash_score,Monthly,0.259245,41,v1,Trench 3,Quick,not applicable,android,apps_score_cash
74,2025-10,apps_score_cash_score,Monthly,0.005316,1806,v1,Trench 3,Quick,not applicable,android,apps_score_cash
75,2025-11,apps_score_cash_score,Monthly,0.011917,2190,v1,Trench 3,Quick,not applicable,android,apps_score_cash
76,2025-12,apps_score_cash_score,Monthly,0.024307,3064,v1,Trench 3,Quick,not applicable,android,apps_score_cash
77,2026-01,apps_score_cash_score,Monthly,0.012999,1965,v1,Trench 3,Quick,not applicable,android,apps_score_cash
78,2026-02,apps_score_cash_score,Monthly,0.034914,1404,v1,Trench 3,Quick,not applicable,android,apps_score_cash
79,2026-03,apps_score_cash_score,Monthly,0.249564,32,v1,Trench 3,Quick,not applicable,android,apps_score_cash
80,2025-10,apps_score_cash_score,Training,0.000000,17,v1,Trench 3,Quick,not applicable,ios,apps_score_cash
81,2025-11,apps_score_cash_score,Monthly,20.194607,1,v1,Trench 3,Quick,not applicable,ios,apps_score_cash

In [113]:
psi_results = score_output_df.copy()
table_id = "prj-prod-dataplatform.dap_ds_poweruser_playground.beta_cash_appscore_model_psi_v7"
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",  # or "WRITE_APPEND"
)
job = client.load_table_from_dataframe(psi_results, table_id, job_config=job_config)
job.result()

C:\Users\Dwaipayan\AppData\Roaming\Python\Python312\site-packages\google\cloud\bigquery\_pandas_helpers.py:483: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=prj-prod-dataplatform, location=asia-southeast1, id=5c942d93-dd13-4eea-bcdf-edea58155536>

### Beta-Cash-Stack-Model

#### Test

In [114]:
sq = """
WITH parsed as (
select customerId, digitalLoanAccountId,
case when modelDisplayName in ('Beta-Cash-Stack-Model') then 'beta_stack_model_cash' else modelDisplayName end as modelDisplayName,
modelVersionId,
start_time,
end_time,
prediction,
case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeatures,
REPLACE(REPLACE(prediction, "'", '"'), "None", "null") AS prediction_clean
FROM `prj-prod-dataplatform.audit_balance.ml_model_run_details`
where modelDisplayName in ('Beta-Cash-Stack-Model', 'beta_stack_model_cash')
),
base as
(select 
 r.customerId,r.digitalLoanAccountId,prediction score
 ,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'Cash' as product,
 'beta_stack_model_cash' Model_Name,
  trenchCategory,
   'Test' Data_selection,
  calcFeatures,
  coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m', coalesce(IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime),  r.start_time)) as Application_month, 
from parsed r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid order by cast(start_time as datetime) desc) = 1
)
select * from base where lower(new_loan_type) not like '%sil%'
;
"""

dfd = client.query(sq).to_dataframe(progress_bar_type='tqdm')
dfd.head()

Job ID ec7a551e-dd43-4372-aa4e-f5c2862d01a1 successfully executed: 100%|██████████|
Downloading: 100%|██████████|

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1000481,2d1f037f-f934-4171-8094-2c1fdd79bbb7,0.5989452040453195,2025-12-18 19:30:36.998531,2025-12-18 19:30:37.434402,beta_stack_model_cash,v1.1,Quick,M,not applicable,ios,Cash,beta_stack_model_cash,Trench 2,Test,"{""demo_score"": ""0.5978094974888332"", ""credo_sc...",2025-12-18 15:43:00,NaT,2025-12
1,1010940,0d550cf4-de2e-4761-b82b-b979270c7ca5,0.514535892669528,2025-12-13 01:49:38.376290,2025-12-13 01:49:40.469243,beta_stack_model_cash,v1,Quick,F,not applicable,android,Cash,beta_stack_model_cash,Trench 3,Test,"{""demo_score"": ""0.4479766423106986"", ""credo_sc...",2025-12-13 09:49:28,NaT,2025-12
2,1011117,de262fa1-f813-489d-910c-7daa208aa362,0.1496989023186311,2025-12-29 13:30:35.467003,2025-12-29 13:30:36.812757,beta_stack_model_cash,v1.1,Quick,F,not applicable,android,Cash,beta_stack_model_cash,Trench 2,Test,"{""demo_score"": ""0.3698099225729743"", ""credo_sc...",2025-12-29 21:30:30,NaT,2025-12
3,1015170,385bd22e-5851-4fa4-9242-7bc9348290e9,0.29151146719459664,2026-02-21 00:52:21.861728,2026-02-21 00:52:23.241779,beta_stack_model_cash,v1.1,Quick,M,not applicable,android,Cash,beta_stack_model_cash,Trench 2,Test,"{""demo_score"": ""0.4570646280972322"", ""credo_sc...",2026-02-21 08:52:16,2026-02-21 16:51:21,2026-02
4,1022474,0a3dd2ae-94a7-402b-980a-d626754acd06,0.16210943791768298,2025-11-15 13:21:56.376297,2025-11-15 13:21:57.107963,beta_stack_model_cash,v1,Quick,M,not applicable,android,Cash,beta_stack_model_cash,Trench 2,Test,"{""demo_score"": ""0.6313409233802605"", ""credo_sc...",2025-11-15 21:21:52,NaT,2025-11

In [115]:
df1 = dfd.copy()

#### Train

In [116]:
sq = """ 
WITH parsed as (
select customerId, digitalLoanAccountId,
case when modelDisplayName in ('Beta-Cash-Stack-Model') then 'beta_stack_model_cash' else modelDisplayName end modelDisplayName,
modelVersionId,start_time,end_time,prediction,
case when trenchCategory is null then 'ALL' 
         when trenchCategory='' then 'ALL'    
            else trenchCategory end trenchCategory,
REPLACE(REPLACE(calcFeature, "'", '"'), "None", "null") AS calcFeatures,
FROM prj-prod-dataplatform.dap_ds_poweruser_playground.ml_training_model_run_details
where modelDisplayName in ('Beta-Cash-Stack-Model', 'beta_stack_model_cash')
),
base as
(select 
 r.customerId,r.digitalLoanAccountId,prediction score
 ,start_time,end_time,
  modelDisplayName,modelVersionId,
     loanmaster.new_loan_type ,
 loanmaster.gender,
    case when loanmaster.loantype='BNPL' and sil_category.store_type =1 then 'Appliance'
    when loanmaster.loantype='BNPL' and sil_category.store_type =2 then 'Mobile'
    when loanmaster.loantype='BNPL' and sil_category.store_type =3 then 'Mall'
    when loanmaster.loantype='BNPL' and sil_category.store_type not in (1,2,3) then store_tagging
    else 'not applicable' end as loan_product_type,
     case when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%andro%' then 'android'
    when lower(coalesce(loanmaster.osversion_v2, loanmaster.osVersion)) like '%os%' then 'ios'
    when lower(loanmaster.deviceType) like '%andro%' then 'android'
    else 'ios' end osType,
 'Cash' as product,
 'beta_stack_model_cash' Model_Name,
  trenchCategory,
   'Train' Data_selection,
  calcFeatures,
  IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime) AS appln_submit_datetime,
  loanmaster.disbursementDateTime,
  format_date('%Y-%m',IF(loanmaster.new_loan_type = 'Flex-up', loanmaster.startApplyDateTime, loanmaster.termsAndConditionsSubmitDateTime)) as Application_month, 
from parsed r
left join risk_credit_mis.loan_master_table loanmaster
  ON loanmaster.digitalLoanAccountId = r.digitalLoanAccountId
 left join(SELECT DISTINCT mer_refferal_code, mer_name mer_name,store_type,store_tagging FROM `dl_loans_db_raw.tdbk_merchant_refferal_mtb`
  left join worktable_datachampions.TARGET_SPLIT P on P.STORE_NAME = mer_name
 qualify row_number() over(partition by mer_refferal_code order by  created_dt desc)=1) sil_category on loanmaster.purpleKey=sil_category.mer_refferal_code
  qualify row_number() over(partition by r.customerId, r.digitalLoanAccountid order by cast(start_time as datetime) desc) = 1
)
select * from base where lower(new_loan_type) not like '%sil%'
;
"""

dfd = client.query(sq).to_dataframe(progress_bar_type='tqdm')
dfd.head()

Job ID 213e4591-2ae1-47cc-9459-ac36871ee1d8 successfully executed: 100%|██████████|
Downloading: 100%|██████████|

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
0,1000793,d6740edf-8a03-40b9-b2c0-4143ae091e1e,0.587510,2025-12-23T22:26:23.571169,2025-12-23T22:26:23.571169,beta_stack_model_cash,v1,Quick,M,not applicable,android,Cash,beta_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.5720976557628832, ""apps_score...",2025-09-20 09:10:10,NaT,2025-09
1,1000979,5d93a6d8-b7a0-4867-86e2-90e4252a381f,0.888538,2025-12-23T22:26:27.154847,2025-12-23T22:26:27.154847,beta_stack_model_cash,v1,Quick,F,not applicable,android,Cash,beta_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.5892459407113142, ""apps_score...",2025-08-19 21:17:00,NaT,2025-08
2,1009195,5383165a-4fb6-4594-871b-21c9687e114a,0.602939,2025-12-23T22:26:26.854441,2025-12-23T22:26:26.854441,beta_stack_model_cash,v1,Quick,M,not applicable,android,Cash,beta_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.5841934192828128, ""apps_score...",2025-03-04 12:25:14,NaT,2025-03
3,1011842,7e943ca0-6e91-4a8a-b682-8f7d1823c8c2,0.434104,2025-12-23T22:26:27.810060,2025-12-23T22:26:27.810060,beta_stack_model_cash,v1,Quick,M,not applicable,android,Cash,beta_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.5671519818476471, ""apps_score...",2024-12-01 22:31:00,NaT,2024-12
4,1018775,c6cb479d-b297-4817-8a4f-e1f3c7ccc7ba,0.301928,2025-12-23T22:26:26.741400,2025-12-23T22:26:26.741400,beta_stack_model_cash,v1,Quick,M,not applicable,android,Cash,beta_stack_model_cash,Trench 2,Train,"{""demo_score"": 0.485839547653176, ""apps_score""...",2025-02-27 19:46:17,NaT,2025-02

In [117]:
df2 = dfd.copy()

In [118]:
df_concat = pd.concat([df1, df2], ignore_index=True)
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")

The shape of the concatenated dataframe is: (814187, 19)

In [119]:
print(f"The shape of the concatenated dataframe is: {df_concat.shape}")
df_combined = dropping_duplicates(df_concat)
print(f"The shape of the dataframe after dropping duplicates is: {df_combined.shape}")

The shape of the concatenated dataframe is: (814187, 19)
The shape of the dataframe after dropping duplicates is: (814187, 19)

In [120]:
df_combined['score'] = pd.to_numeric(df_combined['score'], errors='coerce')

In [121]:
df_combined.sample(10)

,customerId,digitalLoanAccountId,score,start_time,end_time,modelDisplayName,modelVersionId,new_loan_type,gender,loan_product_type,osType,product,Model_Name,trenchCategory,Data_selection,calcFeatures,appln_submit_datetime,disbursementDateTime,Application_month
777133,3042892,0f828622-4c5e-4e76-b56b-f1d9c753676e,0.534253,2025-12-23T22:26:03.867067,2025-12-23T22:26:03.867067,beta_stack_model_cash,v1,Quick,F,not applicable,ios,Cash,beta_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.5772199212445487, ""credo_scor...",2024-11-21 12:00:37,NaT,2024-11
121365,3351844,6341f2d0-79af-46d7-b129-87263bd8ac7f,0.917166,2025-11-20 09:12:04.963769,2025-11-20 09:12:05.765100,beta_stack_model_cash,v1,Quick,F,not applicable,android,Cash,beta_stack_model_cash,Trench 2,Test,"{""demo_score"": ""0.595203645145016"", ""credo_sco...",2025-11-20 17:12:00,NaT,2025-11
607804,3425619,8e48f1f9-fa95-4737-9c14-cdb982a5ace3,0.457156,2025-12-23T22:25:58.197797,2025-12-23T22:25:58.197797,beta_stack_model_cash,v1,Quick,F,not applicable,ios,Cash,beta_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.4454552921217291, ""credo_scor...",2025-05-14 05:52:43,NaT,2025-05
706246,3550732,95734edc-4d82-4af6-be25-592686436007,0.716157,2025-12-23T22:26:05.623264,2025-12-23T22:26:05.623264,beta_stack_model_cash,v1,Quick,F,not applicable,ios,Cash,beta_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.612386404583913, ""credo_score...",2025-07-11 16:23:53,NaT,2025-07
257488,4100836,52250c04-baf7-4504-a353-a774be40b212,0.761161,2026-02-16 06:33:31.901111,2026-02-16 06:33:32.764892,beta_stack_model_cash,v1.1,Quick,M,not applicable,android,Cash,beta_stack_model_cash,Trench 1,Test,"{""demo_score"": ""0.5687304582264378"", ""credo_sc...",2026-02-16 14:33:24,NaT,2026-02
738878,3208782,748e0712-9c79-4719-9c51-881976ab0321,0.850601,2025-12-23T22:25:51.771846,2025-12-23T22:25:51.771846,beta_stack_model_cash,v1,Quick,M,not applicable,android,Cash,beta_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.6321676871980103, ""apps_score...",2025-01-23 06:43:54,NaT,2025-01
305598,4025210,681bef17-1412-4cfa-8685-ede4a104f1bd,0.638999,2026-01-19 14:49:22.241698,2026-01-19 14:49:23.107677,beta_stack_model_cash,v1.1,Quick,M,not applicable,android,Cash,beta_stack_model_cash,Trench 1,Test,"{""demo_score"": ""0.37937999612120143"", ""credo_s...",2026-01-19 22:49:17,NaT,2026-01
261668,3497894,d80973c7-e020-4e05-b89d-3f098ebf0297,0.514933,2025-11-18 08:10:52.927769,2025-11-18 08:10:53.672976,beta_stack_model_cash,v1,Quick,F,not applicable,android,Cash,beta_stack_model_cash,Trench 2,Test,"{""demo_score"": ""0.4800956096800759"", ""credo_sc...",2025-11-18 16:10:49,NaT,2025-11
390787,2949732,f20aaa62-32c7-4b44-a248-8f930180c20c,0.711061,2025-12-23T22:25:46.878449,2025-12-23T22:25:46.878449,beta_stack_model_cash,v1,Quick,F,not applicable,android,Cash,beta_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.6254968296434815, ""apps_score...",2024-10-18 02:35:46,NaT,2024-10
505159,3401117,69809f64-6efb-4de7-a800-1cc5c2ab5f31,0.845500,2025-12-23T22:25:46.495952,2025-12-23T22:25:46.495952,beta_stack_model_cash,v1,Quick,F,not applicable,android,Cash,beta_stack_model_cash,Trench 1,Train,"{""demo_score"": 0.584789218191363, ""apps_score""...",2025-04-25 13:16:39,NaT,2025-04

### PSI calculation

In [122]:
score_output_df = calculate_psi_with_segments(
    df=df_combined,
    score_column='score',
    date_column='Application_month',
    data_selection_column='Data_selection',
    segment_columns=['modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']
)

# This will create waterfall levels:
# Level 1: Only modelVersionId
# Level 2: modelVersionId + trenchCategory
# Level 3: modelVersionId + trenchCategory + new_loan_type
# Level 4: modelVersionId + trenchCategory + new_loan_type + loan_product_type
# Level 5: modelVersionId + trenchCategory + new_loan_type + loan_product_type + osType

print(f"Output shape: {score_output_df.shape}")
print(f"\nOutput columns: {score_output_df.columns.tolist()}")
print(f"\nFirst few rows:")
print(score_output_df.head(20))
print(f"\nData types:")
print(score_output_df.dtypes)

Output shape: (106, 10)

Output columns: ['Month', 'scorename', 'DateCategory', 'psivalues', 'account_count', 'modelVersionId', 'trenchCategory', 'new_loan_type', 'loan_product_type', 'osType']

First few rows:
      Month scorename DateCategory  psivalues  account_count modelVersionId  \
0   2025-10     score     Training   0.000000         488440             v1
1   2025-09     score      Monthly   0.026940            803             v1
2   2025-10     score      Monthly   0.006787          35272             v1
3   2025-11     score      Monthly   0.009895          58553             v1
4   2025-12     score      Monthly   0.009527          39042             v1
5   2026-01     score      Monthly   2.376856           2898             v1
6   2026-02     score      Monthly   2.379528           2257             v1
7   2026-03     score      Monthly   4.465387             51             v1
8   2025-10     score     Training   0.000000         324344             v1
9   2025-09     score      Monthly   0.033305            578             v1
10  2025-10     score      Monthly   0.004550          24909             v1
11  2025-11     score      Monthly   0.005843          26229             v1
12  2025-12     score      Monthly   0.009239          16024             v1
13  2026-02     score      Monthly  20.723307              1             v1
14  2026-03     score      Monthly  20.723307              1             v1
15  2025-10     score     Training   0.000000         121682             v1
16  2025-09     score      Monthly   0.057032            164             v1
17  2025-10     score      Monthly   0.012284           7744             v1
18  2025-11     score      Monthly   0.009222          29134             v1
19  2025-12     score      Monthly   0.016633          18476             v1

   trenchCategory new_loan_type loan_product_type osType
0              NA            NA                NA     NA
1              NA            NA                NA     NA
2              NA            NA                NA     NA
3              NA            NA                NA     NA
4              NA            NA                NA     NA
5              NA            NA                NA     NA
6              NA            NA                NA     NA
7              NA            NA                NA     NA
8        Trench 1            NA                NA     NA
9        Trench 1            NA                NA     NA
10       Trench 1            NA                NA     NA
11       Trench 1            NA                NA     NA
12       Trench 1            NA                NA     NA
13       Trench 1            NA                NA     NA
14       Trench 1            NA                NA     NA
15       Trench 2            NA                NA     NA
16       Trench 2            NA                NA     NA
17       Trench 2            NA                NA     NA
18       Trench 2            NA                NA     NA
19       Trench 2            NA                NA     NA

Data types:
Month                 object
scorename             object
DateCategory          object
psivalues            float64
account_count          int64
modelVersionId        object
trenchCategory        object
new_loan_type         object
loan_product_type     object
osType                object
dtype: object

In [123]:
print(f"The shape of the score_output_df is {score_output_df.shape}")
score_output_df['Model_Name'] = 'beta_stack_model_cash'
score_output_df['scorename'] = score_output_df['scorename'].replace('score', 'beta_stack_model_cash_score')
score_output_df

The shape of the score_output_df is (106, 10)

,Month,scorename,DateCategory,psivalues,account_count,modelVersionId,trenchCategory,new_loan_type,loan_product_type,osType,Model_Name
0,2025-10,beta_stack_model_cash_score,Training,0.000000,488440,v1,NA,NA,NA,NA,beta_stack_model_cash
1,2025-09,beta_stack_model_cash_score,Monthly,0.026940,803,v1,NA,NA,NA,NA,beta_stack_model_cash
2,2025-10,beta_stack_model_cash_score,Monthly,0.006787,35272,v1,NA,NA,NA,NA,beta_stack_model_cash
3,2025-11,beta_stack_model_cash_score,Monthly,0.009895,58553,v1,NA,NA,NA,NA,beta_stack_model_cash
4,2025-12,beta_stack_model_cash_score,Monthly,0.009527,39042,v1,NA,NA,NA,NA,beta_stack_model_cash
...,...,...,...,...,...,...,...,...,...,...,...
101,2025-11,beta_stack_model_cash_score,Monthly,0.030953,1000,v1,Trench 3,Quick,not applicable,ios,beta_stack_model_cash
102,2025-12,beta_stack_model_cash_score,Monthly,0.105993,1478,v1,Trench 3,Quick,not applicable,ios,beta_stack_model_cash
103,2026-01,beta_stack_model_cash_score,Monthly,0.010983,933,v1,Trench 3,Quick,not applicable,ios,beta_stack_model_cash
104,2026-02,beta_stack_model_cash_score,Monthly,0.026782,852,v1,Trench 3,Quick,not applicable,ios,beta_stack_model_cash
105,2026-03,beta_stack_model_cash_score,Monthly,4.423737,18,v1,Trench 3,Quick,not applicable,ios,beta_stack_model_cash

In [124]:
psi_results = score_output_df.copy()
table_id = "prj-prod-dataplatform.dap_ds_poweruser_playground.beta_cash_stack_model_psi_v7"
job_config = bigquery.LoadJobConfig(
    write_disposition="WRITE_TRUNCATE",  # or "WRITE_APPEND"
)
job = client.load_table_from_dataframe(psi_results, table_id, job_config=job_config)
job.result()

C:\Users\Dwaipayan\AppData\Roaming\Python\Python312\site-packages\google\cloud\bigquery\_pandas_helpers.py:483: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

LoadJob<project=prj-prod-dataplatform, location=asia-southeast1, id=f65f9c7b-00e4-4492-a63a-65fe251e1a7e>

# End